//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@interface _XYYCGImage : NSObject <NSCoding, NSCopying>
{
    struct CGImage *_CGImage;
}

+ (id)imageWithCGImage:(struct CGImage *)arg1;
@property(nonatomic) struct CGImage *CGImage; // @synthesize CGImage=_CGImage;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

