//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol ADJLogger, OS_dispatch_source;

@interface ADJTimerCycle : NSObject
{
    _Bool _suspended;
    NSObject<OS_dispatch_source> *_source;
    id <ADJLogger> _logger;
    NSString *_name;
}

+ (id)timerWithBlock:(CDUnknownBlockType)arg1 queue:(id)arg2 startTime:(double)arg3 intervalTime:(double)arg4 name:(id)arg5;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) __weak id <ADJLogger> logger; // @synthesize logger=_logger;
@property(nonatomic) _Bool suspended; // @synthesize suspended=_suspended;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancel;
- (void)suspend;
- (void)resume;
- (id)initBlock:(CDUnknownBlockType)arg1 queue:(id)arg2 startTime:(double)arg3 intervalTime:(double)arg4 name:(id)arg5;

@end

