//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface APEncryptorAES : NSObject
{
}

+ (id)dataForHexString:(id)arg1;
+ (id)hexStringForData:(id)arg1;

@end

