//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "APMGPBMessage.h"

@interface APMGPBBoolValue : APMGPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool value; // @dynamic value;

@end

