//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "APMGPBMessage.h"

@interface APMGPBFloatValue : APMGPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) float value; // @dynamic value;

@end

