//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol APMLogging <NSObject>
- (void)logMessage:(NSString *)arg1 logTag:(NSString *)arg2 messageCode:(long long)arg3 withLogLevel:(long long)arg4;
@end

