//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface APMMonitoringSampledData : NSObject
{
    NSMutableArray *_sampledData;
}

+ (id)sampledDataEntryWithKey:(id)arg1 timestamp:(id)arg2 context:(id)arg3 population:(id)arg4;
+ (id)monitoringURLParamWithKey:(id)arg1 population:(id)arg2 context:(id)arg3;
+ (_Bool)isValidUserDefaultsArrayEntry:(id)arg1;
- (void).cxx_destruct;
- (id)sampledData;
- (id)monitoringDataForDispatchWithSamplePeriod:(double)arg1 lastSampledTimestamp:(double)arg2;
- (void)insertOrUpdateSampledDataWithKey:(id)arg1 encodedContext:(id)arg2;
- (id)initWithArray:(id)arg1;

@end

