//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class APMEvent;

@interface APMRawEventData : NSObject
{
    APMEvent *_rawEvent;
    long long _rowID;
    long long _metadataFingerprint;
}

@property(readonly, nonatomic) long long metadataFingerprint; // @synthesize metadataFingerprint=_metadataFingerprint;
@property(readonly, nonatomic) long long rowID; // @synthesize rowID=_rowID;
@property(readonly, nonatomic) APMEvent *rawEvent; // @synthesize rawEvent=_rawEvent;
- (void).cxx_destruct;
- (id)initWithRawEvent:(id)arg1 rowID:(long long)arg2 metadataFingerprint:(long long)arg3;

@end

