//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface APURLTool : NSObject
{
}

+ (id)urlDecode:(id)arg1 count:(long long)arg2;
+ (id)urlEncode:(id)arg1 count:(long long)arg2;

@end

