//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSCognitoIdentityIdentityPoolShortDescription : AWSModel
{
    NSString *_identityPoolId;
    NSString *_identityPoolName;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *identityPoolName; // @synthesize identityPoolName=_identityPoolName;
@property(retain, nonatomic) NSString *identityPoolId; // @synthesize identityPoolId=_identityPoolId;
- (void).cxx_destruct;

@end

