//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AWSDDLogger, OS_dispatch_queue;

@interface AWSDDLoggerNode : NSObject
{
    id <AWSDDLogger> _logger;
    unsigned long long _level;
    NSObject<OS_dispatch_queue> *_loggerQueue;
}

+ (id)nodeWithLogger:(id)arg1 loggerQueue:(id)arg2 level:(unsigned long long)arg3;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *loggerQueue; // @synthesize loggerQueue=_loggerQueue;
@property(readonly, nonatomic) unsigned long long level; // @synthesize level=_level;
@property(readonly, nonatomic) id <AWSDDLogger> logger; // @synthesize logger=_logger;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithLogger:(id)arg1 loggerQueue:(id)arg2 level:(unsigned long long)arg3;

@end

