//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AWSDDLogFormatter-Protocol.h"

@class NSArray, NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface AWSDDMultiFormatter : NSObject <AWSDDLogFormatter>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_formatters;
}

- (void).cxx_destruct;
- (_Bool)isFormattingWithFormatter:(id)arg1;
- (void)removeAllFormatters;
- (void)removeFormatter:(id)arg1;
- (void)addFormatter:(id)arg1;
@property(readonly) NSArray *formatters;
- (id)logMessageForLine:(id)arg1 originalMessage:(id)arg2;
- (id)formatLogMessage:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

