//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSHTTPURLResponse, NSURLRequest;

@protocol AWSHTTPURLResponseSerializer <NSObject>
- (id)responseObjectForResponse:(NSHTTPURLResponse *)arg1 originalRequest:(NSURLRequest *)arg2 currentRequest:(NSURLRequest *)arg3 data:(id)arg4 error:(id *)arg5;
- (_Bool)validateResponse:(NSHTTPURLResponse *)arg1 fromRequest:(NSURLRequest *)arg2 data:(id)arg3 error:(id *)arg4;
@end

