//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSMTLValueTransformer.h"

@interface AWSMTLReversibleValueTransformer : AWSMTLValueTransformer
{
}

+ (_Bool)allowsReverseTransformation;
- (id)reverseTransformedValue:(id)arg1;
- (id)initWithForwardBlock:(CDUnknownBlockType)arg1 reverseBlock:(CDUnknownBlockType)arg2;

@end

