//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@interface AWSS3CreateBucketConfiguration : AWSModel
{
    long long _locationConstraint;
}

+ (id)locationConstraintJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long locationConstraint; // @synthesize locationConstraint=_locationConstraint;

@end

