//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSArray, NSNumber, NSString;

@interface AWSS3ListBucketMetricsConfigurationsOutput : AWSModel
{
    NSString *_continuationToken;
    NSNumber *_isTruncated;
    NSArray *_metricsConfigurationList;
    NSString *_nextContinuationToken;
}

+ (id)metricsConfigurationListJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *nextContinuationToken; // @synthesize nextContinuationToken=_nextContinuationToken;
@property(retain, nonatomic) NSArray *metricsConfigurationList; // @synthesize metricsConfigurationList=_metricsConfigurationList;
@property(retain, nonatomic) NSNumber *isTruncated; // @synthesize isTruncated=_isTruncated;
@property(retain, nonatomic) NSString *continuationToken; // @synthesize continuationToken=_continuationToken;
- (void).cxx_destruct;

@end

