//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSRequest.h"

@class AWSS3CompletedMultipartUpload, NSString;

@interface AWSS3CompleteMultipartUploadRequest : AWSRequest
{
    NSString *_bucket;
    NSString *_key;
    AWSS3CompletedMultipartUpload *_multipartUpload;
    long long _requestPayer;
    NSString *_uploadId;
}

+ (id)requestPayerJSONTransformer;
+ (id)multipartUploadJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *uploadId; // @synthesize uploadId=_uploadId;
@property(nonatomic) long long requestPayer; // @synthesize requestPayer=_requestPayer;
@property(retain, nonatomic) AWSS3CompletedMultipartUpload *multipartUpload; // @synthesize multipartUpload=_multipartUpload;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
- (void).cxx_destruct;

@end

