//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSS3TransferUtilityTask.h"

@class AWSS3TransferUtilityUploadExpression;

@interface AWSS3TransferUtilityUploadTask : AWSS3TransferUtilityTask
{
    AWSS3TransferUtilityUploadExpression *_expression;
}

@property(retain, nonatomic) AWSS3TransferUtilityUploadExpression *expression; // @synthesize expression=_expression;
- (void).cxx_destruct;

@end

