//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSArray;

@interface AWSS3GetBucketCorsOutput : AWSModel
{
    NSArray *_CORSRules;
}

+ (id)CORSRulesJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSArray *CORSRules; // @synthesize CORSRules=_CORSRules;
- (void).cxx_destruct;

@end

