//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSURLRequestRetryHandler.h"

@interface AWSS3RequestRetryHandler : AWSURLRequestRetryHandler
{
}

- (long long)shouldRetry:(unsigned int)arg1 originalRequest:(id)arg2 response:(id)arg3 data:(id)arg4 error:(id)arg5;

@end

