//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSRequest.h"

@class AWSS3NotificationConfigurationDeprecated, NSString;

@interface AWSS3PutBucketNotificationRequest : AWSRequest
{
    NSString *_bucket;
    NSString *_contentMD5;
    AWSS3NotificationConfigurationDeprecated *_notificationConfiguration;
}

+ (id)notificationConfigurationJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) AWSS3NotificationConfigurationDeprecated *notificationConfiguration; // @synthesize notificationConfiguration=_notificationConfiguration;
@property(retain, nonatomic) NSString *contentMD5; // @synthesize contentMD5=_contentMD5;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
- (void).cxx_destruct;

@end

