//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AWSSignatureSignerUtility : NSObject
{
}

+ (id)HMACSign:(id)arg1 withKey:(id)arg2 usingAlgorithm:(unsigned int)arg3;
+ (id)hexEncode:(id)arg1;
+ (id)hash:(id)arg1;
+ (id)hashString:(id)arg1;
+ (id)sha256HMacWithData:(id)arg1 withKey:(id)arg2;

@end

