//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSMutableDictionary, NSString;

@interface AWSS3GetPreSignedURLRequest : NSObject
{
    _Bool _accelerateModeEnabled;
    NSString *_bucket;
    NSString *_key;
    long long _HTTPMethod;
    NSDate *_expires;
    double _minimumCredentialsExpirationInterval;
    NSMutableDictionary *_internalRequestParameters;
    NSMutableDictionary *_internalRequestHeaders;
}

@property(retain, nonatomic) NSMutableDictionary *internalRequestHeaders; // @synthesize internalRequestHeaders=_internalRequestHeaders;
@property(retain, nonatomic) NSMutableDictionary *internalRequestParameters; // @synthesize internalRequestParameters=_internalRequestParameters;
@property(nonatomic) double minimumCredentialsExpirationInterval; // @synthesize minimumCredentialsExpirationInterval=_minimumCredentialsExpirationInterval;
@property(retain, nonatomic) NSDate *expires; // @synthesize expires=_expires;
@property(nonatomic) long long HTTPMethod; // @synthesize HTTPMethod=_HTTPMethod;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(nonatomic, getter=isAccelerateModeEnabled) _Bool accelerateModeEnabled; // @synthesize accelerateModeEnabled=_accelerateModeEnabled;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forRequestParameter:(id)arg2;
- (void)setValue:(id)arg1 forRequestHeader:(id)arg2;
@property(retain, nonatomic) NSString *contentMD5;
@property(retain, nonatomic) NSString *contentType;
@property(readonly, nonatomic) NSDictionary *requestParameters;
@property(readonly, nonatomic) NSDictionary *requestHeaders;
- (id)init;

@end

