//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSSTSAssumedRoleUser : AWSModel
{
    NSString *_arn;
    NSString *_assumedRoleId;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *assumedRoleId; // @synthesize assumedRoleId=_assumedRoleId;
@property(retain, nonatomic) NSString *arn; // @synthesize arn=_arn;
- (void).cxx_destruct;

@end

