//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class AWSS3AnalyticsExportDestination;

@interface AWSS3StorageClassAnalysisDataExport : AWSModel
{
    AWSS3AnalyticsExportDestination *_destination;
    long long _outputSchemaVersion;
}

+ (id)outputSchemaVersionJSONTransformer;
+ (id)destinationJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long outputSchemaVersion; // @synthesize outputSchemaVersion=_outputSchemaVersion;
@property(retain, nonatomic) AWSS3AnalyticsExportDestination *destination; // @synthesize destination=_destination;
- (void).cxx_destruct;

@end

