//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class AWSS3ErrorDocument, AWSS3IndexDocument, AWSS3RedirectAllRequestsTo, NSArray;

@interface AWSS3GetBucketWebsiteOutput : AWSModel
{
    AWSS3ErrorDocument *_errorDocument;
    AWSS3IndexDocument *_indexDocument;
    AWSS3RedirectAllRequestsTo *_redirectAllRequestsTo;
    NSArray *_routingRules;
}

+ (id)routingRulesJSONTransformer;
+ (id)redirectAllRequestsToJSONTransformer;
+ (id)indexDocumentJSONTransformer;
+ (id)errorDocumentJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSArray *routingRules; // @synthesize routingRules=_routingRules;
@property(retain, nonatomic) AWSS3RedirectAllRequestsTo *redirectAllRequestsTo; // @synthesize redirectAllRequestsTo=_redirectAllRequestsTo;
@property(retain, nonatomic) AWSS3IndexDocument *indexDocument; // @synthesize indexDocument=_indexDocument;
@property(retain, nonatomic) AWSS3ErrorDocument *errorDocument; // @synthesize errorDocument=_errorDocument;
- (void).cxx_destruct;

@end

