//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSSTSDecodeAuthorizationMessageResponse : AWSModel
{
    NSString *_decodedMessage;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *decodedMessage; // @synthesize decodedMessage=_decodedMessage;
- (void).cxx_destruct;

@end

