//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSService.h"

@class AWSServiceConfiguration;

@interface AWSS3PreSignedURLBuilder : AWSService
{
    AWSServiceConfiguration *_configuration;
}

+ (void)removeS3PreSignedURLBuilderForKey:(id)arg1;
+ (id)S3PreSignedURLBuilderForKey:(id)arg1;
+ (void)registerS3PreSignedURLBuilderWithConfiguration:(id)arg1 forKey:(id)arg2;
+ (id)defaultS3PreSignedURLBuilder;
+ (void)initialize;
@property(retain, nonatomic) AWSServiceConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)getPreSignedURL:(id)arg1;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

@end

