//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSRequest.h"

@class AWSS3AccelerateConfiguration, NSString;

@interface AWSS3PutBucketAccelerateConfigurationRequest : AWSRequest
{
    AWSS3AccelerateConfiguration *_accelerateConfiguration;
    NSString *_bucket;
}

+ (id)accelerateConfigurationJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(retain, nonatomic) AWSS3AccelerateConfiguration *accelerateConfiguration; // @synthesize accelerateConfiguration=_accelerateConfiguration;
- (void).cxx_destruct;

@end

