//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class AWSS3Owner, NSArray;

@interface AWSS3GetObjectAclOutput : AWSModel
{
    NSArray *_grants;
    AWSS3Owner *_owner;
    long long _requestCharged;
}

+ (id)requestChargedJSONTransformer;
+ (id)ownerJSONTransformer;
+ (id)grantsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long requestCharged; // @synthesize requestCharged=_requestCharged;
@property(retain, nonatomic) AWSS3Owner *owner; // @synthesize owner=_owner;
@property(retain, nonatomic) NSArray *grants; // @synthesize grants=_grants;
- (void).cxx_destruct;

@end

