//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class AWSS3Condition, AWSS3Redirect;

@interface AWSS3RoutingRule : AWSModel
{
    AWSS3Condition *_condition;
    AWSS3Redirect *_redirect;
}

+ (id)redirectJSONTransformer;
+ (id)conditionJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) AWSS3Redirect *redirect; // @synthesize redirect=_redirect;
@property(retain, nonatomic) AWSS3Condition *condition; // @synthesize condition=_condition;
- (void).cxx_destruct;

@end

