//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSS3CreateBucketOutput : AWSModel
{
    NSString *_location;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *location; // @synthesize location=_location;
- (void).cxx_destruct;

@end

