//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSS3FilterRule : AWSModel
{
    long long _name;
    NSString *_value;
}

+ (id)nameJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(nonatomic) long long name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

