//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AWSRequest.h"

@class NSNumber, NSString;

@interface AWSS3ListObjectsV2Request : AWSRequest
{
    NSString *_bucket;
    NSString *_continuationToken;
    NSString *_delimiter;
    long long _encodingType;
    NSNumber *_fetchOwner;
    NSNumber *_maxKeys;
    NSString *_prefix;
    long long _requestPayer;
    NSString *_startAfter;
}

+ (id)requestPayerJSONTransformer;
+ (id)encodingTypeJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *startAfter; // @synthesize startAfter=_startAfter;
@property(nonatomic) long long requestPayer; // @synthesize requestPayer=_requestPayer;
@property(retain, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(retain, nonatomic) NSNumber *maxKeys; // @synthesize maxKeys=_maxKeys;
@property(retain, nonatomic) NSNumber *fetchOwner; // @synthesize fetchOwner=_fetchOwner;
@property(nonatomic) long long encodingType; // @synthesize encodingType=_encodingType;
@property(retain, nonatomic) NSString *delimiter; // @synthesize delimiter=_delimiter;
@property(retain, nonatomic) NSString *continuationToken; // @synthesize continuationToken=_continuationToken;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
- (void).cxx_destruct;

@end

