//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSS3PutObjectOutput.h"

@interface AWSS3TransferManagerUploadOutput : AWSS3PutObjectOutput
{
}

@end

