//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AWSModel.h"

@class NSString;

@interface AWSS3CreateBucketOutput : AWSModel
{
    NSString *_location;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) NSString *location; // @synthesize location=_location;
- (void).cxx_destruct;

@end

