//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BLYConstants : NSObject
{
}

+ (void)level:(unsigned long long)arg1 log:(id)arg2;
+ (_Bool)isDebugLogEnabled;
+ (void)enableDebugLog:(_Bool)arg1;
+ (id)defaultTLSRequestUrl;
+ (id)defaultRequestUrl;

@end

