//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSException;

@protocol BLYCrashReporterDelegate <NSObject>

@optional
- (void)willSendCrashReport;
- (void)didCaughtCrash:(NSException *)arg1;
- (void)didCrashAccidentHappened;
@end

