//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface BLYDataManagerKVOModel : NSObject
{
    NSSet *_subscribers;
    NSString *_key;
}

@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(copy, nonatomic) NSSet *subscribers; // @synthesize subscribers=_subscribers;
- (void).cxx_destruct;
- (id)description;
- (id)initWithSubscriber:(id)arg1 key:(id)arg2;

@end

