//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BLYJceStream : NSObject
{
    char *_streamBuffer;
    int _streamSize;
    int _cursor;
}

@property(nonatomic) int cursor; // @synthesize cursor=_cursor;
@property(nonatomic) int streamSize; // @synthesize streamSize=_streamSize;
@property(nonatomic) char *streamBuffer; // @synthesize streamBuffer=_streamBuffer;
- (id)description;
- (id)data;
- (id)init;

@end

