//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol BotDetectionSignalLoggerDelegate <NSObject>
- (void)logBotDetectionSignalData:(NSDictionary *)arg1 forProductName:(NSString *)arg2 forLoggerEventName:(NSString *)arg3;
@end

