//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSSet;

@protocol BotDetectionSignalsProviderDelegate <NSObject>
- (void)stopTimer;
- (void)startTimerWithTimeInterval:(double)arg1 queue:(NSObject<OS_dispatch_queue> *)arg2 block:(void (^)(void))arg3;
- (NSDictionary *)bdTelephonySignals;
- (void)addTelephonySignalsForSignalList:(NSSet *)arg1 toDictionary:(NSMutableDictionary *)arg2 usingDispatchGroup:(NSObject<OS_dispatch_group> *)arg3;
- (void)addBuildInfoSignalsForSignalList:(NSSet *)arg1 toDictionary:(NSMutableDictionary *)arg2;
- (void)addReachabilitySignalsForSignalList:(NSSet *)arg1 toDictionary:(NSMutableDictionary *)arg2;
- (void)addLocationSignalsForSignalList:(NSSet *)arg1 toDictionary:(NSMutableDictionary *)arg2;

@optional
- (_Bool)isJailBrokenDevice;
- (void)addJailbrokenSignalsForSignalList:(NSSet *)arg1 toDictionary:(NSMutableDictionary *)arg2;
@end

