//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADInternalBannerView.h"

@interface DFPInternalBannerView : GADInternalBannerView
{
}

- (void)setAdOptions:(id)arg1;
- (void)recordImpression;
- (void)resize:(struct GADAdSize)arg1;

@end

