//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EifsFileGapInfo : NSObject
{
    _Bool _bValid;
    unsigned int _fileId;
    long long _nOffset;
    long long _nLength;
    NSString *_strTmpFileName;
    NSString *_strOriFileName;
}

@property(retain) NSString *strOriFileName; // @synthesize strOriFileName=_strOriFileName;
@property(retain) NSString *strTmpFileName; // @synthesize strTmpFileName=_strTmpFileName;
@property(nonatomic) unsigned int fileId; // @synthesize fileId=_fileId;
@property(nonatomic) _Bool bValid; // @synthesize bValid=_bValid;
@property(nonatomic) long long nLength; // @synthesize nLength=_nLength;
@property(nonatomic) long long nOffset; // @synthesize nOffset=_nOffset;
- (void).cxx_destruct;
- (id)init;

@end

