//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class FBAdImage, NSString, NSURL;

@protocol FBAdReportingData
@property(readonly, copy, nonatomic) NSString *inlineClientToken;
@property(readonly, nonatomic) FBAdImage *icon;
@property(readonly, copy, nonatomic) NSURL *adChoicesLinkURL;
@end

