//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FBAdMovingAverage, OS_dispatch_queue;

@interface FBAdNetworkQuality : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    id <FBAdMovingAverage> _downloadBandwidthMovingAverage;
    id <FBAdMovingAverage> _uploadBandwidthMovingAverage;
}

@property(readonly, nonatomic) id <FBAdMovingAverage> uploadBandwidthMovingAverage; // @synthesize uploadBandwidthMovingAverage=_uploadBandwidthMovingAverage;
@property(readonly, nonatomic) id <FBAdMovingAverage> downloadBandwidthMovingAverage; // @synthesize downloadBandwidthMovingAverage=_downloadBandwidthMovingAverage;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)updateUploadBandwidthEstimate:(double)arg1;
- (void)updateDownloadBandwidthEstimate:(double)arg1;
@property(readonly, nonatomic) unsigned long long uploadBandwidthState;
@property(readonly, nonatomic) double uploadBandwidthEstimate;
@property(readonly, nonatomic) unsigned long long downloadBandwidthState;
@property(readonly, nonatomic) double downloadBandwidthEstimate;
- (void)updateUsingCountOfBytesSent:(unsigned long long)arg1 requestDurationInMiliseconds:(unsigned long long)arg2;
- (void)updateUsingTask:(id)arg1 metrics:(id)arg2;
- (id)initWithFactory:(CDUnknownBlockType)arg1;

@end

