//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBAdLabel, NSArray;

@interface FBAdStarRatingView : UIView
{
    NSArray *_starViews;
    NSArray *_starFillViews;
    FBAdLabel *_ratingCountLabel;
}

@property(retain, nonatomic) FBAdLabel *ratingCountLabel; // @synthesize ratingCountLabel=_ratingCountLabel;
@property(copy, nonatomic) NSArray *starFillViews; // @synthesize starFillViews=_starFillViews;
@property(copy, nonatomic) NSArray *starViews; // @synthesize starViews=_starViews;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setupViewWithRating:(id)arg1 ratingCount:(id)arg2;
- (id)initWithRating:(id)arg1 ratingCount:(id)arg2;

@end

