//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSUUID;

@interface FBAdEventToken : NSObject
{
    NSUUID *_tokenId;
    NSString *_token;
}

+ (id)deserializeFromSqlite:(struct sqlite3_stmt *)arg1;
+ (void)initialize;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSUUID *tokenId; // @synthesize tokenId=_tokenId;
- (void).cxx_destruct;
- (id)initWithToken:(id)arg1;

@end

