//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface FBAdSplitBackgroundView : UIView
{
    UIView *_leftView;
    UIView *_rightView;
    double _leftPercentage;
}

@property(nonatomic) double leftPercentage; // @synthesize leftPercentage=_leftPercentage;
@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *leftView; // @synthesize leftView=_leftView;
- (void).cxx_destruct;
- (id)createAndAddNewViewWithBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (id)initWithLeftColor:(id)arg1 rightColor:(id)arg2 leftPercentage:(double)arg3;

@end

