//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface FBAdLabel : UILabel
{
}

- (void)setupViewWithText:(id)arg1 numberOfLines:(unsigned long long)arg2 font:(id)arg3;
- (id)initWithText:(id)arg1 numberOfLines:(unsigned long long)arg2 font:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

