//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class FBAdDSLBridgeViewController, NSError, UIEvent;

@protocol FBAdDSLBridgeDelegate
- (void)dynamicAdViewControllerWantsToProcessCTA:(FBAdDSLBridgeViewController *)arg1 withEvent:(UIEvent *)arg2;
- (void)dynamicAdViewController:(FBAdDSLBridgeViewController *)arg1 didFailWithError:(NSError *)arg2;
- (void)dynamicAdViewControllerWillClose:(FBAdDSLBridgeViewController *)arg1;
- (void)dynamicAdViewControllerDidLoad:(FBAdDSLBridgeViewController *)arg1;
@end

