//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FBAdDSLModel, NSArray, NSMutableDictionary;

@interface FBAdDSLViewModel : NSObject
{
    NSArray *_assets;
    FBAdDSLModel *_adModel;
    NSMutableDictionary *_adRawData;
}

@property(copy, nonatomic) NSMutableDictionary *adRawData; // @synthesize adRawData=_adRawData;
@property(retain, nonatomic) FBAdDSLModel *adModel; // @synthesize adModel=_adModel;
@property(readonly, copy, nonatomic) NSArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (id)remoteHTMLFileURL;
- (id)localHTMLFileURL;
- (id)adJSONData;
- (_Bool)isLocalHTMLFileAvailable;
- (id)commonAssetsDirectoriesURL;
- (id)generateAdDataDictionary;
- (_Bool)setLocalURLForAsset:(id)arg1 withURL:(id)arg2;
- (id)initWithMetadata:(id)arg1 withSandboxAddress:(id)arg2;

@end

