//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBAdConnectionInfo : NSObject
{
}

+ (unsigned long long)statusForReachabilityFlags:(unsigned int)arg1;
+ (unsigned long long)currentReachabilityStatus;
+ (unsigned long long)currentConnectionSubtype;
+ (id)currentCellularConnection;
+ (unsigned long long)currentConnectionType;
+ (unsigned long long)typeFromSubtype:(unsigned long long)arg1;
+ (void)initialize;

@end

