//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface FBAdStoriesPageIndicatorItemView : UIView
{
    double _progress;
}

@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;

@end

