//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface FBAdMediationOverlay : UIView
{
}

+ (void)initialize;
- (_Bool)isValidImage:(id)arg1;
- (void)attachToView:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

