//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSURL;

@interface FBAdDSLModel : NSObject
{
    NSURL *_mainHTMLAsset;
    NSURL *_videoLocalAsset;
    NSURL *_imageLocalAsset;
    NSURL *_iconLocalAsset;
    NSMutableDictionary *_endCardLocalAssets;
}

@property(retain, nonatomic) NSMutableDictionary *endCardLocalAssets; // @synthesize endCardLocalAssets=_endCardLocalAssets;
@property(copy, nonatomic) NSURL *iconLocalAsset; // @synthesize iconLocalAsset=_iconLocalAsset;
@property(copy, nonatomic) NSURL *imageLocalAsset; // @synthesize imageLocalAsset=_imageLocalAsset;
@property(copy, nonatomic) NSURL *videoLocalAsset; // @synthesize videoLocalAsset=_videoLocalAsset;
@property(copy, nonatomic) NSURL *mainHTMLAsset; // @synthesize mainHTMLAsset=_mainHTMLAsset;
- (void).cxx_destruct;
- (id)init;

@end

