//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBAdDSLJSScriptMessageHandlerDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSString, WKWebView;
@protocol FBAdDSLFullScreenAdViewControllerDataSource, FBAdDSLFullScreenAdViewControllerDelegate;

@interface FBAdDSLFullScreenAdViewController : UIViewController <WKUIDelegate, WKNavigationDelegate, FBAdDSLJSScriptMessageHandlerDelegate>
{
    id <FBAdDSLFullScreenAdViewControllerDelegate> _delegate;
    id <FBAdDSLFullScreenAdViewControllerDataSource> _dataSource;
    WKWebView *_webview;
}

@property(retain, nonatomic) WKWebView *webview; // @synthesize webview=_webview;
@property(nonatomic) __weak id <FBAdDSLFullScreenAdViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <FBAdDSLFullScreenAdViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)willEvaluateJSMessage:(id)arg1;
- (void)sendEvent:(unsigned long long)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)sendMessage:(id)arg1 toWebView:(id)arg2 success:(CDUnknownBlockType)arg3 fail:(CDUnknownBlockType)arg4;
- (void)receivedJSScriptEvent:(unsigned long long)arg1 withExtraData:(id)arg2;
- (void)loadWebView;
- (void)setupWebView;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

