//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURL;

@interface FBAdDSLAsset : NSObject
{
    NSDictionary *_metaData;
    NSString *_fileName;
    NSURL *_remoteURL;
    unsigned long long _type;
}

@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) NSURL *remoteURL; // @synthesize remoteURL=_remoteURL;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) NSDictionary *metaData; // @synthesize metaData=_metaData;
- (void).cxx_destruct;
- (id)initWithAssetMetadata:(id)arg1 fileName:(id)arg2 withRemoteURLString:(id)arg3 withType:(unsigned long long)arg4;

@end

