//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class FBAdImage, NSString, NSURL;

@protocol FBAdReportingData
@property(readonly, copy, nonatomic) NSString *inlineClientToken;
@property(readonly, nonatomic) FBAdImage *icon;
@property(readonly, copy, nonatomic) NSURL *adChoicesLinkURL;
@end

