//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@protocol FBAdBrowserSessionDataGeneration <NSObject>
@property(readonly, nonatomic) unsigned long long loadFinishMs;
@property(readonly, nonatomic) unsigned long long scrollReadyMs;
@property(readonly, nonatomic) unsigned long long domContentLoadedMs;
@property(readonly, nonatomic) unsigned long long responseEndMs;
@property(readonly, nonatomic) unsigned long long loadStartMs;
@property(readonly, nonatomic) unsigned long long handlerTimeMs;
@property(readonly, copy, nonatomic) NSURL *url;
@property(readonly, copy, nonatomic) NSString *inlineClientToken;
@end

