//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdEndCardScreenshotView;

@protocol FBAdEndCardScreenshotViewDelegate <NSObject>
- (void)endCardScreenshotViewDidTerminate:(FBAdEndCardScreenshotView *)arg1;
- (void)endCardScreenshotViewWillClose:(FBAdEndCardScreenshotView *)arg1;
- (void)endCardScreenshotViewClicked:(FBAdEndCardScreenshotView *)arg1;
@end

