//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBAdEnvironmentData, FBAdProviderResponseParser, NSMutableArray, NSOperationQueue;

@interface FBAdProvider : NSObject
{
    _Bool _active;
    id <FBAdProviderDelegate> _delegate;
    FBAdProviderResponseParser *_adParser;
    FBAdEnvironmentData *_environmentData;
    NSOperationQueue *_parsingQueue;
    NSMutableArray *_requests;
    double _requestTime;
}

@property(nonatomic) double requestTime; // @synthesize requestTime=_requestTime;
@property(retain, nonatomic) NSMutableArray *requests; // @synthesize requests=_requests;
@property(retain, nonatomic) NSOperationQueue *parsingQueue; // @synthesize parsingQueue=_parsingQueue;
@property(retain, nonatomic) FBAdEnvironmentData *environmentData; // @synthesize environmentData=_environmentData;
@property(retain, nonatomic) FBAdProviderResponseParser *adParser; // @synthesize adParser=_adParser;
@property(nonatomic) __weak id <FBAdProviderDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool active; // @synthesize active=_active;
- (void).cxx_destruct;
- (void)funnelLogAdResponse:(id)arg1;
- (void)parseResponseFromData:(id)arg1 canReturnSources:(_Bool)arg2;
- (void)handleAdResponse:(id)arg1 data:(id)arg2 error:(id)arg3 canReturnSources:(_Bool)arg4 deliveryUrl:(id)arg5;
- (_Bool)maybeHandleBidPayload:(id)arg1;
- (void)makeAdRequestWithParameters:(id)arg1;
- (void)dispatchError:(id)arg1;
- (void)destroy;
- (void)cancel;
- (void)loadAdWithEnvironmentData:(id)arg1;
- (id)init;

@end

