//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FBBotDetectionCircularBuffer;

@interface FBBDAppDelegateSignalManager : NSObject
{
    FBBotDetectionCircularBuffer *_circularBuffer;
}

+ (void)setAppDelegateConfigDelegate:(id)arg1;
+ (id)appDelegateConfigDelegate;
- (void).cxx_destruct;
- (void)addSignalToCircularBfferForLifecycleEventValue:(int)arg1;
- (void)handleDidEnterBackgroundNotification;
- (void)handleDidBecomeActiveNotification;
- (id)appDelegateSignalsArray;
- (void)dealloc;
- (id)init;

@end

