//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBBotDetectionSignalCollectionManager : NSObject
{
}

+ (void)finalizeSignalsAndEvaluateLatestTierForEventId:(id)arg1 productType:(unsigned long long)arg2 eventType:(id)arg3 bdSessionIds:(id)arg4;
+ (void)sendBotDetectionSignalsForEventId:(id)arg1 productType:(unsigned long long)arg2 eventType:(id)arg3 bdSessionIds:(id)arg4;
+ (void)loadBotDetection;
+ (void)setDynamicLoadedLibraryProviderDelegate:(id)arg1;
+ (id)dynamicLoadedLibraryProviderDelegate;
+ (void)setSignalsDelegate:(id)arg1;
+ (id)signalsDelegate;
+ (void)setConfigDelegate:(id)arg1;
+ (id)configDelegate;
+ (void)setLoggerDelegate:(id)arg1;
+ (id)loggerDelegate;

@end

