//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBAdViewabilityValidatorDelegate.h"
#import "FBDisplayAdAdapterControllerDelegate.h"

@class FBAdExtraHint, FBAdViewabilityValidator, FBApplicationInterfaceOrientationProvider, FBDisplayAdAdapterController, NSString;

@interface FBDisplayAdController : NSObject <FBAdViewabilityValidatorDelegate, FBDisplayAdAdapterControllerDelegate>
{
    _Bool _initialized;
    _Bool _loaded;
    _Bool _started;
    _Bool _adapterHadImpression;
    _Bool _controllerHadImpression;
    id <FBDisplayAdControllerDelegate> _delegate;
    FBAdExtraHint *_extraHint;
    FBAdViewabilityValidator *_viewabilityValidator;
    FBApplicationInterfaceOrientationProvider *_interfaceOrientationProvider;
    FBDisplayAdAdapterController *_adapterController;
    double _requestTime;
    NSObject *_adInterface;
}

+ (void)initialize;
@property(retain, nonatomic) NSObject *adInterface; // @synthesize adInterface=_adInterface;
@property(nonatomic) double requestTime; // @synthesize requestTime=_requestTime;
@property(retain, nonatomic) FBDisplayAdAdapterController *adapterController; // @synthesize adapterController=_adapterController;
@property(retain, nonatomic) FBApplicationInterfaceOrientationProvider *interfaceOrientationProvider; // @synthesize interfaceOrientationProvider=_interfaceOrientationProvider;
@property(nonatomic) _Bool controllerHadImpression; // @synthesize controllerHadImpression=_controllerHadImpression;
@property(nonatomic) _Bool adapterHadImpression; // @synthesize adapterHadImpression=_adapterHadImpression;
@property(nonatomic) _Bool started; // @synthesize started=_started;
@property(nonatomic) _Bool loaded; // @synthesize loaded=_loaded;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
@property(retain, nonatomic) FBAdViewabilityValidator *viewabilityValidator; // @synthesize viewabilityValidator=_viewabilityValidator;
@property(retain, nonatomic) FBAdExtraHint *extraHint; // @synthesize extraHint=_extraHint;
@property(nonatomic) __weak id <FBDisplayAdControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loadedAdDidClickWithAdapter:(id)arg1 withURL:(id)arg2 playerHandles:(_Bool)arg3;
- (void)loadDidFailWithAdapter:(id)arg1 withError:(id)arg2;
- (void)adWithAdapter:(id)arg1 performAction:(unsigned long long)arg2;
- (_Bool)viewabilityValidator:(id)arg1 checkedWithStatus:(long long)arg2;
- (void)startListeningToInterfaceOrientationChanges;
- (void)stopObservingNotifications;
- (void)onApplicationForegrounded;
- (void)onApplicationBackgrounded;
- (void)startObservingNotifications;
- (void)adapter:(id)arg1 didFailWithError:(id)arg2;
- (void)adapterDidLoad:(id)arg1;
- (void)disableViewabilityValidator;
- (void)ensureViewabilityValidator;
- (void)adapterServerRewardFailed:(id)arg1;
- (void)adapterServerRewardSuccess:(id)arg1;
- (void)notifyAdVideoComplete;
- (void)notifyAdUserClose;
- (void)notifyAdClickThruWithURL:(id)arg1 playerHandles:(_Bool)arg2;
- (void)notifyAdError:(id)arg1;
- (void)notifyAdStopped;
- (void)notifyAdImpression;
- (void)notifyAdViewPresented;
- (void)notifyAdLoaded;
- (_Bool)adExpired;
- (CDStruct_1b6d18a9)adapterDuration;
- (id)getPlacementDefinition;
- (void)unregisterView;
- (void)registerViewForInteraction:(id)arg1 withViewController:(id)arg2;
- (void)logImpressionFromSource:(long long)arg1;
- (_Bool)passRewardData:(id)arg1;
- (void)refresh;
- (_Bool)startAdFromRootViewController:(id)arg1 animated:(_Bool)arg2 sender:(id)arg3;
- (void)startAdapterController:(id)arg1 withEnvironment:(id)arg2 withRewardData:(id)arg3;
- (void)checkInitialization;
- (void)dealloc;
- (void)loadAdWithPlacementId:(id)arg1 withPlacementType:(long long)arg2 withTemplateID:(long long)arg3 withAdSize:(struct FBAdSize)arg4 withAdProvider:(id)arg5 withRewardData:(id)arg6 withBidPayload:(id)arg7;
- (void)loadAdWithPlacementId:(id)arg1 withPlacementType:(long long)arg2 withTemplateID:(long long)arg3 withAdSize:(struct FBAdSize)arg4 withAdProvider:(id)arg5 withRewardData:(id)arg6;
- (void)loadAdWithPlacementId:(id)arg1 withPlacementType:(long long)arg2 withTemplateID:(long long)arg3 withAdSize:(struct FBAdSize)arg4 withAdProvider:(id)arg5;
- (void)loadAdWithPlacementId:(id)arg1 withPlacementType:(long long)arg2 withTemplateID:(long long)arg3 withAdSize:(struct FBAdSize)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

