//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBAdDataModel.h"

@class NSString;

@interface FBHTMLAdDataModel : FBAdDataModel
{
    NSString *_markup;
    NSString *_activationCommand;
    long long _orientation;
}

+ (void)initialize;
@property(readonly, nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(readonly, copy, nonatomic) NSString *activationCommand; // @synthesize activationCommand=_activationCommand;
@property(readonly, copy, nonatomic) NSString *markup; // @synthesize markup=_markup;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (id)initWithMetadata:(id)arg1;

@end

