//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBInterstitialAd, NSError;

@protocol FBInterstitialAdDelegate <NSObject>

@optional
- (void)interstitialAdWillLogImpression:(FBInterstitialAd *)arg1;
- (void)interstitialAd:(FBInterstitialAd *)arg1 didFailWithError:(NSError *)arg2;
- (void)interstitialAdDidLoad:(FBInterstitialAd *)arg1;
- (void)interstitialAdWillClose:(FBInterstitialAd *)arg1;
- (void)interstitialAdDidClose:(FBInterstitialAd *)arg1;
- (void)interstitialAdDidClick:(FBInterstitialAd *)arg1;
@end

