//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface FBInterstitialAdInternal : UIViewController
{
}

- (_Bool)showAdFromRootViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)showAdFromRootViewController:(id)arg1;
- (void)loadAd;
- (id)adDataModel;
- (id)initWithPlacementID:(id)arg1 adData:(id)arg2 minViewability:(int)arg3;
- (_Bool)isAdValid;

@end

