//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBNativeAdBase, NSArray;

@protocol FBNativeAdBaseView <NSObject>
@property(readonly, copy, nonatomic) NSArray *allInteractableTargets;
- (void)populate:(FBNativeAdBase *)arg1;
@end

