//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBNativeBannerAd, NSError;

@protocol FBNativeBannerAdDelegate <NSObject>

@optional
- (void)nativeBannerAdDidFinishHandlingClick:(FBNativeBannerAd *)arg1;
- (void)nativeBannerAdDidClick:(FBNativeBannerAd *)arg1;
- (void)nativeBannerAd:(FBNativeBannerAd *)arg1 didFailWithError:(NSError *)arg2;
- (void)nativeBannerAdWillLogImpression:(FBNativeBannerAd *)arg1;
- (void)nativeBannerAdDidDownloadMedia:(FBNativeBannerAd *)arg1;
- (void)nativeBannerAdDidLoad:(FBNativeBannerAd *)arg1;
@end

