//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBSDKCrashHandler : NSObject
{
}

+ (_Bool)isSafeToGenerateMapping;
+ (id)getPathToLibDataFile:(id)arg1;
+ (id)getPathToCrashFile:(id)arg1;
+ (id)loadLibData:(id)arg1;
+ (void)generateMethodMapping:(id)arg1;
+ (void)saveCrashLog:(id)arg1;
+ (id)getCrashLogFileNames:(id)arg1;
+ (void)clearCrashReportFiles;
+ (id)loadCrashLog:(id)arg1;
+ (id)loadCrashLogs;
+ (id)getProcessedCrashLogs;
+ (void)saveSignal:(int)arg1 withCallStack:(id)arg2;
+ (void)saveException:(id)arg1;
+ (void)uninstallExceptionsHandler;
+ (void)installExceptionsHandler;
+ (void)removeObserver:(id)arg1;
+ (void)addObserver:(id)arg1;
+ (void)disable;
+ (_Bool)callstack:(id)arg1 containsPrefix:(id)arg2;
+ (id)filterCrashLogs:(id)arg1;
+ (void)sendCrashLogs;
+ (void)initialize;

@end

