//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBSDKButton.h"

#import "FBSDKSharingButton-Protocol.h"

@class FBSDKShareDialog, NSString;
@protocol FBSDKSharingContent;

@interface FBSDKShareButton : FBSDKButton <FBSDKSharingButton>
{
    FBSDKShareDialog *_dialog;
}

- (void).cxx_destruct;
- (void)_share:(id)arg1;
- (_Bool)isImplicitlyDisabled;
- (void)configureButton;
- (id)impressionTrackingIdentifier;
- (id)impressionTrackingEventName;
- (id)analyticsParameters;
@property(copy, nonatomic) id <FBSDKSharingContent> shareContent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

