//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBSDKSharing-Protocol.h"

@protocol FBSDKSharingDialog <FBSDKSharing>
@property(readonly, nonatomic) _Bool canShow;
- (_Bool)show;
@end

