//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBSDKLikeBoxBorderView, NSString, UILabel;

@interface FBSDKLikeBoxView : UIView
{
    FBSDKLikeBoxBorderView *_borderView;
    UILabel *_likeCountLabel;
    unsigned long long _caretPosition;
}

@property(nonatomic) unsigned long long caretPosition; // @synthesize caretPosition=_caretPosition;
- (void).cxx_destruct;
- (void)_initializeContent;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
@property(copy, nonatomic) NSString *text;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

