//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBSDKBase64 : NSObject
{
}

+ (id)encodeString:(id)arg1;
+ (id)encodeData:(id)arg1;
+ (id)decodeAsString:(id)arg1;
+ (id)decodeAsData:(id)arg1;
+ (void)initialize;
- (id)encodeString:(id)arg1;
- (id)encodeData:(id)arg1;
- (id)decodeAsString:(id)arg1;
- (id)decodeAsData:(id)arg1;

@end

