//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBSDKTypeUtility : NSObject
{
}

+ (id)_objectValue:(id)arg1 ofClass:(Class)arg2;
+ (id)URLValue:(id)arg1;
+ (unsigned long long)unsignedIntegerValue:(id)arg1;
+ (double)timeIntervalValue:(id)arg1;
+ (id)stringValue:(id)arg1;
+ (id)objectValue:(id)arg1;
+ (long long)integerValue:(id)arg1;
+ (id)dictionaryValue:(id)arg1;
+ (_Bool)boolValue:(id)arg1;
+ (id)arrayValue:(id)arg1;

@end

