//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSURLSessionTask;

@interface FBSDKURLSessionTask : NSObject
{
    NSURLSessionTask *_task;
    NSDate *_requestStartDate;
    CDUnknownBlockType _handler;
    unsigned long long _requestStartTime;
    unsigned long long _loggerSerialNumber;
}

@property(nonatomic) unsigned long long loggerSerialNumber; // @synthesize loggerSerialNumber=_loggerSerialNumber;
@property(nonatomic) unsigned long long requestStartTime; // @synthesize requestStartTime=_requestStartTime;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(readonly, nonatomic) NSDate *requestStartDate; // @synthesize requestStartDate=_requestStartDate;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (void)cancel;
- (void)start;
@property(readonly) long long state;
- (id)initWithRequest:(id)arg1 fromSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)init;

@end

