//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol FBSDKLoginCompleting
- (void)completeLoginWithHandler:(void (^)(FBSDKLoginCompletionParameters *))arg1;
@end

