//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MCSessionDelegate.h"

@class MCPeerID, MCSession, NSString;

@interface FGameCenterSessionDelegateMC : UIViewController <MCSessionDelegate>
{
    MCSession *Session;
    MCPeerID *PeerID;
}

@property(retain, nonatomic) MCPeerID *PeerID; // @synthesize PeerID;
@property(retain, nonatomic) MCSession *Session; // @synthesize Session;
- (void)session:(id)arg1 peer:(id)arg2 didChangeState:(long long)arg3;
- (void)session:(id)arg1 didReceiveStream:(id)arg2 withName:(id)arg3 fromPeer:(id)arg4;
- (void)session:(id)arg1 didFinishReceivingResourceWithName:(id)arg2 fromPeer:(id)arg3 atURL:(id)arg4 withError:(id)arg5;
- (void)session:(id)arg1 didStartReceivingResourceWithName:(id)arg2 fromPeer:(id)arg3 withProgress:(id)arg4;
- (void)session:(id)arg1 didReceiveData:(id)arg2 fromPeer:(id)arg3;
- (void)joinSession;
- (_Bool)sessionsAvailable;
- (void)shutdownSession;
- (void)dealloc;
- (id)initSessionWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

