//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FileManager : NSObject
{
    _Bool _isCreateDirectory;
    _Bool _isCreateCacheFile;
    _Bool _isCreateZipFile;
    struct __sFILE *_dstFilePtr;
    NSString *_cacheFileName;
    NSString *_cacheDirectoryPath;
}

+ (id)sharedFileManager;
@property(copy, nonatomic) NSString *cacheDirectoryPath; // @synthesize cacheDirectoryPath=_cacheDirectoryPath;
@property(copy, nonatomic) NSString *cacheFileName; // @synthesize cacheFileName=_cacheFileName;
- (void).cxx_destruct;
- (void)closeFilePtr;
- (void)clearAllZipFile;
- (void)removeFilePath:(id)arg1;
- (_Bool)segmentZip:(const char *)arg1 desPath:(const char *)arg2;
- (_Bool)uploadToServer:(id)arg1;
- (_Bool)createCacheFileName:(id)arg1;
- (_Bool)flushBufferToFile:(const char *)arg1 bufferLen:(unsigned long long)arg2;
- (id)showAllUnUploadCachedFile;
- (id)constructCachePath:(id)arg1;
- (id)init;

@end

