//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CADisplayLink;

@interface FIOSFramePacer : NSObject
{
    struct FEvent *FramePacerEvent;
    CADisplayLink *displayLink;
}

- (void)signal:(id)arg1;
- (void)run:(id)arg1;

@end

