//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIOSAsyncTask : NSObject
{
    int bIsReadyForGameThread;
    id UserData;
    CDUnknownBlockType GameThreadCallback;
}

+ (void)ProcessAsyncTasks;
+ (void)CreateTaskWithBlock:(CDUnknownBlockType)arg1;
+ (void)initialize;
@property(copy) CDUnknownBlockType GameThreadCallback; // @synthesize GameThreadCallback;
@property(retain) id UserData; // @synthesize UserData;
- (void)dealloc;
- (_Bool)CheckForCompletion;
- (void)FinishedTask;
- (id)init;

@end

