//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FIRAnalyticsConfiguration : NSObject
{
}

+ (id)sharedInstance;
- (void)setAnalyticsCollectionEnabled:(_Bool)arg1 persistSetting:(_Bool)arg2;
- (void)setAnalyticsCollectionEnabled:(_Bool)arg1;
- (void)postNotificationName:(id)arg1 value:(id)arg2;

@end

