//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FIRConnectorUtils : NSObject
{
}

+ (_Bool)isUserPropertyAllowed:(id)arg1 withOrigin:(id)arg2;
+ (_Bool)shouldLogEventWithName:(id)arg1 parameters:(id)arg2;
+ (_Bool)isEventNameAllowedForListeners:(id)arg1;
+ (_Bool)isListenerOriginAllowed:(id)arg1;
+ (_Bool)isOriginAllowed:(id)arg1;
+ (id)hiddenEventNames;
+ (id)blacklistedUserPropertyPatterns;
+ (id)blacklistedUserProperties;
+ (id)blacklistedParameters;
+ (id)blacklistedEventNames;
+ (id)blacklistedOrigins;
+ (id)allowedListenerOrigins;

@end

