//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FIRInstanceIDCheckinPreferences, FIRInstanceIDStore;

@protocol FIRInstanceIDStoreDelegate <NSObject>
- (void)store:(FIRInstanceIDStore *)arg1 didDeleteFCMScopedTokensForCheckin:(FIRInstanceIDCheckinPreferences *)arg2;
@end

