//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FIRMessaging, FIRMessagingRemoteMessage, NSString;

@protocol FIRMessagingDelegate <NSObject>

@optional
- (void)messaging:(FIRMessaging *)arg1 didReceiveMessage:(FIRMessagingRemoteMessage *)arg2;
- (void)messaging:(FIRMessaging *)arg1 didReceiveRegistrationToken:(NSString *)arg2;
@end

