//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FApplePlatformObject.h"

@interface FMetalDeferredStats : FApplePlatformObject
{
    unsigned long long TextureSize;
    int TexType;
    _Bool bIsRenderTarget;
}

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (CDStruct_eb6fb79d *)classAllocator;
- (void)dealloc;

@end

