//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FApplePlatformObject.h"

#import "NSObject-Protocol.h"

@class NSString;

@interface FMetalBufferData : FApplePlatformObject <NSObject>
{
    char *Data;
    unsigned int Len;
}

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (CDStruct_eb6fb79d *)classAllocator;
- (void)dealloc;
- (id)initWithBytes:(const void *)arg1 length:(unsigned int)arg2;
- (id)initWithSize:(unsigned int)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

