//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError;

@protocol FNFAtomManagerDelegate
- (void)reportWarning:(NSError *)arg1;
- (void)resetDataForSeekBackForTrack:(long long)arg1;
- (void)resetDataForSeekBack;
- (void)parsingDidFailWithError:(NSError *)arg1;
@end

