//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol FNFPlayerAudioDecoder <NSObject>
- (void)reset;
- (_Bool)decodeToBuffer:(struct AudioQueueBuffer *)arg1 frame:(struct FNFFrameMetadata)arg2 frameData:(const char *)arg3;
- (void)setAudioStreamBasicDescription:(struct AudioStreamBasicDescription)arg1 extraParameters:(NSDictionary *)arg2 errorCallback:(void (^)(NSError *))arg3;
@end

