//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FNFPlayerRenderer-Protocol.h"

@class NSString;

@protocol FNFPlayerGLRenderer <FNFPlayerRenderer>
- (void)invalidate;
- (void)restoreGLState;
- (_Bool)drawFrame:(_Bool)arg1 presentationRect:(struct CGSize)arg2 backingWidth:(int)arg3 backingHeight:(int)arg4 frameBuffer:(unsigned int)arg5 videoGravity:(NSString *)arg6 rotation:(double)arg7 layerBounds:(struct CGRect)arg8 transform:(struct CGAffineTransform)arg9 colorConversion:(long long)arg10;
- (_Bool)setupGLState;
@end

