//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDecimalNumber, NSString;

@interface GADAdValue : NSObject <NSCopying>
{
    long long _precision;
    NSDecimalNumber *_value;
    NSString *_currencyCode;
}

@property(readonly, nonatomic) NSString *currencyCode; // @synthesize currencyCode=_currencyCode;
@property(readonly, nonatomic) NSDecimalNumber *value; // @synthesize value=_value;
@property(readonly, nonatomic) long long precision; // @synthesize precision=_precision;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithValue:(id)arg1 currencyCode:(id)arg2 precision:(long long)arg3;

@end

