//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADObserverCollection, GADWebAdView;

@interface GADAnimateViewActionMonitor : NSObject
{
    GADObserverCollection *_observers;
    GADWebAdView *_weakAdView;
}

- (void).cxx_destruct;
- (void)handleAnimations:(id)arg1 withDuration:(double)arg2 requestIdentifier:(id)arg3;
- (void)handleAnimationNotification:(id)arg1;
- (id)initWithWebAdView:(id)arg1 messageSource:(id)arg2;

@end

