//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADAd, GADObserverCollection;

@interface GADAppEventMonitor : NSObject
{
    GADObserverCollection *_observers;
    GADAd *_ad;
}

- (void).cxx_destruct;
- (void)handleAppEventNotification:(id)arg1;
- (id)initWithAd:(id)arg1 messageSource:(id)arg2;

@end

