//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADJSContext;

@interface GADActiveViewContext : NSObject
{
    GADJSContext *_context;
}

+ (void)loadWithEventContext:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)updateActiveViewWithSignals:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setJSContext:(id)arg1;

@end

