//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface GADAdapterStatus : NSObject <NSCopying>
{
    NSString *_statusDescription;
    long long _state;
    double _latency;
}

@property(readonly, nonatomic) double latency; // @synthesize latency=_latency;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithState:(long long)arg1 latency:(double)arg2 description:(id)arg3;

@end

