//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADActiveViewReporter, GADObserverCollection, GADScheduler;

@interface GADActiveViewMonitor : NSObject
{
    GADObserverCollection *_observers;
    GADScheduler *_updateActiveViewStatusScheduler;
    GADActiveViewReporter *_activeViewReporter;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithAd:(id)arg1 viewMessageSource:(id)arg2 webAdView:(id)arg3 adFormat:(id)arg4 analyticsLoggingEnabled:(_Bool)arg5 activeViewConfiguration:(id)arg6;

@end

