//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADAd, GADObserverCollection;

@interface GADAppEventMonitor : NSObject
{
    GADObserverCollection *_observers;
    GADAd *_ad;
}

- (void).cxx_destruct;
- (void)handleAppEventNotification:(id)arg1;
- (id)initWithAd:(id)arg1 messageSource:(id)arg2;

@end

