//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADObserverCollection, UIView;

@interface GADAdVerificationMonitoredView : NSObject
{
    GADObserverCollection *_presenterDismissalObserverCollection;
    UIView *_monitoredView;
}

@property(nonatomic) __weak UIView *monitoredView; // @synthesize monitoredView=_monitoredView;
- (void).cxx_destruct;
- (void)addObserverForMonitoredViewDismissal:(id)arg1 dismissalBlock:(CDUnknownBlockType)arg2;
- (id)initWithMonitoredView:(id)arg1;

@end

