//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface GADActiveQueryIDManager : NSObject
{
    NSMutableArray *_queryIDs;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)removeQueryID:(id)arg1;
- (void)removeOneObjectFromMutableArray:(id)arg1;
- (void)addQueryID:(id)arg1;
- (id)init;

@end

