//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADActiveViewReporter, GADObserverCollection, GADScheduler;

@interface GADActiveViewMonitor : NSObject
{
    GADObserverCollection *_observers;
    GADScheduler *_updateActiveViewStatusScheduler;
    GADActiveViewReporter *_activeViewReporter;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithAd:(id)arg1 viewMessageSource:(id)arg2 webAdView:(id)arg3 adFormat:(id)arg4 analyticsLoggingEnabled:(_Bool)arg5 activeViewConfiguration:(id)arg6;

@end

