//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADCustomEventRequest, NSArray, NSString, UIViewController;
@protocol GADCustomEventNativeAdDelegate;

@protocol GADCustomEventNativeAd <NSObject>
@property(nonatomic) __weak id <GADCustomEventNativeAdDelegate> delegate;
- (_Bool)handlesUserImpressions;
- (_Bool)handlesUserClicks;
- (void)requestNativeAdWithParameter:(NSString *)arg1 request:(GADCustomEventRequest *)arg2 adTypes:(NSArray *)arg3 options:(NSArray *)arg4 rootViewController:(UIViewController *)arg5;
@end

