//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SFSafariViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class GADAd, GADEventContext, NSString, NSURL, UIAlertView, UIButton;
@protocol GADDebugOptionsViewControllerDelegate;

@interface GADDebugOptionsViewController : UIViewController <UIAlertViewDelegate, SFSafariViewControllerDelegate>
{
    GADAd *_ad;
    GADEventContext *_context;
    NSString *_adDebugDialogString;
    UIAlertView *_creativeInformationAlertView;
    UIAlertView *_debugOptionsAlertView;
    UIAlertView *_statusAlertView;
    NSURL *_debugDeviceLinkingURL;
    UIButton *_closeButton;
    _Bool _debugSignalStatusFetchInProgress;
    _Bool _inAppPreviewTokenFetchInProgress;
    NSString *_adUnitID;
    _Bool _shouldEnableInAppPreview;
    _Bool _shouldEnableDebugSignal;
    id <GADDebugOptionsViewControllerDelegate> _delegate;
}

+ (id)debugOptionsViewControllerWithAdUnitID:(id)arg1;
@property(nonatomic) __weak id <GADDebugOptionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)finishedDebugFlow;
- (void)showAlertViewWithTitle:(id)arg1;
- (void)showSystemErrorAlertView;
- (void)inAppPreviewSignalStatusReceivedResponse:(id)arg1 data:(id)arg2;
- (void)linkInAppPreview;
- (void)debugSignalStatusReceivedResponse:(id)arg1 data:(id)arg2;
- (void)linkDebugSignal;
- (void)createDeviceIdentifierAndlinkDevice;
- (void)linkDevice;
- (id)debugURLRequestForString:(id)arg1;
- (id)debugDeviceQueryParameters;
- (void)showFeatureNotEnabledAlertView;
- (void)creativeInfoAlertViewClickedButtonAtIndex:(long long)arg1;
- (void)debugOptionsAlertViewClickedButtonAtIndex:(long long)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showCreativeInformationAlertView;
- (void)showDebugOptionsAlertView;
- (void)viewDidLoad;
- (void)updateConfigurationFromSettings;
- (void)dealloc;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithAd:(id)arg1 adUnitID:(id)arg2 debugDialogString:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

