//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADObserverCollection, NSOperationQueue;

@interface GADEventConsoleLogger : NSObject
{
    NSOperationQueue *_operationQueue;
    GADObserverCollection *_settingsUpdateObservers;
    GADObserverCollection *_loggingObservers;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)logEvent:(id)arg1;
- (void)updateEnabled;
- (id)init;

@end

