//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADObserverCollection, GADScheduler, NSMutableArray, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface GADEventLogger : NSObject
{
    GADObserverCollection *_observers;
    _Atomic _Bool _enabled;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSMutableDictionary *_eventObserversMap;
    NSMutableArray *_enqueuedEvents;
    GADScheduler *_scheduler;
    double _flushBufferTimestamp;
    struct atomic_flag _didDropEvents;
    NSMutableDictionary *_requestEventsMap;
    _Bool _shouldBatchRequestEvents;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addEventToRequestMap:(id)arg1;
- (void)addEventsToQueue:(id)arg1;
- (void)handleNotificationName:(id)arg1 context:(id)arg2 userInfo:(id)arg3;
- (_Bool)flushEventsQueue;
- (void)updateScheduler;
- (void)updateEventObservers;
- (void)updateBatchEvents;
- (void)updateLoggingState;
- (void)startScheduler;
- (void)disableLogging;
- (void)enableLogging;
- (_Bool)isNotificationLogged:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
@property(readonly, nonatomic) _Bool enabled;
- (id)init;

@end

