//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADAdNetworkExtras-Protocol.h"

@class NSString;

@interface GADFBNetworkExtras : NSObject <GADAdNetworkExtras>
{
    long long _nativeAdFormat;
}

@property(nonatomic) long long nativeAdFormat; // @synthesize nativeAdFormat=_nativeAdFormat;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

