//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADAd, GADClickProtection, GADObserverCollection, GADWebAdView, NSMutableDictionary;

@interface GADInAppStoreMonitor : NSObject
{
    GADWebAdView *_webAdView;
    GADAd *_ad;
    GADClickProtection *_clickProtection;
    GADObserverCollection *_observers;
    NSMutableDictionary *_cachedStoreProductViewController;
}

- (void).cxx_destruct;
- (void)handleFetchInAppStoreAction:(id)arg1;
- (void)openInAppStoreWithProductID:(id)arg1 fallbackURL:(id)arg2 shouldWaitForFetch:(_Bool)arg3;
- (void)handleOpenInAppStoreAction:(id)arg1;
- (id)initWithAd:(id)arg1 webAdView:(id)arg2 messageSource:(id)arg3 clickProtection:(id)arg4;

@end

