//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADAdRendering-Protocol.h"

@class GADAdMediaContent, GADEventContext, GADInstreamMediaContent, GADInternalNativeAd, GADNativeAdAttribution, GADURLSession, GADWebViewController, NSArray, NSMutableDictionary, NSSet, NSString;
@protocol OS_dispatch_group;

@interface GADInlineSingleNativeAdRenderer : NSObject <GADAdRendering>
{
    GADURLSession *_session;
    struct NSDictionary *_adConfiguration;
    GADEventContext *_adContext;
    NSMutableDictionary *_assets;
    CDUnknownBlockType _renderCompletionHandler;
    _Bool _disableImageLoading;
    NSArray *_images;
    GADInternalNativeAd *_internalNativeAd;
    GADAdMediaContent *_mediaContent;
    GADInstreamMediaContent *_instreamContent;
    NSSet *_requiredAssets;
    GADNativeAdAttribution *_attribution;
    GADWebViewController *_adVerificationWebViewController;
    GADWebViewController *_mediaContentWebViewController;
    NSObject<OS_dispatch_group> *_assetLoadingGroup;
}

- (void).cxx_destruct;
- (void)loadImageArray:(id)arg1 loadedImages:(id)arg2;
- (void)loadSingleImage:(id)arg1 assetName:(id)arg2;
- (void)renderAttribution;
- (void)loadAdVerificationWebView;
- (void)renderInstreamMediaContent;
- (void)renderMediaContent;
- (void)renderImages;
- (void)renderCustomAssets;
- (void)renderMuteAdInfo;
- (void)renderSingleAssets;
- (void)renderWithServerTransaction:(id)arg1 adConfiguration:(struct NSDictionary *)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)isVideo;
- (void)invalidateAndCancel;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

