//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADObserverCollection, NSOperationQueue;

@interface GADIntermissionStateMonitor : NSObject
{
    GADObserverCollection *_observers;
    _Bool _idleTimerWasOriginallyDisabled;
    NSOperationQueue *_deactivationQueue;
    _Bool _applicationBackgroundedDueToAdAction;
    _Bool _applicationStateIntermissionControlled;
    id <GADPresenterSource> _presenterSource;
}

@property(nonatomic) __weak id <GADPresenterSource> presenterSource; // @synthesize presenterSource=_presenterSource;
- (void).cxx_destruct;
- (void)sceneWillEnterForeground:(id)arg1;
- (void)setDeactivationQueueSuspended:(_Bool)arg1;
- (void)checkWhetherIntermissionActivated;
- (void)checkWhetherIntermissionDeactivated;
- (_Bool)intermissionActive;
- (void)intermissionWillEnd;
- (void)intermissionDidBegin;
- (void)restoreApplicationState;
- (void)saveApplicationState;
- (id)init;

@end

