//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "JSExport-Protocol.h"

@class GADJSCoreConsole, GADJSCoreInterface, GADJSCoreLocalStorage, GADJSCoreNavigator, GADJSCorePinger, GADJSCoreTimers, NSString;

@protocol GADJSCoreEnvironmentProtocol <JSExport>
@property(readonly, nonatomic) GADJSCoreLocalStorage *localStorage;
@property(readonly, nonatomic) GADJSCorePinger *pinger;
@property(readonly, nonatomic) GADJSCoreTimers *timers;
@property(readonly, nonatomic) GADJSCoreConsole *console;
@property(readonly, nonatomic) GADJSCoreInterface *googleAdsJsInterface;
@property(readonly, nonatomic) GADJSCoreNavigator *navigator;
@property(readonly, nonatomic) NSString *sdkVersion;
@property(readonly, nonatomic) NSString *platform;
@property(readonly, nonatomic) NSString *environment;
@end

