//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADEventContextSource-Protocol.h"
#import "GADJavascriptEvaluating-Protocol.h"

@class GADEventContext, NSString;

@interface GADJSContext : NSObject <GADJavascriptEvaluating, GADEventContextSource>
{
    GADEventContext *_eventContext;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
@property(readonly, nonatomic) GADEventContext *context; // @synthesize context=_eventContext;
- (void).cxx_destruct;
- (void)asyncEvaluateFunction:(id)arg1 parameters:(id)arg2;
- (id)initWithEventContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

