//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADJSFunction.h"

@class JSValue;

@interface GADJSCoreJSFunction : GADJSFunction
{
    JSValue *_functionValue;
}

- (void).cxx_destruct;
- (void)callWithArguments:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithFunctionValue:(id)arg1;

@end

