//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADJSCoreNavigatorProtocol-Protocol.h"

@class NSString;

@interface GADJSCoreNavigator : NSObject <GADJSCoreNavigatorProtocol>
{
    NSString *_userAgent;
}

@property(readonly, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
- (void).cxx_destruct;
- (id)init;

@end

