//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GADKeyValueObserver : NSObject
{
    id _object;
    CDUnknownBlockType _block;
    NSString *_key;
    GADKeyValueObserver *_retainCycle;
}

- (void).cxx_destruct;
- (void)invalidateAndCancel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithObject:(id)arg1 key:(id)arg2 block:(CDUnknownBlockType)arg3;

@end

