//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADMediatedAdRenderer.h"

#import "GADAdPresenting.h"

@class GADInterstitialAd, GADMediatedIntermission, NSString;

@interface GADMediationInterstitialAdRenderer : GADMediatedAdRenderer <GADAdPresenting>
{
    GADInterstitialAd *_interstitialAd;
    // Error parsing type: {atomic_flag="_Value"AB}, name: _clickEventReceived
    CDUnknownBlockType _renderCompletionHandler;
    GADMediatedIntermission *_intermission;
    // Error parsing type: {atomic_flag="_Value"AB}, name: _adLoadCompleted
}

- (void).cxx_destruct;
- (void)adapterDidGetAdClick:(id)arg1;
- (void)adapterWillLeaveApplication:(id)arg1;
- (void)adapterDidDismissInterstitial:(id)arg1;
- (void)adapterWillDismissInterstitial:(id)arg1;
- (void)adapterWillPresentInterstitial:(id)arg1;
- (void)adapter:(id)arg1 didFailAd:(id)arg2;
- (void)adapterDidReceiveInterstitial:(id)arg1;
- (void)presentFromViewController:(id)arg1;
- (_Bool)canPresentFromViewController:(id)arg1;
- (void)renderWithServerTransaction:(id)arg1 adConfiguration:(struct NSDictionary *)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)viewControllerForPresentingModalView;
- (void)reportClick;
- (void)adapterCompletedLoadWithError:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

