//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GADMediatedUnifiedNativeAd.h"
#import "GADMediationAd.h"

@protocol GADMediationNativeAd <GADMediationAd, GADMediatedUnifiedNativeAd>

@optional
- (_Bool)handlesUserImpressions;
- (_Bool)handlesUserClicks;
@end

