//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADMediationAdEventDelegate-Protocol.h"

@class GADAdReward;

@protocol GADMediationRewardedAdEventDelegate <GADMediationAdEventDelegate>
- (void)didEndVideo;
- (void)didStartVideo;
- (void)didRewardUserWithReward:(GADAdReward *)arg1;
@end

