//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADInternalNativeAd, GADMediatedIntermission, GADObserverCollection, UIView;

@interface GADMediatedNativeAdMonitor : NSObject
{
    id _mediatedNativeAd;
    GADInternalNativeAd *_internalNativeAd;
    GADObserverCollection *_observers;
    struct atomic_flag _clickEventReceived;
    UIView *_trackedView;
    GADMediatedIntermission *_intermission;
}

- (void).cxx_destruct;
- (id)internalVideoController;
- (void)handleMediatedNativeAdDidEndVideoPlayback;
- (void)handleMediatedNativeAdDidPauseVideo;
- (void)handleMediatedNativeAdDidPlayVideo;
- (void)handleUntrackViewNotification:(id)arg1;
- (void)handleTrackViewNotification:(id)arg1;
- (void)handleWillLeaveApplicationEvent;
- (void)handleDidDismissScreenEvent;
- (void)handleWillDismissScreenEvent;
- (void)handleWillPresentScreenEvent;
- (void)handleThirdPartyClickEvent;
- (void)handleFirstPartyClickEvent:(id)arg1;
- (void)handleThirdParyImpressionEvent;
- (void)handleFirstPartyImpressionEvent;
- (void)dealloc;
- (id)initWithInternalNativeAd:(id)arg1 mediatedNativeAd:(id)arg2 adapterHandlesImpressions:(_Bool)arg3 adapterHandlesClicks:(_Bool)arg4;

@end

