//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADMediationAdConfiguration.h"

@class NSArray;

@interface GADMediationNativeAdConfiguration : GADMediationAdConfiguration
{
    NSArray *_options;
}

@property(readonly, nonatomic) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (id)initWithAdConfiguration:(struct NSDictionary *)arg1 targeting:(id)arg2 credentials:(id)arg3 extras:(id)arg4;
- (id)init;
- (id)initWithOptions:(id)arg1 adConfiguration:(struct NSDictionary *)arg2 targeting:(id)arg3 credentials:(id)arg4 extras:(id)arg5;

@end

