//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADMAdNetworkAdapter.h"
#import "VungleDelegate.h"

@class NSString;

@interface GADMAdapterVungleInterstitial : NSObject <VungleDelegate, GADMAdNetworkAdapter>
{
    _Bool waitingInit;
    NSString *desiredPlacement;
    id <GADMAdNetworkConnector> _connector;
}

+ (Class)networkExtrasClass;
+ (id)adapterVersion;
@property(nonatomic) __weak id <GADMAdNetworkConnector> connector; // @synthesize connector=_connector;
@property(readonly) _Bool waitingInit; // @synthesize waitingInit;
@property(readonly) NSString *desiredPlacement; // @synthesize desiredPlacement;
- (void).cxx_destruct;
- (void)didCloseAd:(_Bool)arg1 didDownload:(_Bool)arg2;
- (void)willCloseAd:(_Bool)arg1 didDownload:(_Bool)arg2;
- (void)willShowAd;
- (void)adAvailable;
- (void)initialized:(_Bool)arg1 error:(id)arg2;
- (void)presentInterstitialFromRootViewController:(id)arg1;
- (_Bool)isBannerAnimationOK:(long long)arg1;
- (void)stopBeingDelegate;
- (void)getInterstitial;
- (void)loadAd;
- (void)getBannerWithSize:(struct GADAdSize)arg1;
- (void)dealloc;
- (id)initWithGADMAdNetworkConnector:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

