//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIViewController;

@protocol GADMRewardBasedVideoAdNetworkAdapter <NSObject>
+ (Class)networkExtrasClass;
+ (NSString *)adapterVersion;
- (void)stopBeingDelegate;
- (void)presentRewardBasedVideoAdWithRootViewController:(UIViewController *)arg1;
- (void)requestRewardBasedVideoAd;
- (void)setUp;
- (id)initWithRewardBasedVideoAdNetworkConnector:(id <GADMRewardBasedVideoAdNetworkConnector>)arg1;

@optional
- (void)setUpWithUserID:(NSString *)arg1;
- (id)initWithGADMAdNetworkConnector:(id <GADMRewardBasedVideoAdNetworkConnector>)arg1;
- (id)initWithRewardBasedVideoAdNetworkConnector:(id <GADMRewardBasedVideoAdNetworkConnector>)arg1 credentials:(NSArray *)arg2;
@end

