//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADAVPlayerItemProvider-Protocol.h"

@class AVPlayerItem, NSString, NSURL;

@interface GADNetworkVideoPlayerItem : NSObject <GADAVPlayerItemProvider>
{
    AVPlayerItem *_playerItem;
    NSURL *_videoURL;
}

- (void).cxx_destruct;
- (id)videoURL;
- (id)playerItem;
- (id)initWithVideoURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

