//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADNetworkUtilizationStatistics, GADObserverCollection, NSObject<OS_dispatch_queue>;

@interface GADNetworkUtilizationMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADNetworkUtilizationStatistics *_aggregatedStatistics;
    GADNetworkUtilizationStatistics *_initialStatistics;
    GADObserverCollection *_observers;
}

- (void).cxx_destruct;
@property(readonly) long long wifiReceivedByteCount;
@property(readonly) long long wifiTransmittedByteCount;
@property(readonly) long long cellularReceivedByteCount;
@property(readonly) long long cellularTransmittedByteCount;
- (void)updateByteCounts;
- (void)stop;
- (void)start;
- (id)init;

@end

