//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface GADNativeTemplateView : UIView
{
    NSString *_templateTypeName;
}

@property(retain, nonatomic, getter=getTemplateTypeName) NSString *templateTypeName; // @synthesize templateTypeName=_templateTypeName;
- (void).cxx_destruct;

@end

