//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;

@interface GADNativeAdViewTracker : NSObject
{
    NSMapTable *_adViewToAdMap;
    NSMapTable *_adToAdViewMap;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)adViewForNativeAd:(id)arg1;
- (void)removeAdViewForNativeAd:(id)arg1;
- (void)registerAdView:(id)arg1 assetViewTracker:(id)arg2 forNativeAd:(id)arg3;
- (id)init;

@end

