//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GADWebAdViewDelegate.h"

@class GADAd, GADClickProtection, GADObserverCollection, NSMapTable, NSString;

@interface GADOpenActionMonitor : NSObject <GADWebAdViewDelegate>
{
    GADAd *_ad;
    GADObserverCollection *_observers;
    _Bool _analyticsLoggingEnabled;
    NSMapTable *_confirmationAlertURLs;
    GADClickProtection *_clickProtection;
}

- (void).cxx_destruct;
- (void)adView:(id)arg1 runJavaScriptTextInputPanelWithTitle:(id)arg2 defaultText:(id)arg3 prompt:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)adView:(id)arg1 runJavaScriptConfirmPanelWithTitle:(id)arg2 message:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)adView:(id)arg1 runJavaScriptAlertPanelWithTitle:(id)arg2 message:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handleMailAction:(id)arg1;
- (void)handleSMSAction:(id)arg1;
- (void)openSafariViewControllerToURL:(id)arg1;
- (void)handleOpenSafariAction:(id)arg1;
- (void)handleOpenBrowserAction:(id)arg1;
- (void)confirmClickToURL:(id)arg1 title:(id)arg2;
- (void)handleOpenApplicationAction:(id)arg1;
- (void)handleOpenApplicationWithURL:(id)arg1 navigationURL:(id)arg2 sourceURL:(id)arg3;
- (void)confirmURLNavigation:(id)arg1;
- (void)handleClickAction:(id)arg1;
- (id)initWithAd:(id)arg1 messageSource:(id)arg2 clickProtection:(id)arg3 analyticsLoggingEnabled:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

