//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADObserverCollection, GADResourceBuffer, GADVideoConfiguration, GADWebAdView, NSTimer, NSURL;
@protocol OS_dispatch_queue;

@interface GADPrecacheMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADWebAdView *_adView;
    id _messageSource;
    GADObserverCollection *_observers;
    GADObserverCollection *_resourceBufferObservers;
    GADResourceBuffer *_resourceBuffer;
    unsigned long long _byteThresholdToNotify;
    GADVideoConfiguration *_videoConfiguration;
    NSURL *_videoSourceURL;
    NSTimer *_resourceBufferNotifyUpdateTimer;
    long long _lastNotifiedBytes;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)notifyPrecacheEvent:(id)arg1;
- (void)notifyPrecacheCompletedWithError:(id)arg1;
- (void)notifyPrecacheUpdate;
- (void)stopResourceBufferUpdateCheckTimer;
- (void)handleResourceBufferNotification:(id)arg1;
- (void)startPrecachingWithRequest:(id)arg1 fileURL:(id)arg2;
- (void)abort;
- (void)handlePrecacheAction:(id)arg1;
@property(readonly) NSURL *videoSourceURL;
@property(readonly) GADResourceBuffer *resourceBuffer;
- (void)dealloc;
- (id)initWithWebAdView:(id)arg1 messageSource:(id)arg2;

@end

