//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADObserverCollection, NSDate, NSObject<OS_dispatch_queue>;

@interface GADRemoteConfigurationSource : NSObject
{
    GADObserverCollection *_observers;
    _Bool _isConfigurationUpdatePublisherInitiated;
    _Bool _adMobAppIDChanged;
    _Bool _refreshIsInProgress;
    _Bool _didRefreshSinceAppStart;
    NSDate *_lastConfigurationRefreshTimestamp;
    _Bool _remoteConfigRefreshedSinceAppStart;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)processRemoteConfigurationResult:(id)arg1 error:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)refreshWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool didRefreshSinceAppStart;
- (void)refreshIfNeeded;
- (void)refresh;
- (void)refreshFromPublisherRequest;
- (id)init;

@end

