//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADSignal-Protocol.h"
#import "GADSignalSource-Protocol.h"

@class GADAd, GADObserverCollection, NSMapTable, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface GADRequestStatisticsSignals : NSObject <GADSignal, GADSignalSource>
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    _Atomic long long _sequenceNumber;
    long long _previousRequestCount;
    NSMutableDictionary *_applicationMetrics;
    NSMutableDictionary *_requestMetricsBySequenceNumber;
    NSMapTable *_adMetricsByAdContext;
    NSMutableDictionary *_unfinalizedAdsBySequenceNumber;
    GADAd *_appExitingAd;
    GADObserverCollection *_observers;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)getSignalUpdateQueue:(id *)arg1 signalCreationBlock:(CDUnknownBlockType *)arg2;
- (void)addSignalEntriesToMutableDictionary:(id)arg1;
- (void)updateRequestTimeMetrics;
- (id)appStatistics;
- (id)adStatistics;
- (void)cleanUpMetricsSentByRequest:(id)arg1;
- (_Bool)hasFinalizedStatisticsForSequenceNumber:(id)arg1;
- (void)setValue:(id)arg1 forRequest:(id)arg2 signal:(id)arg3;
- (void)resetQualitySessionIfNeeded;
- (void)endClickEventsForContext:(id)arg1;
- (void)endClickEventForExitingAd;
- (void)recordClickForAd:(id)arg1;
- (id)knownAdContexts;
- (void)setAds:(id)arg1 forRequest:(id)arg2;
- (void)addServerRequest:(id)arg1;
- (long long)nextSequenceNumber;
- (void)addSynchronizedObserverForName:(id)arg1 fromInstanceOfClass:(Class)arg2 block:(CDUnknownBlockType)arg3;
- (void)observeAdEvents;
- (void)observeAppEvents;
- (void)observeRequests;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

