//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADMediationCredentials, GADRTBMediationSignalsConfiguration;

@interface GADRTBRequestParameters : NSObject
{
    GADRTBMediationSignalsConfiguration *_configuration;
    id <GADAdNetworkExtras> _extras;
    GADMediationCredentials *_credentials;
    struct GADAdSize _adSize;
}

@property(readonly, nonatomic) GADMediationCredentials *credentials; // @synthesize credentials=_credentials;
@property(readonly, nonatomic) struct GADAdSize adSize; // @synthesize adSize=_adSize;
@property(readonly, nonatomic) id <GADAdNetworkExtras> extras; // @synthesize extras=_extras;
@property(readonly, nonatomic) GADRTBMediationSignalsConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)initWithTargeting:(id)arg1 RTBAdapter:(id)arg2;

@end

