//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface GADRewardBasedVideoAdController : NSObject
{
    NSMutableDictionary *_connectors;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *connectors; // @synthesize connectors=_connectors;
- (void).cxx_destruct;
- (void)removeConnectorForAdapterName:(id)arg1;
- (void)createConnectorForAdapter:(id)arg1 withAdConfiguration:(struct NSDictionary *)arg2 renderer:(id)arg3;
- (id)init;

@end

