//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADMediationAdapter-Protocol.h"

@class GADRTBRequestParameters;

@protocol GADRTBAdapter <GADMediationAdapter>
- (void)collectSignalsForRequestParameters:(GADRTBRequestParameters *)arg1 completionHandler:(void (^)(NSString *, NSError *))arg2;
@end

