//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GADAdSource, GADInterstitialAd, GADObserverCollection, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface GADRewardBasedVideoAd : NSObject
{
    GADInterstitialAd *_rewardBasedVideoAd;
    GADAdSource *_adSource;
    _Bool _requestInProgress;
    GADObserverCollection *_intermissionObservers;
    GADObserverCollection *_rewardedAdObservers;
    NSString *_adUnitID;
    GADObserverCollection *_appSettingsObservers;
    _Bool _isAdPresenting;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSString *_adNetworkClassName;
    NSDictionary *_adMetadata;
    id <GADRewardBasedVideoAdDelegate> _delegate;
    NSString *_userIdentifier;
    NSString *_customRewardString;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *customRewardString; // @synthesize customRewardString=_customRewardString;
@property(copy, nonatomic) NSString *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
@property(nonatomic) __weak id <GADRewardBasedVideoAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stopObservingApplicationConfiguration;
- (void)setUpAdaptersFromApplicationSettings;
- (void)attachAppSettingsObservers;
- (void)attachRewardedEventsObservers;
- (void)attachLifecycleEventObservers;
- (void)setAdMetadata:(id)arg1;
@property(readonly, nonatomic) NSDictionary *adMetadata;
- (id)adSource;
- (void)setRewardBasedVideoAd:(id)arg1;
@property(readonly, nonatomic, getter=isReady) _Bool ready;
- (void)adPresentationDidFail;
- (void)setAdNetworkClassName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName;
- (void)presentFromRootViewController:(id)arg1;
- (void)adLoadCompletedWithError:(id)arg1;
- (void)adInvalidated;
- (void)loadWithTargeting:(id)arg1;
- (void)removeExistingAd;
- (void)loadRequest:(id)arg1 withAdUnitID:(id)arg2;
- (void)updateTargeting:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

