//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class GADViewControllerPresenter, NSString, SKStoreProductViewController;

@interface GADStoreKitProductOpener : NSObject <SKStoreProductViewControllerDelegate>
{
    SKStoreProductViewController *_weakStoreKitProductViewController;
    GADViewControllerPresenter *_presenter;
    _Bool _shouldDismissAfterPresentation;
    _Bool _isPresenting;
    _Bool _isPresented;
    _Bool _dismissed;
}

- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)dismiss;
- (void)openWithRootViewController:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)initWithStoreKitProductViewController:(id)arg1 context:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

