//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface GADSQLStorage : NSObject
{
    struct sqlite3 *_database;
    NSMutableDictionary *_values;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSObject<OS_dispatch_queue> *_writeQueue;
    NSMutableDictionary *_valuesToWrite;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)writeUpdatedValues;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)stringForKey:(id)arg1;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (_Bool)openDatabaseAtURL:(id)arg1;
- (void)loadDatabaseValues;
- (void)dealloc;
- (id)init;

@end

