//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol OS_dispatch_queue;

@interface GADWebViewControllerMap : NSObject
{
    NSMutableSet *_webViewControllers;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)webViewConfigurationForMainDocumentURL:(id)arg1 context:(id *)arg2;
- (void)removeWebViewController:(id)arg1;
- (void)addWebViewController:(id)arg1;
- (id)init;

@end

