//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GDTCORLifecycleProtocol-Protocol.h"
#import "GDTCORUploadPackageProtocol-Protocol.h"
#import "NSObject-Protocol.h"

@class GDTCORStoredEvent, GDTCORUploadPackage;

@protocol GDTCORPrioritizer <NSObject, GDTCORLifecycleProtocol, GDTCORUploadPackageProtocol>
- (GDTCORUploadPackage *)uploadPackageWithConditions:(long long)arg1;
- (void)prioritizeEvent:(GDTCORStoredEvent *)arg1;
@end

