//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTCORApplication;

@protocol GDTCORLifecycleProtocol <NSObject>

@optional
- (void)appWillForeground:(GDTCORApplication *)arg1;
- (void)appWillBackground:(GDTCORApplication *)arg1;
- (void)appWillTerminate:(GDTCORApplication *)arg1;
@end

