//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AWSIdentityProviderManager-Protocol.h"

@class NSString;

@interface GGAWSCustomAuthenticatedIdentityProviderManager : NSObject <AWSIdentityProviderManager>
{
}


// Remaining properties
@property(readonly, nonatomic) NSString *customRoleArn;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

