//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GKTurnBasedMatch, GKTurnBasedMatchmakerViewController, NSError;

@protocol GKTurnBasedMatchmakerViewControllerDelegate <NSObject>
- (void)turnBasedMatchmakerViewController:(GKTurnBasedMatchmakerViewController *)arg1 didFailWithError:(NSError *)arg2;
- (void)turnBasedMatchmakerViewControllerWasCancelled:(GKTurnBasedMatchmakerViewController *)arg1;

@optional
- (void)turnBasedMatchmakerViewController:(GKTurnBasedMatchmakerViewController *)arg1 playerQuitForMatch:(GKTurnBasedMatch *)arg2;
- (void)turnBasedMatchmakerViewController:(GKTurnBasedMatchmakerViewController *)arg1 didFindMatch:(GKTurnBasedMatch *)arg2;
@end

