//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GPBMessage.h"

@interface GPBDoubleValue : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double value; // @dynamic value;

@end

