//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLConnectionDataDelegate-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"

@class NSMutableData, NSString, NSURLConnection;
@protocol GSDKHttpRequestDelegate;

@interface GSDKHttpRequest : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    id <GSDKHttpRequestDelegate> _delegate;
    NSMutableData *_receiveData;
    NSURLConnection *_connection;
    struct __CFRunLoop *_rl;
}

@property(nonatomic) struct __CFRunLoop *rl; // @synthesize rl=_rl;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSMutableData *receiveData; // @synthesize receiveData=_receiveData;
@property(nonatomic) __weak id <GSDKHttpRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)dealloc;
- (void)requestLoginControl:(id)arg1 Env:(int)arg2;
- (id)requestControl:(id)arg1 Openid:(id)arg2 Acctype:(int)arg3 Zoneid:(id)arg4 Env:(int)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

