//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface GSDKWIFI : NSObject
{
    NSMutableDictionary *_devicesDictionary;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *devicesDictionary; // @synthesize devicesDictionary=_devicesDictionary;
- (void).cxx_destruct;
- (void)ping:(id)arg1;
- (int)wifiDeviceCount:(_Bool)arg1;
- (id)resultWIFI_noCollect;
- (id)resultWIFI;
- (void)dealloc;
- (id)init;

@end

