//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GSDKLoginPayDetect : NSObject
{
}

- (void)detectPayPort;
- (void)detectPort:(id)arg1 Port1:(id)arg2 Domain2:(id)arg3 Port2:(id)arg4 Domain3:(id)arg5 Port3:(id)arg6 Domain4:(id)arg7 Port4:(id)arg8 Domain5:(id)arg9 Port5:(id)arg10 Domain6:(id)arg11 Port6:(id)arg12;

@end

