//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GSDK_Route_Info : NSObject
{
    struct sockaddr m_addrs[8];
    struct rt_msghdr2 m_rtm;
    int m_len;
}

+ (id)getRoute:(struct rt_msghdr2 *)arg1;
+ (id)getRoutes;
- (id)formatIPV4Address:(struct in_addr)arg1;
- (id)getAddrStringByIndex:(int)arg1;
- (id)getGateway;
- (id)getNetmask;
- (id)getDestination;
- (void)setAddr:(struct sockaddr *)arg1 index:(int)arg2;
- (id)initWithRtm:(struct rt_msghdr2 *)arg1;

@end

