//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDKBatteryLevel : NSObject
{
    int _has_charged;
    int _start_battery;
}

+ (id)sharedInstance;
@property(nonatomic) int start_battery; // @synthesize start_battery=_start_battery;
@property(nonatomic) int has_charged; // @synthesize has_charged=_has_charged;
- (id)resultBattery_noCollect;
- (id)resultBattery;
- (void)startBattery;

@end

