//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDKLoginPayDetect : NSObject
{
}

- (void)detectPayPort;
- (void)detectPort:(id)arg1 Port1:(id)arg2 Domain2:(id)arg3 Port2:(id)arg4 Domain3:(id)arg5 Port3:(id)arg6 Domain4:(id)arg7 Port4:(id)arg8 Domain5:(id)arg9 Port5:(id)arg10 Domain6:(id)arg11 Port6:(id)arg12;

@end

