//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GSDKHttpRequestDelegate.h"

@class NSString;

@interface GSDKInitManager : NSObject <GSDKHttpRequestDelegate>
{
    _Bool _login_flag;
    _Bool _pay_flag;
    _Bool _domain_flag;
    int _gsdkAcctype;
    int _gsdkEnv;
    NSString *_gsdkOpenID;
    NSString *_gsdkAppID;
    NSString *_uuidString;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *uuidString; // @synthesize uuidString=_uuidString;
@property(nonatomic) _Bool domain_flag; // @synthesize domain_flag=_domain_flag;
@property(nonatomic) _Bool pay_flag; // @synthesize pay_flag=_pay_flag;
@property(nonatomic) _Bool login_flag; // @synthesize login_flag=_login_flag;
@property(nonatomic) int gsdkEnv; // @synthesize gsdkEnv=_gsdkEnv;
@property(retain, nonatomic) NSString *gsdkAppID; // @synthesize gsdkAppID=_gsdkAppID;
@property(retain, nonatomic) NSString *gsdkOpenID; // @synthesize gsdkOpenID=_gsdkOpenID;
@property(nonatomic) int gsdkAcctype; // @synthesize gsdkAcctype=_gsdkAcctype;
- (void).cxx_destruct;
- (void)GSDKSetUserName:(int)arg1 Openid:(id)arg2;
- (void)detectOperation:(id)arg1;
- (void)resolver:(id)arg1 getControlError:(id)arg2;
- (void)resolver:(id)arg1 didGetControlInfo:(id)arg2;
- (void)GSDKRequestLoginControl:(id)arg1 Env:(int)arg2;
- (void)GSDKInit:(id)arg1 Debug:(_Bool)arg2 Env:(int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

