//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HelpshiftFAQFilter, HelpshiftSupportMetaData, NSArray, NSDictionary, NSString;

@interface HelpshiftAPIConfigBuilder : NSObject
{
    _Bool _presentFullScreenOniPad;
    _Bool _enableFullPrivacy;
    _Bool _showConversationInfoScreen;
    _Bool _gotoConversationAfterContactUs;
    _Bool _requireEmail;
    _Bool _hideNameAndEmail;
    _Bool _showSearchOnNewConversation;
    _Bool _showConversationResolutionQuestion;
    _Bool _enableTypingIndicator;
    _Bool _isGotoConversationAfterContactUsSet;
    int _enableContactUs;
    NSArray *_customContactUsFlows;
    HelpshiftFAQFilter *_withTagsMatching;
    HelpshiftSupportMetaData *_customMetaData;
    NSDictionary *_customIssueFields;
    NSDictionary *_extraConfig;
    NSString *_conversationPrefillText;
}

@property(nonatomic) _Bool isGotoConversationAfterContactUsSet; // @synthesize isGotoConversationAfterContactUsSet=_isGotoConversationAfterContactUsSet;
@property(nonatomic) _Bool enableTypingIndicator; // @synthesize enableTypingIndicator=_enableTypingIndicator;
@property(nonatomic) _Bool showConversationResolutionQuestion; // @synthesize showConversationResolutionQuestion=_showConversationResolutionQuestion;
@property(nonatomic) _Bool showSearchOnNewConversation; // @synthesize showSearchOnNewConversation=_showSearchOnNewConversation;
@property(nonatomic) _Bool hideNameAndEmail; // @synthesize hideNameAndEmail=_hideNameAndEmail;
@property(nonatomic) _Bool requireEmail; // @synthesize requireEmail=_requireEmail;
@property(nonatomic) _Bool gotoConversationAfterContactUs; // @synthesize gotoConversationAfterContactUs=_gotoConversationAfterContactUs;
@property(retain, nonatomic) NSString *conversationPrefillText; // @synthesize conversationPrefillText=_conversationPrefillText;
@property(retain, nonatomic) NSDictionary *extraConfig; // @synthesize extraConfig=_extraConfig;
@property(retain, nonatomic) NSDictionary *customIssueFields; // @synthesize customIssueFields=_customIssueFields;
@property(retain, nonatomic) HelpshiftSupportMetaData *customMetaData; // @synthesize customMetaData=_customMetaData;
@property(retain, nonatomic) HelpshiftFAQFilter *withTagsMatching; // @synthesize withTagsMatching=_withTagsMatching;
@property(retain, nonatomic) NSArray *customContactUsFlows; // @synthesize customContactUsFlows=_customContactUsFlows;
@property(nonatomic) int enableContactUs; // @synthesize enableContactUs=_enableContactUs;
@property(nonatomic) _Bool showConversationInfoScreen; // @synthesize showConversationInfoScreen=_showConversationInfoScreen;
@property(nonatomic) _Bool enableFullPrivacy; // @synthesize enableFullPrivacy=_enableFullPrivacy;
@property(nonatomic) _Bool presentFullScreenOniPad; // @synthesize presentFullScreenOniPad=_presentFullScreenOniPad;
- (void).cxx_destruct;
- (id)build;
- (id)init;

@end

