//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface HelpshiftSupportMetaData : NSObject
{
    NSDictionary *_metaData;
    NSArray *_issueTags;
}

@property(retain, nonatomic) NSArray *issueTags; // @synthesize issueTags=_issueTags;
@property(retain, nonatomic) NSDictionary *metaData; // @synthesize metaData=_metaData;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)initWithMetaData:(id)arg1 andTags:(id)arg2;
- (id)initWithMetaData:(id)arg1;
- (id)init;

@end

