//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol HsAdapterObserver <NSObject>
- (void)adapterDataSourceUpdationFailed;
- (void)noChangeInadapterDataSource;
- (void)adapterDataSourceUpdated;
@end

