//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIAlertController.h>

@interface HsAlertView : UIAlertController
{
}

- (void)viewDidAppear:(_Bool)arg1;
- (void)show:(_Bool)arg1;
- (id)topViewController;

@end

