//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;
@protocol HsPlatform;

@protocol HsAnalyticsDao <NSObject>
- (void)purgeStoredAnalyticsDataForKey:(NSString *)arg1 withError:(id *)arg2;
- (NSDictionary *)unsyncedAnalyticsDataWithError:(id *)arg1;
- (void)storeUnsyncedAnalyticsData:(NSDictionary *)arg1 forKey:(NSString *)arg2 withError:(id *)arg3;
- (id)initWithPlatform:(id <HsPlatform>)arg1 withError:(id *)arg2;
@end

