//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsBaseTableViewCell.h"

@interface HSAttachmentImageTableViewCell : HsBaseTableViewCell
{
    id <HSAttachmentImageTableViewCellDelegate> _delegate;
}

@property __weak id <HSAttachmentImageTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reapplyTheming;
- (_Bool)isAccessibilityElement;
- (id)accessibilityElements;

@end

