//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HSBaseViewController.h"

@class HsBorderedImageView, HsThemedBarButtonItem, NSDictionary, NSString;
@protocol HsAttachmentPreviewDelegate;

@interface HsAttachmentPreviewController : HSBaseViewController
{
    HsThemedBarButtonItem *_doneBarButtonItem;
    HsBorderedImageView *_imageView;
    unsigned long long _source;
    NSDictionary *_mediaInfo;
    NSString *_currentProfileLocalId;
    id <HsAttachmentPreviewDelegate> _delegate;
}

@property __weak id <HsAttachmentPreviewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSString *currentProfileLocalId; // @synthesize currentProfileLocalId=_currentProfileLocalId;
@property(retain) NSDictionary *mediaInfo; // @synthesize mediaInfo=_mediaInfo;
@property unsigned long long source; // @synthesize source=_source;
- (void).cxx_destruct;
- (void)doneButtonTapped:(id)arg1;
- (void)reapplyTheming;
- (void)applyTheming;
- (void)setupUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

