//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface HSCategoryTagsFilter : NSObject
{
    short _hsOperator;
    NSArray *_tags;
}

@property(nonatomic) short hsOperator; // @synthesize hsOperator=_hsOperator;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
- (void).cxx_destruct;
- (id)initWithCategoryTagOptions:(id)arg1;

@end

