//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsConversationFooterViewState : NSObject
{
    unsigned long long _state;
}

@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void)setFooterState:(unsigned long long)arg1;
- (unsigned long long)footerState;
- (id)init;

@end

