//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsCoreViewUtils : NSObject
{
}

+ (struct CGSize)computeExpectedLabelSize:(id)arg1 forFont:(id)arg2 andWidth:(double)arg3;
+ (id)getTopViewController;

@end

