//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol HsConversationFooterViewDelegate <NSObject>
- (void)didTapStartNewConversation;
- (void)didSelectRatingWithValue:(long long)arg1;
- (void)didTapResolutionQuestionNoButton;
- (void)didTapResolutionQuestionYesButton;
@end

