//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HsConversationBrandingVisibilityManager : NSObject
{
    _Bool _keyboardVisible;
    _Bool _isLandscape;
    _Bool _shouldShowBranding;
    id <HsConversationBrandingVisibilityManagerDelegate> _delegate;
    long long _currentState;
}

@property(nonatomic) _Bool shouldShowBranding; // @synthesize shouldShowBranding=_shouldShowBranding;
@property(nonatomic) _Bool isLandscape; // @synthesize isLandscape=_isLandscape;
@property(nonatomic) _Bool keyboardVisible; // @synthesize keyboardVisible=_keyboardVisible;
@property(nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak id <HsConversationBrandingVisibilityManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keyboardWillHide;
- (void)keyboardWillShow;
- (void)orientationDidChange;
- (void)conversationBrandingStateDidChangeTo:(long long)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

