//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HSConstants : NSObject
{
}

+ (id)rootViewController;
+ (id)nilIfEmptyString:(id)arg1;
+ (id)errorWithErrorDomain:(id)arg1 errorCode:(unsigned long long)arg2 errorUserInfoDescription:(id)arg3 errorUserInfoReason:(id)arg4;
+ (const char *)queueNameWithSuffix:(id)arg1;
+ (const char *)queueNameForClass:(Class)arg1;

@end

