//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsBaseTableViewCell.h"

@class HsLabel;

@interface HsConversationRedactedTableViewCell : HsBaseTableViewCell
{
    HsLabel *_titleLabel;
}

+ (id)reuseIdentifier;
@property(nonatomic) __weak HsLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)reapplyTheming;
- (void)updateWithDM:(id)arg1;
- (void)applyTheme;
- (void)awakeFromNib;

@end

