//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HsDiskspaceDTO : NSObject
{
    NSString *_totalSpace;
    NSString *_freeSpace;
}

@property(readonly, nonatomic) NSString *freeSpace; // @synthesize freeSpace=_freeSpace;
@property(readonly, nonatomic) NSString *totalSpace; // @synthesize totalSpace=_totalSpace;
- (void).cxx_destruct;
- (id)initWithTotalSpace:(id)arg1 freeSpace:(id)arg2;

@end

