//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsBaseUIView.h"

@interface HsDividerView : HsBaseUIView
{
}

- (void)reapplyTheming;
- (void)applyTheme;
- (void)awakeFromNib;

@end

