//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HSPollerController, HSSDKDataDM, HSUserManagerDM, HsAnalyticsDM, HsConversationInboxManagerDM, HsFAQsDM, HsLocalizationDM, HsMetaDataDM, HsRetriableEventsDM, HsSDKConfigurationDM, HsThreader, HsWebsocketConfigDM;
@protocol HsPlatform;

@interface HsDomain : NSObject
{
    id <HsPlatform> _platform;
    HsSDKConfigurationDM *_sdkConfigDM;
    HsWebsocketConfigDM *_websocketConfigDM;
    HsMetaDataDM *_metaDataDM;
    HsAnalyticsDM *_analyticsDM;
    HsRetriableEventsDM *_retriableEventsDM;
    HsLocalizationDM *_localizationDM;
    HSUserManagerDM *_userManagerDM;
    HSSDKDataDM *_sdkDataDM;
    HsConversationInboxManagerDM *_conversationInboxManagerDM;
    HsFAQsDM *_faqsDM;
    HSPollerController *_conversationInboxPollerController;
    HsThreader *_serialThreaderPrivate;
    HsThreader *_concurrentThreaderPrivate;
}

@property(retain, nonatomic) HsThreader *concurrentThreaderPrivate; // @synthesize concurrentThreaderPrivate=_concurrentThreaderPrivate;
@property(retain, nonatomic) HsThreader *serialThreaderPrivate; // @synthesize serialThreaderPrivate=_serialThreaderPrivate;
- (void).cxx_destruct;
- (id)conversationPollerController;
- (id)faqsDM;
- (id)conversationInboxManagerDM;
- (id)fetchActiveConversation;
- (id)conversationInboxDM;
- (id)sdkDataDM;
- (id)userManagerDM;
- (id)localizationDM;
- (id)websocketConfigDM;
- (id)retriableEventsDM;
- (id)analyticsDM;
- (id)metaDataDM;
- (id)sdkConfigurationDM;
- (void)runSyncOnUI:(CDUnknownBlockType)arg1;
- (void)runOnUI:(CDUnknownBlockType)arg1;
- (void)runConcurrent:(CDUnknownBlockType)arg1 withDelay:(double)arg2;
- (void)runConcurrent:(CDUnknownBlockType)arg1;
- (void)runSerial:(CDUnknownBlockType)arg1;
@property(readonly) HsThreader *concurrentThreader;
@property(readonly) HsThreader *serialThreader;
- (id)initWithPlatform:(id)arg1;

@end

