//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface HsDynamicForm : NSObject
{
    NSString *_title;
    NSArray *_flows;
}

+ (id)dynamicFormWithTitle:(id)arg1 andFlowsData:(id)arg2;
+ (id)dynamicFormWithTitle:(id)arg1 andFlows:(id)arg2;
@property(retain, nonatomic) NSArray *flows; // @synthesize flows=_flows;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

