//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsExponentialBackoff : NSObject
{
    float _randomness;
    float _multiplier;
    double _baseInterval;
    double _maxInterval;
    long long _maxAttempts;
    double _currentBaseInterval;
    long long _attempts;
}

@property(nonatomic) long long attempts; // @synthesize attempts=_attempts;
@property(nonatomic) double currentBaseInterval; // @synthesize currentBaseInterval=_currentBaseInterval;
@property(nonatomic) long long maxAttempts; // @synthesize maxAttempts=_maxAttempts;
@property(nonatomic) float multiplier; // @synthesize multiplier=_multiplier;
@property(nonatomic) float randomness; // @synthesize randomness=_randomness;
@property(nonatomic) double maxInterval; // @synthesize maxInterval=_maxInterval;
@property(nonatomic) double baseInterval; // @synthesize baseInterval=_baseInterval;
- (double)nextInterval;
- (void)reset;
- (id)initWithBuilder:(id)arg1;

@end

