//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsFAQAnalyticsImplementer-Protocol.h"
#import "NSObject-Protocol.h"

@class HsFaqSearchResultsModel, NSString;

@protocol HsFaqSearchUIController <NSObject, HsFAQAnalyticsImplementer>
@property(readonly, nonatomic) HsFaqSearchResultsModel *model;
- (void)searchDidEnd;
- (void)searchDidStart;
- (void)filterContentForSearchText:(NSString *)arg1;
- (void)setSectionPublishId:(NSString *)arg1;
@end

