//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HsFaqDbObserver.h"
#import "HsFaqListUIController.h"

@class HSCategoryTagsFilter, HsFaqDbController, HsFaqListModel, NSString;

@interface HsFaqListUIControllerImpl : NSObject <HsFaqListUIController, HsFaqDbObserver>
{
    HsFaqDbController *_dbController;
    HsFaqListModel *_model;
    NSString *_sectionPublishId;
    HSCategoryTagsFilter *_tagsConfig;
}

@property(retain, nonatomic) HSCategoryTagsFilter *tagsConfig; // @synthesize tagsConfig=_tagsConfig;
@property(retain, nonatomic) NSString *sectionPublishId; // @synthesize sectionPublishId=_sectionPublishId;
@property(retain, nonatomic) HsFaqListModel *model; // @synthesize model=_model;
@property(retain, nonatomic) HsFaqDbController *dbController; // @synthesize dbController=_dbController;
- (void).cxx_destruct;
- (void)addFAQAnalyticEvent:(unsigned long long)arg1;
- (void)dataUpdationFailedForFaqPublishId:(id)arg1 error:(id)arg2;
- (void)noChangeInDataForFaqPublishId:(id)arg1;
- (void)dataUpdatedForFaqPublishId:(id)arg1;
- (void)loadFaqListItemsForSectionWithPublishId:(id)arg1 tagsFilter:(id)arg2 shouldFetchSections:(_Bool)arg3;
- (void)loadFromLocalDatabaseFaqListItemsForSectionWithPublishId:(id)arg1 tagsFilter:(id)arg2;
- (unsigned long long)sectionListItemsCountForTagsFilter:(id)arg1;
- (void)notifyModelObserverWithSelector:(SEL)arg1;
- (void)dealloc;
- (id)initWithDataBaseController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

