//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HsFAQAnalyticsImplementer.h"
#import "NSObject.h"

@class HSCategoryTagsFilter, HsFaqListModel, NSString;

@protocol HsFaqListUIController <NSObject, HsFAQAnalyticsImplementer>
@property(readonly, nonatomic) HsFaqListModel *model;
- (unsigned long long)sectionListItemsCountForTagsFilter:(HSCategoryTagsFilter *)arg1;
- (void)loadFaqListItemsForSectionWithPublishId:(NSString *)arg1 tagsFilter:(HSCategoryTagsFilter *)arg2 shouldFetchSections:(_Bool)arg3;
@end

