//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsFaqDbController, HsFaqSearchController, HsFaqSyncController;

@interface HsFaqControllerFactory : NSObject
{
    HsFaqDbController *_dbController;
    HsFaqSyncController *_faqSyncController;
    HsFaqSearchController *_faqSearchController;
}

+ (id)createFaqViewBaseController;
+ (id)createFaqSearchUIController;
+ (id)createSingleFaqController;
+ (id)createFaqListController;
+ (id)createSectionListController;
+ (id)sharedInstance;
@property(retain, nonatomic) HsFaqSearchController *faqSearchController; // @synthesize faqSearchController=_faqSearchController;
@property(retain, nonatomic) HsFaqSyncController *faqSyncController; // @synthesize faqSyncController=_faqSyncController;
@property(retain, nonatomic) HsFaqDbController *dbController; // @synthesize dbController=_dbController;
- (void).cxx_destruct;
- (id)init;

@end

