//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HsFaqResponseParser-Protocol.h"

@class NSString;

@interface HsFaqJsonResponseParser : NSObject <HsFaqResponseParser>
{
}

+ (id)faqSectionFromDictionary:(id)arg1 error:(id *)arg2;
+ (id)faqFromDictionary:(id)arg1 error:(id *)arg2;
+ (id)faqListItemFromDictionary:(id)arg1 error:(id *)arg2;
+ (id)sectionListItemFromDictionary:(id)arg1 error:(id *)arg2;
+ (id)validateFaqListItemDictionary:(id)arg1;
+ (id)validateSectionListItemDictionary:(id)arg1;
+ (id)validateFaqSectionDictionary:(id)arg1;
+ (id)validateFaqDictionary:(id)arg1;
+ (id)errorObjectWithFailureReason:(id)arg1 description:(id)arg2 errorCode:(long long)arg3;
- (void)parseSectionsListResponse:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)parseSectionsListResponse:(id)arg1 error:(id *)arg2;
- (id)parseFaqResponse:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

