//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HsRequest, HsResponse;

@protocol HsHTTPTransport <NSObject>
- (HsResponse *)makeRequest:(HsRequest *)arg1 withError:(id *)arg2;
@end

