//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface HsInput : NSObject
{
    _Bool _required;
    NSString *_botInfo;
    NSString *_inputLabel;
    NSString *_skipLabel;
}

@property(retain) NSString *skipLabel; // @synthesize skipLabel=_skipLabel;
@property(retain) NSString *inputLabel; // @synthesize inputLabel=_inputLabel;
@property _Bool required; // @synthesize required=_required;
@property(retain) NSString *botInfo; // @synthesize botInfo=_botInfo;
- (void).cxx_destruct;
- (id)initWithBotInfo:(id)arg1 required:(_Bool)arg2 inputLabel:(id)arg3 skipLabel:(id)arg4;

@end

