//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HsSdkInfoModel;

@interface HsInfoModelFactory : NSObject
{
    HsSdkInfoModel *_sdkInfoModel;
}

+ (id)sharedInstance;
@property(retain, nonatomic) HsSdkInfoModel *sdkInfoModel; // @synthesize sdkInfoModel=_sdkInfoModel;
- (void).cxx_destruct;

@end

