//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HsAnalyticsDao-Protocol.h"

@class HsIOSKVStroreProvider, NSString;

@interface HsIOSAnalyticsDAO : NSObject <HsAnalyticsDao>
{
    HsIOSKVStroreProvider *_storeProvider;
}

- (void).cxx_destruct;
- (id)unsyncedAnalyticsDataWithError:(id *)arg1;
- (void)purgeStoredAnalyticsDataForKey:(id)arg1 withError:(id *)arg2;
- (void)storeUnsyncedAnalyticsData:(id)arg1 forKey:(id)arg2 withError:(id *)arg3;
- (id)initWithPlatform:(id)arg1 withError:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

