//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDictionary, NSString;

@protocol HsJsonifier
- (NSString *)jsonStringFromDictionary:(NSDictionary *)arg1 withError:(id *)arg2;
- (NSString *)jsonStringFromArray:(NSArray *)arg1 withError:(id *)arg2;
@end

