//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface HsLabel : UILabel
{
    long long _labelType;
}

@property(nonatomic) long long labelType; // @synthesize labelType=_labelType;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)setFontWithSize:(double)arg1;
- (void)setCommonSystemMessageLabelStyleAndTheme;
- (void)setCsatRatingLabelStyleAndTheme;
- (void)setSystemMessageLabelItalicStyleAndTheme;
- (void)setSystemMessageLabelStyleAndTheme;
- (void)setTimeStampLabelStyleAndTheme;
- (void)setBotsPillHeaderLabelStyleAndTheme;
- (void)setBotsPillLabelStyleAndTheme;
- (void)setBotsFAQTitleLabelStyleAndTheme;
- (void)setConversationNWErrorLabelStyleAndTheme;
- (void)setConversationValidationLabelStyleAndTheme;
- (void)setConversationReplyTypeTitleLabelStyleAndTheme;
- (void)setImageAttachmentSizeLabelStyleAndTheme;
- (void)setDefaultStyleAndTheme;
- (void)applyStyleAndTheme;

@end

