//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HSUserSetupStateListener-Protocol.h"

@class HSReachability, NSString;
@protocol HSLoadingRenderer;

@interface HSLoadingViewModel : NSObject <HSUserSetupStateListener>
{
    id <HSLoadingRenderer> _renderer;
    HSReachability *_reachability;
}

@property(retain, nonatomic) HSReachability *reachability; // @synthesize reachability=_reachability;
@property(nonatomic) __weak id <HSLoadingRenderer> renderer; // @synthesize renderer=_renderer;
- (void).cxx_destruct;
- (void)onNetworkUnavailable;
- (void)onNetworkAvailable;
- (void)setUpRechability;
- (void)handleNetworkChange:(id)arg1;
- (void)userSetupStateChangedFrom:(unsigned long long)arg1 to:(unsigned long long)arg2 forUser:(id)arg3;
- (void)handleAuthenticationFailure:(id)arg1;
- (void)setup;
- (void)dealloc;
- (id)initWithRenderer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

