//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HSLocalization : NSObject
{
}

+ (_Bool)setLanguage:(id)arg1;
+ (id)getDeviceLanguageCode;
+ (_Bool)isLanguageRTL:(id)arg1;
+ (id)languageForString:(id)arg1;
+ (_Bool)isDeviceLanguageRTL;
+ (id)getLocalizedString:(id)arg1;
+ (id)getLocalizedString:(id)arg1 alter:(id)arg2;
+ (id)getLanguage;
+ (_Bool)initializeWithLanguage:(id)arg1;

@end

