//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HSConversationManager, HsDomain;
@protocol HsConversationDAO, HsPlatform;

@interface HsLocalConversationLoader : NSObject
{
    _Bool _hasOlderMessages;
    _Bool _sameConversationLoadedInLastLoad;
    id <HsPlatform> _platform;
    HsDomain *_domain;
    id <HsConversationDAO> _conversationDao;
    HSConversationManager *_conversationManager;
}

@property(retain, nonatomic) HSConversationManager *conversationManager; // @synthesize conversationManager=_conversationManager;
@property(retain) id <HsConversationDAO> conversationDao; // @synthesize conversationDao=_conversationDao;
@property(retain) HsDomain *domain; // @synthesize domain=_domain;
@property(retain) id <HsPlatform> platform; // @synthesize platform=_platform;
@property _Bool sameConversationLoadedInLastLoad; // @synthesize sameConversationLoadedInLastLoad=_sameConversationLoadedInLastLoad;
@property _Bool hasOlderMessages; // @synthesize hasOlderMessages=_hasOlderMessages;
- (void).cxx_destruct;
- (id)lastOpenConversationFromConversations:(id)arg1;
- (id)filterOpenConversationsFromConversations:(id)arg1;
- (id)filterRejectedEmptyPreconversationsFromConversations:(id)arg1 withError:(id *)arg2;
- (id)filterFullPrivacyEnabledConversationsFromConversations:(id)arg1;
- (id)filterMessagesFromList:(id)arg1 forConversationId:(id)arg2;
- (id)conversationsBeforeCursor:(id)arg1 withMessagePageSize:(unsigned long long)arg2 forUser:(id)arg3 withError:(id *)arg4;
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 conversationManager:(id)arg3 withError:(id *)arg4;

@end

