//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsLogExtrasModelProvider : NSObject
{
}

+ (id)fromKey:(id)arg1 DictionaryValue:(id)arg2;
+ (id)fromKey:(id)arg1 StringValue:(id)arg2;

@end

