//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HsRequestData, HsResponse;

@protocol HsNetwork <NSObject>
- (HsResponse *)makeRequest:(HsRequestData *)arg1 withError:(id *)arg2;
@end

