//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSSet, NSString;

@protocol HsNetworkRequestDAO <NSObject>
- (void)clearSuccessfulRequestIds;
- (NSSet *)getAllSuccessfulRequestIds;
- (void)storeSuccessfulRequestId:(NSString *)arg1;
- (NSDictionary *)getPendingRequestIdDictionaryForRoute:(NSString *)arg1;
- (NSString *)getPendingRequestIdForRoute:(NSString *)arg1 withMappingKey:(NSString *)arg2;
- (void)deletePendingRequestIdForRoute:(NSString *)arg1 withMappingKey:(NSString *)arg2;
- (void)storePendingRequestId:(NSString *)arg1 forRoute:(NSString *)arg2 withMappingKey:(NSString *)arg3;
- (void)removeEtagsForRoutesWithPrefix:(NSString *)arg1;
- (void)removeEtagForRoute:(NSString *)arg1;
- (NSString *)etagForRoute:(NSString *)arg1;
- (void)storeEtag:(NSString *)arg1 forRoute:(NSString *)arg2;
- (double)serverTimeDelta;
- (void)storeServerTimeDelta:(double)arg1;
@end

