//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class HsConversationMerger, HsDomain;
@protocol HsPlatform;

@interface HsNetworkConversationLoader : NSObject
{
    id <HsPlatform> _platform;
    HsDomain *_domain;
    HsConversationMerger *_merger;
}

@property(retain) HsConversationMerger *merger; // @synthesize merger=_merger;
@property(retain) HsDomain *domain; // @synthesize domain=_domain;
@property(retain) id <HsPlatform> platform; // @synthesize platform=_platform;
- (void).cxx_destruct;
- (id)createConversationNetwork;
- (_Bool)hasOlderMessagesForUser:(id)arg1;
- (void)conversationsBeforeCursor:(id)arg1 forUser:(id)arg2 withError:(id *)arg3;
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 merger:(id)arg3;

@end

