//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsNetworkRequestDataUtil : NSObject
{
}

+ (id)addUserInfoToApiData:(id)arg1 did:(id)arg2 uid:(id)arg3 email:(id)arg4 authToken:(id)arg5;
+ (id)addUserInfoToApiData:(id)arg1 withClearedUser:(id)arg2;
+ (id)addUserInfoToApidData:(id)arg1 withUserDM:(id)arg2;

@end

