//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface HsOption : NSObject
{
    NSString *_title;
    NSString *_dataString;
}

@property(retain, nonatomic) NSString *dataString; // @synthesize dataString=_dataString;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 dataString:(id)arg2;

@end

