//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;

@protocol HSOptionFilter <NSObject>
- (NSArray *)filterOptions:(NSArray *)arg1 forTokens:(NSArray *)arg2;
@end

