//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsProfileFormViewState : NSObject
{
    _Bool _isVisible;
}

@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;

@end

