//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsPostNetwork.h"

@interface HsPutNetwork : HsPostNetwork
{
}

- (id)makeRequestObject:(id)arg1;
- (id)initWithRoute:(id)arg1 domain:(id)arg2 platform:(id)arg3;

@end

