//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HsPullUpControllerBehaviour-Protocol.h"

@class NSString;

@interface HsPullUpControllerDefaultBehaviour : NSObject <HsPullUpControllerBehaviour>
{
}

- (double)getDampingWith:(struct CGVector)arg1;
- (id)timingCurveWith:(struct CGVector)arg1;
- (id)interactionAnimator:(id)arg1 to:(long long)arg2 with:(struct CGVector)arg3;
- (id)removalInteractionAnimator:(id)arg1 with:(struct CGVector)arg2;
@property(readonly, nonatomic) double removalProgress;
@property(readonly, nonatomic) double removalVelocity;
- (id)moveAnimator:(id)arg1 fromPosition:(long long)arg2 toPosition:(long long)arg3;
- (id)removeAnimator:(id)arg1 fromPosition:(long long)arg2;
- (id)addAnimator:(id)arg1 toPosition:(long long)arg2;
- (double)redirectionalProgress:(id)arg1 fromPosition:(long long)arg2 toPosition:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

