//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HSJsonData, NSData, NSDictionary;

@interface HsResponse : NSObject
{
    int _status;
    NSData *_responseData;
    NSDictionary *_headers;
    HSJsonData *_jsonData;
}

@property(retain, nonatomic) HSJsonData *jsonData; // @synthesize jsonData=_jsonData;
@property(readonly, nonatomic) NSDictionary *headers; // @synthesize headers=_headers;
@property(readonly, nonatomic) NSData *responseData; // @synthesize responseData=_responseData;
@property(readonly, nonatomic) int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)initWithStatus:(int)arg1 responseData:(id)arg2 headers:(id)arg3;

@end

