//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface HsRequestData : NSObject
{
    NSDictionary *_body;
    NSDictionary *_customHeaders;
    NSString *_requestID;
}

@property(retain, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
@property(retain, nonatomic) NSDictionary *customHeaders; // @synthesize customHeaders=_customHeaders;
@property(retain, nonatomic) NSDictionary *body; // @synthesize body=_body;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1 customHeaders:(id)arg2;
- (id)initWithData:(id)arg1;

@end

