//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HSUserDM, HsDomain;

@interface HSRedactionManager : NSObject
{
    id <HSRedactionListener> _listener;
    id <HSRedactionDAO> _redactionDao;
    HSUserDM *_user;
    id <HsPlatform> _platform;
    HsDomain *_domain;
}

@property(retain, nonatomic) HsDomain *domain; // @synthesize domain=_domain;
@property(retain, nonatomic) id <HsPlatform> platform; // @synthesize platform=_platform;
@property(retain, nonatomic) HSUserDM *user; // @synthesize user=_user;
@property(retain, nonatomic) id <HSRedactionDAO> redactionDao; // @synthesize redactionDao=_redactionDao;
@property(nonatomic) __weak id <HSRedactionListener> listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (void)updateRedactionStateFrom:(unsigned long long)arg1 to:(unsigned long long)arg2 withError:(id)arg3;
- (void)setAppropriateInitialState;
- (void)executeRedaction;
- (unsigned long long)redactionState;
- (id)initWithPlatform:(id)arg1 domain:(id)arg2 user:(id)arg3 listener:(id)arg4;

@end

