//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;
@protocol HsSearchTokenDto;

@protocol HsSearchTokenDao <NSObject>
- (void)clearAllData;
- (id <HsSearchTokenDto>)resultForQuery:(NSString *)arg1;
- (void)save:(NSArray *)arg1;
@end

