//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "HsModelObserver-Protocol.h"
#import "HsWebViewAdapter-Protocol.h"

@class NSString;
@protocol HsAdapterObserver, HsSingleFaqDataSource;

@interface HsSingleFaqAdapter : NSObject <HsModelObserver, HsWebViewAdapter>
{
    _Bool highlightSearchResults;
    id <HsSingleFaqDataSource> _dataSource;
    id <HsAdapterObserver> _observer;
    NSString *_processedFAQBody;
}

@property(retain, nonatomic) NSString *processedFAQBody; // @synthesize processedFAQBody=_processedFAQBody;
@property(nonatomic) __weak id <HsAdapterObserver> observer; // @synthesize observer=_observer;
@property(retain, nonatomic) id <HsSingleFaqDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool highlightSearchResults; // @synthesize highlightSearchResults;
- (void).cxx_destruct;
- (void)modelUpdationFailed;
- (void)noChangeInModel;
- (void)modelUpdated;
- (id)faqBodyStringWithHighlightedText:(id)arg1 searchTerms:(id)arg2;
- (id)titleTextAsHtml;
- (id)cssStringWithContentBackgroundColor:(id)arg1 isRTL:(_Bool)arg2 globalFontName:(id)arg3 globalFontFileName:(id)arg4 boldFontName:(id)arg5 boldFontFileName:(id)arg6;
- (id)fontFaceCSSElementWithFontName:(id)arg1 fontFileName:(id)arg2;
- (id)bodyBackgroundColour;
- (id)cssFontStringForFontWithName:(id)arg1;
- (id)bodyTextColor;
- (short)faqIsHelpfulStatus;
- (void)clearCachedContent;
- (id)formattedHtmlString;
- (void)initializeWebviewContent;
- (id)initWithDataSource:(id)arg1 observer:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

