//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsSRSecurityPolicy : NSObject
{
    _Bool _certificateChainValidationEnabled;
}

+ (id)pinnningPolicyWithCertificates:(id)arg1;
+ (id)defaultPolicy;
@property(readonly, nonatomic) _Bool certificateChainValidationEnabled; // @synthesize certificateChainValidationEnabled=_certificateChainValidationEnabled;
- (_Bool)evaluateServerTrust:(struct __SecTrust *)arg1 forDomain:(id)arg2;
- (void)updateSecurityOptionsInStream:(id)arg1;
- (id)init;
- (id)initWithCertificateChainValidationEnabled:(_Bool)arg1;

@end

