//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HSSupportDelegateHandler : NSObject
{
}

+ (id)supportedFileFormats;
+ (const char *)unityMessageHandler;
+ (void)notifyDidCreateDynamicForm:(id)arg1;
+ (void)notifyDidCheckIfConversationActive:(_Bool)arg1;
+ (void)conversationEnded;
+ (id)configForFAQViaSearch;
+ (void)handleAuthenticationFailedForUser:(id)arg1 withError:(id)arg2;
+ (_Bool)handleDisplayAttachmentFileAtLocation:(id)arg1 onViewController:(id)arg2;
+ (void)handleUserCompletedCustomerSatisfactionSurvey:(long long)arg1 withFeedback:(id)arg2;
+ (void)handleUserRepliedToConversationWithMessage:(id)arg1;
+ (void)handleNewConversationStartedWithMessage:(id)arg1;
+ (void)handleDidReceiveInAppNotificationWithMessageCount:(long long)arg1;
+ (void)handleHelpshiftSessionHasEnded;
+ (void)handleHelpshiftSessionHasBegun;
+ (void)handleDidReceiveUnreadMessagesCount:(long long)arg1;
+ (void)handleDidReceiveNotificationCount:(long long)arg1;

@end

