//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface HsSyncListener : NSObject
{
    NSString *dataType;
}

- (void).cxx_destruct;
- (id)getDependentDataTypes;
- (_Bool)isFullSyncEnabled;
- (void)fullSync;
- (void)sync;
- (id)getDataType;
- (id)initWithDataType:(id)arg1;

@end

