//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface HsTableView : UITableView
{
}

+ (double)heightForText:(id)arg1 andLabelWidth:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (void)awakeFromNib;

@end

