//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsMessageTableViewCell.h"

#import "HsPillTagsLabelDelegate-Protocol.h"

@class HSAutoAdjustLabel, HsBorderedButton, HsPillTagsLabel, NSLayoutConstraint, NSString, UIView;

@interface HsTagPillSelectTableViewCell : HsMessageTableViewCell <HsPillTagsLabelDelegate>
{
    _Bool _skippable;
    _Bool _didSkip;
    HSAutoAdjustLabel *_titleLabel;
    NSLayoutConstraint *_titleCOntainerHeightConstrain;
    HsPillTagsLabel *_tagLabel;
    UIView *_skipContainerView;
    HsBorderedButton *_skipButton;
    NSLayoutConstraint *_skipContainerHeightConstrain;
}

@property(nonatomic) _Bool didSkip; // @synthesize didSkip=_didSkip;
@property(retain, nonatomic) NSLayoutConstraint *skipContainerHeightConstrain; // @synthesize skipContainerHeightConstrain=_skipContainerHeightConstrain;
@property(nonatomic) _Bool skippable; // @synthesize skippable=_skippable;
@property(nonatomic) __weak HsBorderedButton *skipButton; // @synthesize skipButton=_skipButton;
@property(nonatomic) __weak UIView *skipContainerView; // @synthesize skipContainerView=_skipContainerView;
@property(nonatomic) __weak HsPillTagsLabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) NSLayoutConstraint *titleCOntainerHeightConstrain; // @synthesize titleCOntainerHeightConstrain=_titleCOntainerHeightConstrain;
@property(nonatomic) __weak HSAutoAdjustLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)applyTheming;
- (void)didTapItemAtIndex:(long long)arg1;
- (void)skipButtonTapped:(id)arg1;
- (void)initialiseViewsDefaults;
- (void)prepareForReuse;
- (void)updateWithDM:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

