//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface HsThreader : NSObject
{
    NSObject<OS_dispatch_queue> *_workerQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
- (void).cxx_destruct;
- (void)logException:(id)arg1;
- (CDUnknownBlockType)thread:(CDUnknownBlockType)arg1 withDelay:(double)arg2;
- (CDUnknownBlockType)thread:(CDUnknownBlockType)arg1;
- (id)initWithQueue:(id)arg1;

@end

