//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface HsThemeableButton : UIButton
{
    UIColor *_enabledStateTintColor;
}

@property(retain, nonatomic) UIColor *enabledStateTintColor; // @synthesize enabledStateTintColor=_enabledStateTintColor;
- (void).cxx_destruct;
- (void)setEnabled:(_Bool)arg1;
- (void)setTintColor:(id)arg1;
- (void)awakeFromNib;

@end

