//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HSTokeniser : NSObject
{
}

+ (id)splitWords:(id)arg1 onMinimumLength:(unsigned long long)arg2 for:(long long)arg3;
+ (id)splitWords:(id)arg1;

@end

