//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HsAgentMessageDM.h"

@class NSDictionary, NSString;

@interface HsUnsupportedAdminMessageWithInputDM : HsAgentMessageDM
{
    NSString *_metaString;
    NSString *_type;
    NSString *_botInfoString;
    NSDictionary *_input;
}

@property(retain) NSDictionary *input; // @synthesize input=_input;
@property(retain) NSString *botInfoString; // @synthesize botInfoString=_botInfoString;
@property(retain) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isUISupported;
- (void)merge:(id)arg1;
- (id)initWithBody:(id)arg1 createdAt:(id)arg2 authorName:(id)arg3 type:(id)arg4 botInfo:(id)arg5 input:(id)arg6 metaString:(id)arg7;

@end

