//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HSUserDM, NSArray, NSNumber, NSString;

@protocol HSUserDAO <NSObject>
- (_Bool)deleteUser:(NSNumber *)arg1;
- (_Bool)updateName:(NSString *)arg1 email:(NSString *)arg2 forUserLocalId:(NSNumber *)arg3;
- (_Bool)updateSyncState:(unsigned long long)arg1 forUserLocalId:(NSNumber *)arg2;
- (_Bool)updateIssueExists:(_Bool)arg1 forUserLocalId:(NSNumber *)arg2;
- (_Bool)updateName:(NSString *)arg1 forUserLocalId:(NSNumber *)arg2;
- (_Bool)updateAuthToken:(NSString *)arg1 forUserLocalId:(NSNumber *)arg2;
- (_Bool)updatePushTokenSyncStatus:(_Bool)arg1 forUserLocalId:(NSNumber *)arg2;
- (_Bool)activateUser:(NSNumber *)arg1;
- (HSUserDM *)anonymousUser;
- (HSUserDM *)activeUser;
- (HSUserDM *)fetchUserByIdentifier:(NSString *)arg1 email:(NSString *)arg2;
- (HSUserDM *)fetchUser:(NSNumber *)arg1;
- (NSArray *)fetchUsers;
- (HSUserDM *)createUser:(HSUserDM *)arg1;
@end

