//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HsUserNotificationUtil : NSObject
{
}

+ (void)scheduleLocalNotificationWithTitle:(id)arg1 body:(id)arg2 userInfo:(id)arg3 category:(id)arg4 delay:(double)arg5;
+ (unsigned long long)notificationRegistrationType;

@end

