//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HSUserDBResultConvertor : NSObject
{
}

+ (id)filterUsers:(id)arg1 byIdentifier:(id)arg2 email:(id)arg3;
+ (id)usersFromData:(id)arg1;

@end

