//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HSClearedUserDAO.h"
#import "HSUserDAO.h"
#import "HSUserMetaDAO.h"
#import "HSUserPersistentDAO.h"

@protocol HSUserManagerDAO <HSUserPersistentDAO, HSUserDAO, HSUserMetaDAO, HSClearedUserDAO>
- (id)initWithPlatform:(id <HsPlatform>)arg1;
@end

