//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HSUserDBResultConvertor : NSObject
{
}

+ (id)filterUsers:(id)arg1 byIdentifier:(id)arg2 email:(id)arg3;
+ (id)usersFromData:(id)arg1;

@end

