//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IFS_FILE : NSObject
{
    NSString *_url;
    NSString *_fileName;
    long long _fileSize;
}

@property long long fileSize; // @synthesize fileSize=_fileSize;
@property(retain) NSString *fileName; // @synthesize fileName=_fileName;
@property(retain) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

