//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURL, UIApplication;

@interface IMSDKApplicationDelegate : NSObject
{
    UIApplication *_application;
    NSDictionary *_launchOptions;
    NSString *_gameSecret;
    CDUnknownBlockType _urlLaunchHandle;
    NSDictionary *_launchData;
    NSURL *_launchURL;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(retain, nonatomic) NSDictionary *launchData; // @synthesize launchData=_launchData;
@property(readonly, copy, nonatomic) CDUnknownBlockType urlLaunchHandle; // @synthesize urlLaunchHandle=_urlLaunchHandle;
@property(retain, nonatomic) NSString *gameSecret; // @synthesize gameSecret=_gameSecret;
@property(retain, nonatomic) NSDictionary *launchOptions; // @synthesize launchOptions=_launchOptions;
@property(retain, nonatomic) UIApplication *application; // @synthesize application=_application;
- (void).cxx_destruct;
- (void)setupURLHandleManager:(id)arg1;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)resetHandleResult;
- (void)setUrlLaunchHandle:(CDUnknownBlockType)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 withGameSecret:(id)arg3;
- (id)init;
- (id)initSingleton;

@end

