//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMSDKUrlDefine : NSObject
{
}

+ (id)getDocsLogUrl;
+ (id)getAccountRecoveryCheck;
+ (id)getAccountRecoveryCode;
+ (id)getAccountAllAreaCode;
+ (id)getAccountSendCodeUrl;
+ (id)getAccountModPasswdUrl;
+ (id)getAccountLogoutUrl;
+ (id)getAccountLoginUrl;
+ (id)getAccountRegisterBindUrl;
+ (id)getAccountRegisterUrl;
+ (id)getBaseUrl;
+ (id)getLocalLogUrl;
+ (id)getAuthMigrateUrl;
+ (id)getAuthMigrateInfoUrl;
+ (id)getAuthMigrateCodeUrl;
+ (id)getAuthDeleteAllAccountUrl;
+ (id)getAuthDeleteDeviceAccountUrl;
+ (id)getAuthDisconnectUrl;
+ (id)getAuthRecoverUrl;
+ (id)getAuthRestoreUrl;
+ (id)getAuthReconnectUrl;
+ (id)getAuthConnectUrl;
+ (id)getNoticeUrl;
+ (id)feedbackUploadImgUrl;
+ (id)feedbackPullUrl;
+ (id)feedbackAddUrl;
+ (id)FAQVoteUrl;
+ (id)FAQPullUrl;
+ (id)getConfigUrl;
+ (id)getLocationInfoUrl;
+ (id)modifyUserInfoUrl;
+ (id)getUserInfoUrl;
+ (id)friendListUrl;
+ (id)getDelTagUrl;
+ (id)getSetTagUrl;
+ (id)getBindInfoUrl;
+ (id)getBindGarenaUrl;
+ (id)getBindUrl;
+ (id)getTicketUrl;
+ (id)getCheckTokenValidUrl;
+ (id)getIsLoginUrl;
+ (id)getLogoutUrl;
+ (id)getCheckAndLoginUrl;
+ (id)getLoginUrl;
+ (id)preProcessURL:(id)arg1;
+ (id)getHost;
+ (id)getAPIVersion;

@end

