//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IMSDKApplicationDelegate.h"

@interface IMSDKApplicationDelegate (TwitterLogin)
+ (void)load;
- (_Bool)twitterLogin_application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)twitterLogin_application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)twitterLogin_application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 withGameSecret:(id)arg3;
@end

