//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMSDKStatBuglyManager : NSObject
{
}

+ (_Bool)getDetection;
+ (id)getAppId;
+ (void)reportAutoExceptionReport:(_Bool)arg1;
+ (void)reportCrash:(_Bool)arg1;
+ (void)speedTestWithDomainList:(id)arg1;
+ (void)speedTest:(id)arg1;
+ (void)trackPageEnd:(id)arg1;
+ (void)trackPageBegin:(id)arg1;
+ (void)trackEventEnd:(id)arg1 eventBody:(id)arg2;
+ (void)trackEventBegin:(id)arg1 eventBody:(id)arg2;
+ (void)reportPurchase:(id)arg1 currentCode:(id)arg2 expense:(id)arg3 isRealTime:(_Bool)arg4;
+ (void)reportEvent:(id)arg1 params:(id)arg2 isRealtime:(_Bool)arg3;
+ (void)reportEvent:(id)arg1 eventBody:(id)arg2 isRealtime:(_Bool)arg3;
+ (void)start;

@end

