//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMSDKLoginDelegate-Protocol.h"

@class NSString;

@interface IMSDKLoginTwitterManager : NSObject <IMSDKLoginDelegate>
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (_Bool)isSupportApi;
- (_Bool)isInstalled;
- (void)logout;
- (void)bindWithSubChannel:(id)arg1 extra:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (void)checkAndLoginWithPermissions:(id)arg1 handle:(CDUnknownBlockType)arg2;
- (void)loginWithPermissions:(id)arg1 handle:(CDUnknownBlockType)arg2;
- (id)channelID;
- (void)handleLoginWithSession:(id)arg1 actionType:(int)arg2 error:(id)arg3 handle:(CDUnknownBlockType)arg4;
- (void)loginTwitterWithPermissions:(id)arg1 actionType:(int)arg2 handle:(CDUnknownBlockType)arg3;
- (id)mutablecopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initSingleton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

