//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface IMSDKKeychainManager : NSObject
{
    _Bool _isOperating;
    NSMutableDictionary *_keychainData;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isOperating; // @synthesize isOperating=_isOperating;
@property(retain, nonatomic) NSMutableDictionary *keychainData; // @synthesize keychainData=_keychainData;
- (void).cxx_destruct;
- (void)resetAllKeychainItem;
- (void)resetKeychainItemWithIdentifier:(id)arg1;
- (void)saveObject:(id)arg1 identifier:(id)arg2;
- (id)objectWithIdentifier:(id)arg1;
- (void)dealloc;

@end

