//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMSDKLoginDelegate.h"

@class NSString;

@interface IMSDKLoginGameCenterManager : NSObject <IMSDKLoginDelegate>
{
    CDUnknownBlockType completeHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completeHandler; // @synthesize completeHandler;
- (void).cxx_destruct;
- (void)sendUserIdentityToServ:(CDUnknownBlockType)arg1 state:(long long)arg2;
- (void)authenticateLocalPlayer:(CDUnknownBlockType)arg1 state:(long long)arg2;
- (_Bool)isIMSDKLoginGameCenterManagerAvailable;
- (void)loginGameCenterWithState:(long long)arg1 handler:(CDUnknownBlockType)arg2;
- (_Bool)isSupportApi;
- (_Bool)isInstalled;
- (void)logout;
- (void)bindWithSubChannel:(id)arg1 extra:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (void)checkAndLoginWithPermissions:(id)arg1 handle:(CDUnknownBlockType)arg2;
- (void)loginWithPermissions:(id)arg1 handle:(CDUnknownBlockType)arg2;
- (id)channelID;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

