//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IMSDKMTAEvent.h"

#import "IMSDKMTAEventProtocol-Protocol.h"

@class NSString;

@interface IMSDKMTAAdditionEvent : IMSDKMTAEvent <IMSDKMTAEventProtocol>
{
}

- (id)init;
- (void)encode:(id)arg1;
- (int)getType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

