//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADRewardBasedVideoAdDelegate-Protocol.h"

@class NSString;

@interface IMSDKExtendAdMobHelper : NSObject <GADRewardBasedVideoAdDelegate>
{
    NSString *_adUnitID;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
- (void).cxx_destruct;
- (void)rewardBasedVideoAdDidCompletePlaying:(id)arg1;
- (void)rewardBasedVideoAd:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)rewardBasedVideoAdWillLeaveApplication:(id)arg1;
- (void)rewardBasedVideoAd:(id)arg1 didRewardUserWithReward:(id)arg2;
- (void)rewardBasedVideoAdDidClose:(id)arg1;
- (void)rewardBasedVideoAdDidStartPlaying:(id)arg1;
- (void)rewardBasedVideoAdDidOpen:(id)arg1;
- (void)rewardBasedVideoAdDidReceiveAd:(id)arg1;
- (void)handleShowVideoResult:(struct IMSDKResult)arg1;
- (void)handleLoadRequestResult:(struct IMSDKResult)arg1;
- (void)setUserId:(id)arg1;
- (void)loadUserId;
- (void)loadRequestWithUnitId:(id)arg1;
- (id)admobDeviceID;
- (void)showRewardVideo;
- (id)mutablecopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initSingleton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

