//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GCloudBGApplication, NSMutableArray;

@interface IOSBGDownloadManager : NSObject
{
    GCloudBGApplication *_theApp;
    NSMutableArray *_taskArray;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *taskArray; // @synthesize taskArray=_taskArray;
@property(retain, nonatomic) GCloudBGApplication *theApp; // @synthesize theApp=_theApp;
- (void).cxx_destruct;
- (_Bool)AddRetryTasks;
- (void)CancalIOSBGTask;
- (void)RemoveAllDownloadTask;
- (void)RepairBackgroundDownloadDirectory;
- (_Bool)StartMoreTask_MultiRange:(long long)arg1 withDownloadTask:(id)arg2;
- (_Bool)StartMoreTask:(long long)arg1 withDownloadTask:(id)arg2;
- (_Bool)PrepareBackgroundDownload;
- (void)SetBGApplication:(id)arg1;
- (void)dealloc;
- (id)init;

@end

