//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKContainer, CKDatabase;

@interface IOSCloudStorage : NSObject
{
    CKContainer *CloudContainer;
    CKDatabase *SharedDatabase;
    CKDatabase *UserDatabase;
    id iCloudToken;
}

+ (id)cloudStorage;
@property(retain) id iCloudToken; // @synthesize iCloudToken;
@property(retain) CKDatabase *UserDatabase; // @synthesize UserDatabase;
@property(retain) CKDatabase *SharedDatabase; // @synthesize SharedDatabase;
@property(retain) CKContainer *CloudContainer; // @synthesize CloudContainer;
- (void)iCloudAccountAvailabilityChanged:(id)arg1;
- (_Bool)query:(_Bool)arg1 fetchHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)deleteFile:(id)arg1 sharedDB:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)writeFile:(id)arg1 contents:(id)arg2 sharedDB:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)readFile:(id)arg1 sharedDB:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init:(_Bool)arg1;

@end

