//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class LineSDKConfiguration;

@interface LineSDKHTTPClient : NSObject
{
    LineSDKConfiguration *_configuration;
}

@property(retain, nonatomic) LineSDKConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)buildRequest:(id)arg1;
- (void)sendWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithConfiguration:(id)arg1;

@end

