//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LineSDKConfiguration;

@interface LineSDKHTTPClient : NSObject
{
    LineSDKConfiguration *_configuration;
}

@property(retain, nonatomic) LineSDKConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)buildRequest:(id)arg1;
- (void)sendWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithConfiguration:(id)arg1;

@end

