//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LineSDKAccessToken;

@protocol LineSDKAuthenticationRefreshDelegate <NSObject>
- (void)refreshTokenWithAccessToken:(LineSDKAccessToken *)arg1 completion:(void (^)(LineSDKAccessToken *, NSError *))arg2;
@end

