//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LineSDKCredential, LineSDKLogin, LineSDKProfile, NSError;

@protocol LineSDKLoginDelegate <NSObject>
- (void)didLogin:(LineSDKLogin *)arg1 credential:(LineSDKCredential *)arg2 profile:(LineSDKProfile *)arg3 error:(NSError *)arg4;
@end

