//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MessageQueue : NSObject
{
    char _buffer[16384];
    struct SDKWriteBuffer *_writeBuffer;
    struct _DataPerSec _dataPerSec;
    unsigned int _lastFrameTimestamp;
    unsigned int _maxPss;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned int maxPss; // @synthesize maxPss=_maxPss;
- (void)dealloc;
- (void)isFlushBufferToFile:(unsigned long long)arg1;
- (void)flushBufferToFile;
- (void)pushMessageToGloabelBufferQueue:(unsigned long long)arg1 DataPerSec:(struct _DataPerSec)arg2 isWriteToBuffer:(_Bool)arg3;
- (void)pushMessageToGloabelBufferQueue:(struct _Scene)arg1 forceWriteToFile:(_Bool)arg2;
- (int)pushMessageToGloabelBufferQueueType:(unsigned long long)arg1 int8:(BOOL)arg2 int16:(short)arg3 int32:(int)arg4 bytes:(const char *)arg5 bytesLen:(int)arg6;
- (void)pushMessageToGloabelBufferQueueBytes:(const char *)arg1 bufferLen:(short)arg2;
- (void)pushMessageToGloabelBufferQueueInt64:(long long)arg1;
- (void)pushMessageToGloabelBufferQueueInt32:(int)arg1;
- (void)pushMessageToGloabelBufferQueueInt16:(short)arg1;
- (void)pushMessageToGloabelBufferQueueInt8:(BOOL)arg1;
- (void)pushMessageToGloabelBufferQueue:(CDStruct_13d97d58)arg1;
- (void)pushMessageToGloabelBufferCustomData:(struct _MsgQueueBody)arg1 type:(unsigned long long)arg2;
- (void)consumeFramesWithCompress:(struct MsgQueue *)arg1;
- (void)closeCacheFile;
- (void)setCacheFileName:(id)arg1;
- (void)reset;
- (id)init;

@end

