//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MidasIAPPayDelegate-Protocol.h"

@class NSString;

@interface MidasOCCallbackHanlder : NSObject <MidasIAPPayDelegate>
{
    struct MidasGetProductCallback *mProductCB;
    struct MidasGetIntroPriceCallback *mIntroPriceCB;
    struct MidasGetInfoCallback *mShortOpenidBack;
    struct MidasReprovideCallback *mReprovideCallback;
}

- (id)strFromResp:(id)arg1;
- (void)onResp:(id)arg1;
- (void)needLogin;
- (void)setReprovideCallback:(struct MidasReprovideCallback *)arg1;
- (void)setShortOpenidCallback:(struct MidasGetInfoCallback *)arg1;
- (void)setIntroPriceCallback:(struct MidasGetIntroPriceCallback *)arg1;
- (void)setLocalPriceCallback:(struct MidasGetProductCallback *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

