//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MidasBox : NSObject
{
}

+ (id)shareInstance;
- (void)addRouter:(Class)arg1;
- (void)registerService:(id)arg1 service:(Class)arg2;

@end

