//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol MidasKeyStoreObserver <NSObject>
- (void)onUpdateFailErrorCode:(long long)arg1 innerCode:(NSString *)arg2 msg:(NSString *)arg3;
- (void)onUpdateSuccess;
@end

