//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

@interface MidasProtocolHider : NSObject
{
    NSMutableSet *_protocols;
    NSMutableDictionary *_selPairs;
}

+ (_Bool)isInstanceSelector:(SEL)arg1 belongsToProtocol:(id)arg2;
- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(id)arg1;
- (void)replaceProtocol:(id)arg1 instanceSelector:(SEL)arg2 withInstanceSelector:(SEL)arg3;
- (void)registerProtocol:(id)arg1;

@end

