//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MidasBaseJSCallback.h"

@interface MidasVerifyCodePageJSCallback : MidasBaseJSCallback
{
}

- (void)on_verify_cancel:(id)arg1 webViewcController:(id)arg2;
- (void)on_verify_setSize:(id)arg1 webViewcController:(id)arg2;
- (void)on_verify_setTitle:(id)arg1 webViewcController:(id)arg2;
- (void)on_verify_verify_completed:(id)arg1 webViewcController:(id)arg2;

@end

