//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MidasAddrConfiguration : NSObject
{
    unsigned long long _updateOptions;
    unsigned long long _measureStrategy;
    unsigned long long _dualStackStrategy;
    unsigned long long _cacheStrategy;
}

@property(nonatomic) unsigned long long cacheStrategy; // @synthesize cacheStrategy=_cacheStrategy;
@property(nonatomic) unsigned long long dualStackStrategy; // @synthesize dualStackStrategy=_dualStackStrategy;
@property(nonatomic) unsigned long long measureStrategy; // @synthesize measureStrategy=_measureStrategy;
@property(nonatomic) unsigned long long updateOptions; // @synthesize updateOptions=_updateOptions;
- (id)description;
- (id)initWithDefaultOptions;
- (id)init;

@end

