//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MidasIAPConcurrentJob.h"

@class MidasIAPCacheItem;

@interface MidasIAPInfoJob : MidasIAPConcurrentJob
{
    _Bool _started;
    _Bool _isOvertimeCancel;
    MidasIAPCacheItem *_cacheItem;
}

@property(nonatomic) _Bool isOvertimeCancel; // @synthesize isOvertimeCancel=_isOvertimeCancel;
@property(retain, nonatomic) MidasIAPCacheItem *cacheItem; // @synthesize cacheItem=_cacheItem;
- (void).cxx_destruct;
- (void)jobMainProc;
- (void)stop;
- (void)start;
- (void)dealloc;

@end

