//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MidasIAPInputView;

@protocol MidasIAPInputViewDelegate <NSObject>
- (void)inputViewWillReturn:(MidasIAPInputView *)arg1;
- (void)inputViewDidLoseFocus:(MidasIAPInputView *)arg1;
- (void)inputViewWillOnFocus:(MidasIAPInputView *)arg1;
@end

