//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MidasIAPUserInfo, MidasIapOrderInfo;

@interface MidasIAPConcurrentJob : NSObject
{
    _Bool _finished;
    _Bool _forceBreak;
    id _delegate;
    MidasIapOrderInfo *_orderInfo;
    MidasIAPUserInfo *_userInfo;
}

@property(retain, nonatomic) MidasIAPUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) MidasIapOrderInfo *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(nonatomic) _Bool forceBreak; // @synthesize forceBreak=_forceBreak;
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)jobMainProc;
- (void)stop;
- (void)start;
- (id)initWithDelegate:(id)arg1;
- (id)init;

@end

