//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MidasIAPPayOperation.h"

@class NSMutableArray;

@interface MidasIAPReprovideOperation : MidasIAPPayOperation
{
    NSMutableArray *_transactions;
    NSMutableArray *_willBeFinishTrans;
    _Bool _fromManual;
}

@property(nonatomic) _Bool fromManual; // @synthesize fromManual=_fromManual;
- (void).cxx_destruct;
- (void)onJobQueueCompleted:(_Bool)arg1 jobs:(id)arg2;
- (void)blockProcessNewProvideCgiError:(long long)arg1 inner:(id)arg2 msg:(id)arg3 workingStep:(int)arg4;
- (void)blockProcessOldProvideCgiError:(long long)arg1 inner:(id)arg2 msg:(id)arg3 transactionID:(id)arg4 workingStep:(int)arg5;
- (void)blockProcessNewProvideNetError:(long long)arg1 workingStep:(int)arg2;
- (void)blockProcessOldProvideNetError:(long long)arg1 transactionID:(id)arg2 workingStep:(int)arg3;
- (void)notify;
- (void)dispatchTransactions;
- (id)toRequestInfo;
- (_Bool)midas_paymentQueue:(id)arg1 midas_updatedTransactions:(id)arg2;
- (void)blockProcessProvideCgiSuccess:(id)arg1 transactionID:(id)arg2;
- (void)blockProcessNewProvideCgiSuccess:(id)arg1;
- (void)blockFinalSuccess:(id)arg1;
- (void)_blockCommonFinalSuccess:(id)arg1;
- (void)blockDoProvide;
- (void)blockDoNewProvide:(id)arg1;
- (void)start;

@end

