//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MidasRecord : NSObject
{
    NSString *_recordContent;
    NSString *_identifier;
}

+ (id)recordWithReports:(id)arg1;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *recordContent; // @synthesize recordContent=_recordContent;
- (void).cxx_destruct;
- (id)initWithContent:(id)arg1;

@end

