//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPNativeAdRenderingImageLoader, NSDictionary, NSNumber, UIImageView, UILabel, UINib, UIView;

@protocol MPNativeAdRendering <NSObject>

@optional
+ (UINib *)nibForAd;
- (void)layoutCustomAssetsWithProperties:(NSDictionary *)arg1 imageLoader:(MPNativeAdRenderingImageLoader *)arg2;
- (void)layoutStarRating:(NSNumber *)arg1;
- (UIImageView *)nativePrivacyInformationIconImageView;
- (UILabel *)nativeCallToActionTextLabel;
- (UIView *)nativeVideoView;
- (UIImageView *)nativeMainImageView;
- (UIImageView *)nativeIconImageView;
- (UILabel *)nativeTitleTextLabel;
- (UILabel *)nativeMainTextLabel;
@end

