//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (AWSGZIP)
- (id)awsgzip_gunzippedData;
- (id)awsgzip_gzippedData;
- (id)awsgzip_gzippedDataWithCompressionLevel:(float)arg1;
@end

