//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (FBSDKLoginError)
+ (id)fbErrorWithSystemAccountStoreDeniedError:(id)arg1 isCancellation:(_Bool *)arg2;
+ (id)fbErrorFromServerError:(id)arg1;
+ (id)fbErrorFromReturnURLParameters:(id)arg1;
+ (id)fbErrorForSystemPasswordChange:(id)arg1;
+ (id)fbErrorForFailedLoginWithCode:(long long)arg1 innerError:(id)arg2;
+ (id)fbErrorForFailedLoginWithCode:(long long)arg1;
@end

