//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (FBAdUtility)
- (_Bool)fb_getSizeOfDirectory:(unsigned long long *)arg1 atURL:(id)arg2 error:(id *)arg3;
@end

