//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (AWS)
- (_Bool)aws_atomicallyCopyItemAtURL:(id)arg1 toURL:(id)arg2 backupItemName:(id)arg3 error:(id *)arg4;
@end

