//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (ContentType)
+ (id)contentTypeForImageUTIValue:(struct __CFString *)arg1;
- (unsigned long long)contentCategoryForFile;
- (id)contentTypeForFile;
@end

