//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface NSValueTransformer (AWSMTLPredefinedTransformerAdditions)
+ (id)awsmtl_NSInputStreamValueTransformerWithData:(id)arg1;
+ (id)awsmtl_valueMappingTransformerWithDictionary:(id)arg1 defaultValue:(id)arg2 reverseDefaultValue:(id)arg3;
+ (id)awsmtl_valueMappingTransformerWithDictionary:(id)arg1;
+ (id)awsmtl_JSONArrayTransformerWithModelClass:(Class)arg1;
+ (id)awsmtl_JSONDictionaryTransformerWithModelClass:(Class)arg1;
+ (void)load;
@end

