//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, PLCrashReport;

@protocol PLCrashReportFormatter
- (NSData *)formatReport:(PLCrashReport *)arg1 error:(id *)arg2;
@end

