//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PRF : NSObject
{
    BOOL i;
    BOOL j;
    BOOL temp;
    char *S;
}

- (unsigned char)enc:(unsigned char)arg1;
- (id)init;

@end

