//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ScreenShot : NSObject
{
}

- (void)takeScreenShotEx:(id)arg1;
- (void *)getBufFromImage:(id)arg1;
- (id)screenshotOfView:(id)arg1;
- (id)getAppWindowsForScreen:(id)arg1;

@end

