//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDWebImageProgressiveCoder-Protocol.h"

@class NSString;

@interface SDWebImageWebPCoder : NSObject <SDWebImageProgressiveCoder>
{
    struct WebPIDecoder *_idec;
}

+ (id)sharedCoder;
- (id)sd_encodedWebpDataWithImage:(id)arg1;
- (id)encodedDataWithImage:(id)arg1 format:(long long)arg2;
- (_Bool)canEncodeToFormat:(long long)arg1;
- (struct CGColorSpace *)sd_colorSpaceWithDemuxer:(struct WebPDemuxer *)arg1;
- (id)sd_rawWebpImageWithData:(struct WebPData)arg1 colorSpace:(struct CGColorSpace *)arg2;
- (id)sd_drawnWebpImageWithCanvas:(struct CGContext *)arg1 iterator:(struct WebPIterator)arg2 colorSpace:(struct CGColorSpace *)arg3;
- (id)decompressedImageWithImage:(id)arg1 data:(id *)arg2 options:(id)arg3;
- (id)incrementallyDecodedImageWithData:(id)arg1 finished:(_Bool)arg2;
- (id)decodedImageWithData:(id)arg1;
- (_Bool)canIncrementallyDecodeFromData:(id)arg1;
- (_Bool)canDecodeFromData:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

