//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString, UIAlertController;

@interface SlateTextField : NSObject <UIAlertViewDelegate>
{
    TSharedPtr_2699a924 TextWidget;
    struct FText TextEntry;
    UIAlertController *AlertController;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)show:(TSharedPtr_2699a924)arg1;
- (void)hide;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

