//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TApmSwitch : NSObject
{
    _Bool _isCDNEnable;
    _Bool _isPostStepEventEnable;
    _Bool _isPostAppStateEnable;
    _Bool _isPostValueEnable;
    _Bool _isZigzagEnable;
    _Bool _isMmapEnable;
    _Bool _isFPSEnable;
    int _option;
    int _frequency;
}

+ (id)sharedInstance;
@property(nonatomic) int frequency; // @synthesize frequency=_frequency;
@property(nonatomic) int option; // @synthesize option=_option;
@property(nonatomic) _Bool isFPSEnable; // @synthesize isFPSEnable=_isFPSEnable;
@property(nonatomic) _Bool isMmapEnable; // @synthesize isMmapEnable=_isMmapEnable;
@property(nonatomic) _Bool isZigzagEnable; // @synthesize isZigzagEnable=_isZigzagEnable;
@property(nonatomic) _Bool isPostValueEnable; // @synthesize isPostValueEnable=_isPostValueEnable;
@property(nonatomic) _Bool isPostAppStateEnable; // @synthesize isPostAppStateEnable=_isPostAppStateEnable;
@property(nonatomic) _Bool isPostStepEventEnable; // @synthesize isPostStepEventEnable=_isPostStepEventEnable;
@property(nonatomic) _Bool isCDNEnable; // @synthesize isCDNEnable=_isCDNEnable;
- (unsigned int)getFrequencyFromUserDefault;
- (int)getOptsUserDefault;
- (_Bool)getEnableFpsFromUserDefault;
- (_Bool)getEnableMmapFromUserDefault;
- (_Bool)getEnableZigZagFromUserDefault;
- (_Bool)getEnablePostValueFromUserDefault;
- (_Bool)getCDNFromUserDefault;
- (_Bool)getEnableStreamEventFrameStateFromUserDefault;
- (_Bool)getEnableAppStateFromUserDefault;
- (void)resetDefaultValue;
- (void)setSwitchValue:(id)arg1;
- (id)init;

@end

