//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MKMapView;

@interface TSELocationMapTableViewHeaderView : UIView
{
    MKMapView *_mapView;
}

@property(readonly, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCenterCoordinates:(struct CLLocationCoordinate2D)arg1;

@end

