//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TSEBaseTableViewCell.h"

@class UIActivityIndicatorView;

@interface TSELoadingTableViewCell : TSEBaseTableViewCell
{
    UIActivityIndicatorView *_loadingIndicatorView;
}

@property(readonly, nonatomic) UIActivityIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
- (void).cxx_destruct;
- (void)setUpConstraints;
- (void)prepareForReuse;
- (id)init;

@end

