//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TSETweet;

@protocol TSENetworking <NSObject>
- (void)loadHydratedTwitterUserForAccount:(id <TSEAccount>)arg1 completion:(void (^)(id <TSETwitterUser>))arg2;
- (void)sendTweet:(TSETweet *)arg1 fromAccount:(id <TSEAccount>)arg2 completion:(void (^)(unsigned long long))arg3;
@end

