//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TSETweet, TSETweetShareViewController;
@protocol TSEAccount;

@protocol TSETweetShareViewControllerDelegate <NSObject>
- (void)shareViewControllerPresentedWithNoAccounts:(TSETweetShareViewController *)arg1;
- (void)shareViewControllerWantsToCancelComposer:(TSETweetShareViewController *)arg1 partiallyComposedTweet:(TSETweet *)arg2;
- (void)shareViewControllerDidFinishSendingTweet:(TSETweetShareViewController *)arg1;

@optional
- (void)shareViewController:(TSETweetShareViewController *)arg1 didSelectAccount:(id <TSEAccount>)arg2;
@end

