//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface TSETweetCustomCardAttachmentView : UIView
{
    id <TSETweetAttachmentCustomCardViewProvider> _attachment;
}

@property(readonly, nonatomic) id <TSETweetAttachmentCustomCardViewProvider> attachment; // @synthesize attachment=_attachment;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithCustomCardAttachment:(id)arg1;

@end

