//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface TWTRBirdView : UIView
{
    UIColor *_birdColor;
    struct CGSize _desiredSize;
}

+ (id)mediumBird;
+ (id)smallBird;
@property(nonatomic) struct CGSize desiredSize; // @synthesize desiredSize=_desiredSize;
- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *birdColor; // @synthesize birdColor=_birdColor;
- (struct CGSize)intrinsicContentSize;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

