//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface TWTRPersistentStoreObject : NSObject
{
    NSString *_key;
    unsigned long long _size;
    NSDate *_accessDate;
}

@property(retain, nonatomic) NSDate *accessDate; // @synthesize accessDate=_accessDate;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

