//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TWTRFileManager : NSObject
{
}

+ (id)pathForFileName:(id)arg1 inDirectory:(id)arg2;
+ (id)readDictionaryFromFileName:(id)arg1 inDirectory:(id)arg2;
+ (_Bool)writeDictionary:(id)arg1 toFileName:(id)arg2 inDirectory:(id)arg3;
+ (_Bool)createFileWithName:(id)arg1 inDirectory:(id)arg2;
+ (id)cacheDirectory;

@end

