//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, TWTRComposerViewController, TWTRTweet;

@protocol TWTRComposerViewControllerDelegate <NSObject>

@optional
- (void)composerDidFail:(TWTRComposerViewController *)arg1 withError:(NSError *)arg2;
- (void)composerDidSucceed:(TWTRComposerViewController *)arg1 withTweet:(TWTRTweet *)arg2;
- (void)composerDidCancel:(TWTRComposerViewController *)arg1;
@end

