//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TWTRImages : NSObject
{
}

+ (id)resourcesImageNamed:(id)arg1;
+ (id)resourcePathForImageName:(id)arg1;
+ (id)buttonImageWithCornerRadius:(double)arg1 backgroundColor:(id)arg2 borderColor:(id)arg3;
+ (id)buttonImageWithCornerRadius:(double)arg1 backgroundColor:(id)arg2;
+ (id)closeButtonTemplateImage;
+ (id)vineBadgeImage;
+ (id)mediaScrubberThumb;
+ (id)mediaReplayTemplateImage;
+ (id)mediaPlayTemplateImage;
+ (id)mediaPauseTemplateImage;
+ (id)playIcon;
+ (id)verifiedIcon;
+ (id)darkRetweet;
+ (id)lightRetweet;
+ (id)retweetImageForBackgroundColor:(id)arg1;
+ (id)shareImageLarge;
+ (id)shareImage;
+ (id)retweetImage;
+ (id)likeImageSheetLarge;
+ (id)likeOffLarge;
+ (id)likeOnLarge;
+ (id)likeImageSheet;
+ (id)likeOff;
+ (id)likeOn;

@end

