//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TWTRVideoPlayerView;

@protocol TWTRVideoPlayerViewDelegate <NSObject>

@optional
- (void)videoPlayerDidBecomeReady:(TWTRVideoPlayerView *)arg1;
- (void)videoPlayer:(TWTRVideoPlayerView *)arg1 didChangePlaybackState:(long long)arg2;
@end

