//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TWTRTweetCache-Protocol.h"

@class NSString, TWTRPersistentStore;

@interface TWTRTweetCache : NSObject <TWTRTweetCache>
{
    TWTRPersistentStore *_store;
}

@property(retain, nonatomic) TWTRPersistentStore *store; // @synthesize store=_store;
- (void).cxx_destruct;
- (_Bool)removeTweetWithID:(id)arg1 perspective:(id)arg2;
- (_Bool)storeTweet:(id)arg1 perspective:(id)arg2;
- (id)tweetWithID:(id)arg1 perspective:(id)arg2;
- (id)initWithPath:(id)arg1 maxSize:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

