//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface TWTRLogInButton : UIButton
{
    CDUnknownBlockType _logInCompletion;
}

+ (id)buttonWithLogInCompletion:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType logInCompletion; // @synthesize logInCompletion=_logInCompletion;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (struct CGSize)intrinsicContentSize;
- (void)buttonTapped;
- (void)tw_commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

