//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface TWTRFrameSheet : NSObject
{
    unsigned long long _imageWidth;
    unsigned long long _imageHeight;
    unsigned long long _rows;
    unsigned long long _columns;
    unsigned long long _frameCount;
    UIImage *_frameSheet;
}

@property(readonly, nonatomic) UIImage *frameSheet; // @synthesize frameSheet=_frameSheet;
@property(readonly, nonatomic) unsigned long long frameCount; // @synthesize frameCount=_frameCount;
@property(readonly, nonatomic) unsigned long long columns; // @synthesize columns=_columns;
@property(readonly, nonatomic) unsigned long long rows; // @synthesize rows=_rows;
@property(readonly, nonatomic) unsigned long long imageHeight; // @synthesize imageHeight=_imageHeight;
@property(readonly, nonatomic) unsigned long long imageWidth; // @synthesize imageWidth=_imageWidth;
- (void).cxx_destruct;
- (id)frameArray;
- (id)initWithImage:(id)arg1 rows:(unsigned long long)arg2 columns:(unsigned long long)arg3 frameCount:(unsigned long long)arg4 imageWidth:(unsigned long long)arg5 imageHeight:(unsigned long long)arg6;

@end

