//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface TWTRMultipartFormElement : NSObject
{
    NSString *_name;
    NSString *_contentType;
    NSString *_fileName;
    NSData *_content;
}

@property(readonly, copy, nonatomic) NSData *content; // @synthesize content=_content;
@property(readonly, copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)documentData;
- (id)initWithName:(id)arg1 contentType:(id)arg2 fileName:(id)arg3 content:(id)arg4;

@end

