//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TWTRNSCodingUtil : NSObject
{
}

+ (void)encodeLongLong:(long long)arg1 forKey:(id)arg2 encoder:(id)arg3;
+ (long long)decodeLongLongForKey:(id)arg1 decoder:(id)arg2;

@end

