//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TWTRGuestSessionStore-Protocol.h"
#import "TWTRSessionRefreshingStore-Protocol.h"
#import "TWTRUserSessionStore-Protocol.h"

@class TWTRAuthConfig;

@protocol TWTRSessionStore <TWTRUserSessionStore, TWTRGuestSessionStore, TWTRSessionRefreshingStore>
@property(readonly, nonatomic) TWTRAuthConfig *authConfig;
@end

