//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVPlayerLayer;

@interface TWTRVideoPlayerViewLayer : UIView
{
}

+ (Class)layerClass;
@property(readonly, nonatomic) AVPlayerLayer *playerLayer;

@end

