//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TWTRSessionMigrating-Protocol.h"

@class NSString;

@interface TWTRSessionMigrator : NSObject <TWTRSessionMigrating>
{
}

- (id)authenticatorUserSessionDictionary;
- (void)logoutAuthenticatorUser;
- (void)removeDeprecatedSessions;
- (void)migrateUserSessionsIntoStore:(id)arg1 removeOnSuccess:(_Bool)arg2;
- (void)runMigrationWithDestination:(id)arg1 removeOnSuccess:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

