//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TWTRMoPubAdConfiguration;

@interface TWTRTableViewAdPlacer : NSObject
{
    id _adPlacer;
    TWTRMoPubAdConfiguration *_adConfig;
}

+ (void)initialize;
@property(readonly, nonatomic) TWTRMoPubAdConfiguration *adConfig; // @synthesize adConfig=_adConfig;
@property(readonly, nonatomic) id adPlacer; // @synthesize adPlacer=_adPlacer;
- (void).cxx_destruct;
- (void)loadAdUnitIfConfigured;
- (id)initWithTableView:(id)arg1 viewController:(id)arg2 adConfiguration:(id)arg3;

@end

