//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHTTPURLResponse;

@interface TWTRAPIDateSync : NSObject
{
    NSHTTPURLResponse *_response;
}

@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
- (void).cxx_destruct;
- (_Bool)sync;
- (id)initWithHTTPResponse:(id)arg1;

@end

