//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (VLink)
+ (_Bool)vl_checkCustomFontExist;
+ (id)vl_fontWithSize:(double)arg1;
@end

