//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (FBNativeAdViewTag)
@property(nonatomic) unsigned long long nativeAdViewTag; // @dynamic nativeAdViewTag;
@end

