//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionTaskDelegate.h"

@class NSString, NSURLSession, NSURLSessionUploadTask;

@interface UploadTaskImpliOS : NSObject <NSURLSessionTaskDelegate>
{
    _Bool _isPause;
    int _part;
    int _partCount;
    struct UploadTaskImpl *_task;
    NSURLSessionUploadTask *_uploadTask;
    NSURLSession *_session;
    long long _state;
    long long _totalSize;
}

@property(nonatomic) _Bool isPause; // @synthesize isPause=_isPause;
@property(nonatomic) long long totalSize; // @synthesize totalSize=_totalSize;
@property(nonatomic) int partCount; // @synthesize partCount=_partCount;
@property(nonatomic) int part; // @synthesize part=_part;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSURLSessionUploadTask *uploadTask; // @synthesize uploadTask=_uploadTask;
@property(nonatomic) struct UploadTaskImpl *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (id)initWithUploadTaskImp:(struct UploadTaskImpl *)arg1;
- (void)Uninit;
- (void)Cancel;
- (void)Pause;
- (void)Upload:(int)arg1 partCount:(int)arg2 part:(int)arg3 md5:(const char *)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

