//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, VLImageView;

@interface VLDialogMediaItemCell : UICollectionViewCell
{
    VLImageView *_imageView;
    UIImageView *_tipIconView;
    UIImageView *_playIconView;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *playIconView; // @synthesize playIconView=_playIconView;
@property(retain, nonatomic) UIImageView *tipIconView; // @synthesize tipIconView=_tipIconView;
@property(retain, nonatomic) VLImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)makeConstraints;
- (void)setUpViews;
- (void)configWithModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

