//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView, VLImageView;

@interface VLFeedsPopupRecmCell : UITableViewCell
{
    VLImageView *_thumbImageView;
    UILabel *_titleLabel;
    UILabel *_infoLabel;
    UIImageView *_iconView;
    UIView *_line;
}

@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) VLImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
- (void).cxx_destruct;
- (void)makeConstraints;
- (void)setUpViews;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)configWithModel:(id)arg1 isLast:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

