//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UICollectionView, VLConnectingView;

@interface VLFeedsRecmMainView : UIView
{
    UICollectionView *_collectionView;
    VLConnectingView *_loadingView;
}

@property(retain, nonatomic) VLConnectingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)makeConstraints;
- (void)setUpViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

