//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDate, NSLayoutConstraint, UIButton, UIImageView, UILabel, VLFeedsSideButton, VLRedDotView;
@protocol VLFeedsViewDelegate;

@interface VLFeedsView : UIView
{
    id <VLFeedsViewDelegate> _delegate;
    long long _redDotCount;
    UIView *_buttonsBGView;
    UIButton *_closeButton;
    VLFeedsSideButton *_sideButton1;
    VLFeedsSideButton *_sideButton2;
    UIButton *_robotButton;
    VLRedDotView *_redDotView;
    NSLayoutConstraint *_redDotWidthConstraint;
    UIImageView *_bubbleGiftView;
    UIView *_bubbleView;
    UILabel *_bubbleLabel;
    NSLayoutConstraint *_bubbleWidthConstraint;
    NSLayoutConstraint *_bubbleHeightConstraint;
    NSDate *_lastShowBubbleDate;
}

@property(retain, nonatomic) NSDate *lastShowBubbleDate; // @synthesize lastShowBubbleDate=_lastShowBubbleDate;
@property(retain, nonatomic) NSLayoutConstraint *bubbleHeightConstraint; // @synthesize bubbleHeightConstraint=_bubbleHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *bubbleWidthConstraint; // @synthesize bubbleWidthConstraint=_bubbleWidthConstraint;
@property(retain, nonatomic) UILabel *bubbleLabel; // @synthesize bubbleLabel=_bubbleLabel;
@property(retain, nonatomic) UIView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(retain, nonatomic) UIImageView *bubbleGiftView; // @synthesize bubbleGiftView=_bubbleGiftView;
@property(retain, nonatomic) NSLayoutConstraint *redDotWidthConstraint; // @synthesize redDotWidthConstraint=_redDotWidthConstraint;
@property(retain, nonatomic) VLRedDotView *redDotView; // @synthesize redDotView=_redDotView;
@property(retain, nonatomic) UIButton *robotButton; // @synthesize robotButton=_robotButton;
@property(retain, nonatomic) VLFeedsSideButton *sideButton2; // @synthesize sideButton2=_sideButton2;
@property(retain, nonatomic) VLFeedsSideButton *sideButton1; // @synthesize sideButton1=_sideButton1;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIView *buttonsBGView; // @synthesize buttonsBGView=_buttonsBGView;
@property(nonatomic) long long redDotCount; // @synthesize redDotCount=_redDotCount;
@property(nonatomic) __weak id <VLFeedsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showBubbleGift;
- (void)showBubbleText:(id)arg1;
- (void)menuSelected:(id)arg1;
- (void)addFeedsContentView:(id)arg1;
- (void)addGradienLayer;
- (void)makeConstraints;
- (void)setUpViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

