//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface VLFeedsRecmMainViewModel : NSObject
{
    _Bool _isAppeared;
    unsigned long long _type;
    NSString *_title;
    NSArray *_items;
}

@property(nonatomic) _Bool isAppeared; // @synthesize isAppeared=_isAppeared;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *cellIdentifier;
@property(readonly, nonatomic) struct CGSize cellSize;
- (id)viewModelsWithItemModels:(id)arg1;
- (id)initWithModel:(id)arg1;

@end

