//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VLLocalizedHelper : NSObject
{
}

+ (id)localizedDateString:(long long)arg1;
+ (id)localizedString:(id)arg1;
+ (void)setLanguage:(id)arg1;
+ (id)bundle;

@end

