//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface VLOptionItemModel : NSObject
{
    NSString *_optionId;
    NSString *_optionText;
    NSString *_optionType;
}

+ (id)modelCustomPropertyMapper;
@property(retain) NSString *optionType; // @synthesize optionType=_optionType;
@property(retain) NSString *optionText; // @synthesize optionText=_optionText;
@property(retain) NSString *optionId; // @synthesize optionId=_optionId;
- (void).cxx_destruct;

@end

