//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface VLRecmNavIndexRespModel : NSObject
{
    NSArray *_tagList;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(retain) NSArray *tagList; // @synthesize tagList=_tagList;
- (void).cxx_destruct;

@end

