//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VLBaseRequest.h"

@class NSMutableDictionary;

@interface VLSendLogsRequest : VLBaseRequest
{
    NSMutableDictionary *_paramDict;
}

@property(retain, nonatomic) NSMutableDictionary *paramDict; // @synthesize paramDict=_paramDict;
- (void).cxx_destruct;
- (_Bool)needCertParam;
- (id)parameters;
- (id)path;
- (id)initWithConfig:(id)arg1 logItems:(id)arg2;

@end

