//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WKNavigationDelegate-Protocol.h"

@class NSDate, NSString, VLWebView;

@interface VLWebViewController : UIViewController <WKNavigationDelegate>
{
    NSString *_webTitle;
    NSString *_url;
    NSDate *_openDate;
}

@property(retain, nonatomic) NSDate *openDate; // @synthesize openDate=_openDate;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *webTitle; // @synthesize webTitle=_webTitle;
- (void).cxx_destruct;
@property(readonly, nonatomic) VLWebView *webView;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)dealloc;
- (void)close;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

