//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WKNavigationDelegate-Protocol.h"

@class NSString, VNGMoatBridge, WKWebView;
@protocol VNGMoatBridgeProtocol;

@interface VNGMoatWebViewAndBridge : NSObject <WKNavigationDelegate>
{
    WKWebView *_webView;
    VNGMoatBridge<VNGMoatBridgeProtocol> *_webBridge;
}

@property(retain) VNGMoatBridge<VNGMoatBridgeProtocol> *webBridge; // @synthesize webBridge=_webBridge;
@property(retain) WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)vivifyDisplayWebViewWithPartnerCode:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

