//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VNGMoatBridge.h"

#import "VNGMoatBridgeProtocol-Protocol.h"

@class NSString, WKWebView;

@interface VNGMoatWKWebViewBridge : VNGMoatBridge <VNGMoatBridgeProtocol>
{
    WKWebView *_webView;
}

@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)handleJSResponse:(id)arg1;
- (void)checkAndSendJS:(id)arg1;
- (id)initWithWebView:(id)arg1 forNativeAd:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

