//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VNGPersistenceManager : NSObject
{
}

+ (id)sharedManager;
- (_Bool)moveFileFrom:(id)arg1 toChannel:(long long)arg2 category:(id)arg3 key:(id)arg4 overwrite:(_Bool)arg5 error:(id *)arg6;
- (id)errorWithPersistenceError:(long long)arg1 description:(id)arg2;
- (id)URLForChannel:(long long)arg1 category:(id)arg2 key:(id)arg3 error:(id *)arg4;
- (id)URLForObject:(id)arg1;
- (_Bool)removeAllObjects:(id *)arg1;
- (_Bool)removeAllObjectsInChannel:(long long)arg1 error:(id *)arg2;
- (_Bool)removeAllObjectsInChannel:(long long)arg1 category:(id)arg2 error:(id *)arg3;
- (_Bool)removeObjectWithChannel:(long long)arg1 category:(id)arg2 key:(id)arg3 error:(id *)arg4;
- (_Bool)removeObject:(id)arg1 error:(id *)arg2;
- (id)loadObjectsWithURLs:(id)arg1 error:(id *)arg2;
- (id)loadObjectURLsAtChannel:(long long)arg1 category:(id)arg2 error:(id *)arg3;
- (id)loadObjectsAtChannel:(long long)arg1 category:(id)arg2 error:(id *)arg3;
- (id)loadObject:(id)arg1 error:(id *)arg2;
- (id)loadObjectWithChannel:(long long)arg1 category:(id)arg2 key:(id)arg3 error:(id *)arg4;
- (id)loadURLsForObjectsWithClass:(Class)arg1 error:(id *)arg2;
- (id)loadObjectsWithClass:(Class)arg1 error:(id *)arg2;
- (id)loadObjectWithClass:(Class)arg1 key:(id)arg2 error:(id *)arg3;
- (_Bool)saveObject:(id)arg1 channel:(long long)arg2 category:(id)arg3 key:(id)arg4 overwrite:(_Bool)arg5 error:(id *)arg6;
- (_Bool)saveObjects:(id)arg1 error:(id *)arg2;
- (_Bool)saveObject:(id)arg1 error:(id *)arg2;

@end

