//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSMutableSet;

@interface VungleOperation : NSOperation
{
    long long _state;
    _Bool _hasFinishedAlready;
    NSMutableSet *_internalErrors;
    CDUnknownBlockType _finishHandler;
}

+ (id)keyPathsForValuesAffectingIsFinished;
+ (id)keyPathsForValuesAffectingIsExecuting;
+ (id)keyPathsForValuesAffectingIsReady;
@property(copy, nonatomic) CDUnknownBlockType finishHandler; // @synthesize finishHandler=_finishHandler;
@property(retain, nonatomic) NSMutableSet *internalErrors; // @synthesize internalErrors=_internalErrors;
@property(nonatomic) _Bool hasFinishedAlready; // @synthesize hasFinishedAlready=_hasFinishedAlready;
- (void).cxx_destruct;
- (void)willEnqueue;
- (void)evaluateConditions;
@property(nonatomic) long long state;
- (void)appendError:(id)arg1;
- (void)appendFinishHandler:(CDUnknownBlockType)arg1;
- (void)finishedWithErrors:(id)arg1;
- (void)finishWithErrors:(id)arg1;
- (void)finish;
- (void)execute;
- (void)start;
- (_Bool)canTransitionToState:(long long)arg1;
- (_Bool)isReady;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (id)init;

@end

