//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSError, NSURL;

@interface VungleNetworkResponse : NSObject
{
    NSData *_data;
    long long _statusCode;
    NSError *_error;
    NSURL *_requestURL;
    NSURL *_localDownloadURL;
    unsigned long long _attempts;
    double _parsedHTTPRetryAfterTime;
}

+ (id)vungleNetworkResponseWithNSHTTPURLResponse:(id)arg1;
@property(nonatomic) double parsedHTTPRetryAfterTime; // @synthesize parsedHTTPRetryAfterTime=_parsedHTTPRetryAfterTime;
@property(nonatomic) unsigned long long attempts; // @synthesize attempts=_attempts;
@property(copy, nonatomic) NSURL *localDownloadURL; // @synthesize localDownloadURL=_localDownloadURL;
@property(copy, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
@property(readonly) _Bool hasSuccessfulHTTPStatus;
@property(readonly) _Bool hasHTTPData;
- (id)initWithData:(id)arg1 statusCode:(long long)arg2;

@end

