//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, VunglePlacement;

@protocol VungleRequestStreamingAdControllerDelegate <NSObject>
- (void)streamingAdControllerShouldPlayAdForPlacement:(VunglePlacement *)arg1;
- (void)streamingAdControllerDidValidateCTA:(_Bool)arg1;

@optional
- (void)streamingAdControllerFailedToLoadStreamingAdForPlacement:(VunglePlacement *)arg1 error:(NSError *)arg2;
@end

