//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "VungleSDKDelegate.h"

@class NSMutableArray, NSString;

@interface VungleRouter : NSObject <VungleSDKDelegate>
{
    _Bool _isInitialising;
    NSMutableArray *_delegates;
    id <VungleDelegate> _playingDelegate;
}

+ (id)findPlacement:(id)arg1 networkExtras:(id)arg2;
+ (void)parseServerParameters:(id)arg1 networkExtras:(id)arg2 result:(CDUnknownBlockType)arg3;
+ (id)sharedInstance;
+ (id)adapterVersion;
@property(retain) id <VungleDelegate> playingDelegate; // @synthesize playingDelegate=_playingDelegate;
@property(retain) NSMutableArray *delegates; // @synthesize delegates=_delegates;
@property(readonly) _Bool isInitialising; // @synthesize isInitialising=_isInitialising;
- (void).cxx_destruct;
- (void)vungleSDKDidInitialize;
- (void)vungleAdPlayabilityUpdate:(_Bool)arg1 placementID:(id)arg2 error:(id)arg3;
- (void)vungleDidCloseAdWithViewInfo:(id)arg1 placementID:(id)arg2;
- (void)vungleWillCloseAdWithViewInfo:(id)arg1 placementID:(id)arg2;
- (void)vungleWillShowAdForPlacementID:(id)arg1;
- (void)initialized:(_Bool)arg1 error:(id)arg2;
- (_Bool)playAd:(id)arg1 delegate:(id)arg2 extras:(id)arg3;
- (void)loadAd:(id)arg1;
- (void)notifyAdIsReady:(id)arg1;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)initWithAppId:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

