//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VungleGroupOperation.h"

@class VungleInternalMRAIDAd;

@interface VunglePrepareMRAIDAdOperation : VungleGroupOperation
{
    VungleInternalMRAIDAd *_MRAIDAd;
    CDUnknownBlockType _completionHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak VungleInternalMRAIDAd *MRAIDAd; // @synthesize MRAIDAd=_MRAIDAd;
- (void).cxx_destruct;
- (void)operationDidFinish:(id)arg1 withErrors:(id)arg2;
- (void)execute;
- (id)initWithVungleMRAIDAd:(id)arg1 networkManager:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

