//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VungleUIFactory : NSObject
{
}

+ (double)adjustedButtonPadding:(double)arg1 originalSize:(struct CGSize)arg2 adjustedSize:(struct CGSize)arg3;
+ (struct CGSize)adjustedButtonSize:(struct CGSize)arg1 clickArea:(double)arg2;
+ (id)muteOffButtonImage;
+ (id)muteOnButtonImage;
+ (id)callToActionButtonImage;
+ (id)closeButtonImage;
+ (id)vungleBlue;
+ (id)vungleProgressBar;
+ (id)vungleCTAButtonWithImage:(id)arg1 originalSize:(struct CGSize)arg2 clickArea:(double)arg3;
+ (id)vungleCloseButtonWithImage:(id)arg1;
+ (id)vungleButtonWithImage:(id)arg1;

@end

