//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface VungleLogCoordinator : NSObject
{
    NSMutableArray *_loggers;
}

@property(retain, nonatomic) NSMutableArray *loggers; // @synthesize loggers=_loggers;
- (void).cxx_destruct;
- (void)detachLogger:(id)arg1;
- (void)attachLogger:(id)arg1;
- (void)log:(id)arg1 withParameters:(char *)arg2;
- (void)log:(id)arg1;
- (id)init;

@end

