//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleNetworkRequestBodyBuilder.h"

@interface VungleConfigRequestBodyBuilder : VungleNetworkRequestBodyBuilder
{
}

- (id)buildRequestParameters;
- (id)initWithNetworkManager:(id)arg1 publisherInformation:(id)arg2;

@end

