//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADAdNetworkExtras-Protocol.h"

@class NSArray, NSString;

@interface VungleAdNetworkExtras : NSObject <GADAdNetworkExtras>
{
    _Bool _muted;
    NSString *_userId;
    unsigned long long _ordinal;
    double _flexViewAutoDismissSeconds;
    NSArray *_allPlacements;
    NSString *_playingPlacement;
}

@property(copy, nonatomic) NSString *playingPlacement; // @synthesize playingPlacement=_playingPlacement;
@property(copy, nonatomic) NSArray *allPlacements; // @synthesize allPlacements=_allPlacements;
@property(nonatomic) double flexViewAutoDismissSeconds; // @synthesize flexViewAutoDismissSeconds=_flexViewAutoDismissSeconds;
@property(nonatomic) unsigned long long ordinal; // @synthesize ordinal=_ordinal;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

