//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, VungleNativeCommandHandler;

@protocol VungleNativeCommandHandlerDelegate <NSObject>
- (void)commandHandlerHandlePresentStoreView;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handlePrepareStoreViewWithAppStoreID:(NSString *)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleErrorCode:(NSString *)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleSuccessfulView:(_Bool)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleUIAction:(NSString *)arg2 withValue:(NSString *)arg3;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleUIAction:(NSString *)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleConsentAction:(NSString *)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleTPAT:(NSString *)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleMRAIDOpenCallForURL:(NSURL *)arg2;
- (void)commandHandlerHandleMRAIDClose:(VungleNativeCommandHandler *)arg1;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleMRAIDSetOrientationPropertiesWithForceOrientationMask:(unsigned long long)arg2;
- (void)commandHandler:(VungleNativeCommandHandler *)arg1 handleMRAIDCustomClose:(long long)arg2;
@end

