//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>;

@interface VungleGCDTimer : NSObject
{
    NSObject<OS_dispatch_source> *_timer;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void).cxx_destruct;
- (_Bool)setupWithInterval:(double)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)cancel;
- (_Bool)startWithInterval:(double)arg1 dispatchBlock:(CDUnknownBlockType)arg2 error:(id *)arg3;
- (id)initWithQueue:(id)arg1;

@end

