//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VungleLoggerDelegate-Protocol.h"

@class NSString, NSURL, NSUserDefaults, NSValueTransformer, VungleNetworkManager;

@interface VungleHTTPLogSender : NSObject <VungleLoggerDelegate>
{
    _Bool _enabled;
    NSURL *_remoteURL;
    NSValueTransformer *_logLineValueTransfomer;
    VungleNetworkManager *_networkManager;
    double _flushInterval;
    NSUserDefaults *_defaults;
}

+ (id)createUploadOpForLogEntries:(id)arg1 batchID:(long long)arg2 networkManager:(id)arg3 remoteURL:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
+ (id)processLogLinesAtPath:(id)arg1 withTransformer:(id)arg2;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) NSUserDefaults *defaults; // @synthesize defaults=_defaults;
@property(nonatomic) double flushInterval; // @synthesize flushInterval=_flushInterval;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property(retain, nonatomic) NSValueTransformer *logLineValueTransfomer; // @synthesize logLineValueTransfomer=_logLineValueTransfomer;
@property(retain, nonatomic) NSURL *remoteURL; // @synthesize remoteURL=_remoteURL;
- (void).cxx_destruct;
- (void)sendLogs:(id)arg1 fileURL:(id)arg2;
- (void)loggerDidReachMaximumEntriesInLogFile:(id)arg1;
- (void)processStoredBatchLogs;
- (void)pause;
- (void)start;
- (id)initWithRemoteURL:(id)arg1 networkManager:(id)arg2 logLineValueTransformer:(id)arg3 flushTimeInterval:(double)arg4 defaults:(id)arg5 enabled:(_Bool)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

