//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@interface VungleConcurrentOperation : NSOperation
{
    _Bool _running;
    _Bool _didCancel;
    CDUnknownBlockType _resultBlock;
}

@property(nonatomic) _Bool didCancel; // @synthesize didCancel=_didCancel;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
- (void).cxx_destruct;
- (_Bool)isCancelled;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)isAsynchronous;
- (_Bool)isConcurrent;
- (void)cancel;
- (void)finishOperation;
- (void)start;
- (id)initWithResultBlock:(CDUnknownBlockType)arg1;

@end

