//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLSessionDataDelegate.h"

@class NSDictionary, NSError, NSString, NSURL, NSURLConnection, NSURLSession, NSURLSessionTask, VungleBackoffCalculator, VungleNetworkResponse;

@interface VungleNetworkOperation : NSOperation <NSURLSessionDataDelegate, NSURLConnectionDataDelegate>
{
    _Bool _hasQueryParameters;
    _Bool _isInternal;
    _Bool _TPAT;
    _Bool _didCancel;
    _Bool _running;
    NSDictionary *_parameters;
    NSDictionary *_extraHeaders;
    NSString *_sdkVersion;
    NSURL *_url;
    unsigned long long _maxAttempts;
    double _timeout;
    NSString *_pluginName;
    NSString *_navigatorUserAgent;
    id <VungleNetworkOperationDelegate> _delegate;
    VungleNetworkResponse *_response;
    NSError *_error;
    NSURLSessionTask *_task;
    NSDictionary *_requestParameters;
    NSURLSession *_session;
    unsigned long long _requestType;
    CDUnknownBlockType _taskSetupCompletionBlock;
    VungleBackoffCalculator *_backoffCalculator;
    NSURLConnection *_connection;
    unsigned long long _currentBackoffIndex;
}

+ (id)URLEncodeString:(id)arg1;
@property(nonatomic) unsigned long long currentBackoffIndex; // @synthesize currentBackoffIndex=_currentBackoffIndex;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(retain, nonatomic) VungleBackoffCalculator *backoffCalculator; // @synthesize backoffCalculator=_backoffCalculator;
@property(copy, nonatomic) CDUnknownBlockType taskSetupCompletionBlock; // @synthesize taskSetupCompletionBlock=_taskSetupCompletionBlock;
@property(nonatomic) unsigned long long requestType; // @synthesize requestType=_requestType;
@property(nonatomic) __weak NSURLSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSDictionary *requestParameters; // @synthesize requestParameters=_requestParameters;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
@property(nonatomic) _Bool didCancel; // @synthesize didCancel=_didCancel;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) VungleNetworkResponse *response; // @synthesize response=_response;
@property(nonatomic) __weak id <VungleNetworkOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isTPAT) _Bool TPAT; // @synthesize TPAT=_TPAT;
@property(copy, nonatomic) NSString *navigatorUserAgent; // @synthesize navigatorUserAgent=_navigatorUserAgent;
@property(retain, nonatomic) NSString *pluginName; // @synthesize pluginName=_pluginName;
@property(nonatomic) _Bool isInternal; // @synthesize isInternal=_isInternal;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(nonatomic) unsigned long long maxAttempts; // @synthesize maxAttempts=_maxAttempts;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(copy, nonatomic) NSDictionary *extraHeaders; // @synthesize extraHeaders=_extraHeaders;
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) _Bool hasQueryParameters; // @synthesize hasQueryParameters=_hasQueryParameters;
- (void).cxx_destruct;
- (unsigned long long)retryState;
- (unsigned long long)attemptsRemaining;
- (_Bool)didReachMaxAttempts;
- (_Bool)isFirstAttempt;
@property(readonly, nonatomic) _Bool shouldKeepTrying;
- (void)dispatchBackoffConnectionWithRequest:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)encodedURLParametersStringWithDictionary:(id)arg1;
- (void)prepareRequest:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 inDict:(id)arg3;
- (void)finishOperation;
- (_Bool)handleData:(id)arg1 error:(id *)arg2;
- (void)terminate;
- (void)retryBaseRequestWithBackoff;
- (void)cancel;
- (_Bool)isCancelled;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)isAsynchronous;
- (_Bool)isConcurrent;
- (id)taskWithRequest:(id)arg1 session:(id)arg2;
- (void)start;
- (void)setName:(id)arg1;
- (id)initWithURL:(id)arg1 requestType:(unsigned long long)arg2 parameters:(id)arg3 session:(id)arg4 taskSetupCompletionBlock:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

