//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VungleNetworkRequestBodyBuilder.h"

@class NSDictionary;

@interface VungleReportRequestBodyBuilder : VungleNetworkRequestBodyBuilder
{
    NSDictionary *_reportDictionary;
}

@property(retain, nonatomic) NSDictionary *reportDictionary; // @synthesize reportDictionary=_reportDictionary;
- (void).cxx_destruct;
- (id)buildRequestParameters;
- (id)initWithReportInfo:(id)arg1 networkManager:(id)arg2 publisherInformation:(id)arg3;

@end

