//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VungleGroupOperation.h"

@class VungleNetworkManager;

@interface VungleRetrieveLegacyAdPartsOperation : VungleGroupOperation
{
    VungleNetworkManager *_manager;
}

@property(retain, nonatomic) VungleNetworkManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)initWithVungleAdLegacy:(id)arg1 networkManager:(id)arg2 cacheManager:(id)arg3;

@end

