//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol VungleMRAIDCommandDelegate <NSObject>
- (void)commandPresentStoreView;
- (void)commandPrepareStoreView:(NSString *)arg1;
- (void)commandError:(NSString *)arg1;
- (void)commandSuccessfulView;
- (void)commandUIAction:(NSString *)arg1 withValue:(NSString *)arg2;
- (void)commandUIAction:(NSString *)arg1;
- (void)commandConsentAction:(NSString *)arg1;
- (void)commandTPATEvent:(NSString *)arg1;
@end

