//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;

@protocol VungleCacheable <NSObject>
- (_Bool)isCached;
- (_Bool)storeInCacheWithError:(id *)arg1;
- (NSURL *)expectedLocalCacheURL;
@end

