//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VungleDismissibleContainerViewDelegate-Protocol.h"
#import "VungleMRAIDBridgeDelegate-Protocol.h"

@class NSString, UIViewController, VungleCacheManager, VungleDismissibleWebViewContainerView, VungleMRAIDAd, VungleMRAIDBridge, VungleMRAIDViewProperties, VunglePlacement, VungleWebViewFacade;
@protocol VungleMRAIDControllerDelegate, VungleMRAIDReportBuilderProtocol;

@interface VungleMRAIDController : NSObject <VungleDismissibleContainerViewDelegate, VungleMRAIDBridgeDelegate>
{
    _Bool _isAdLoading;
    _Bool _didFinishDisplayingAd;
    _Bool _isSuccessfulAdView;
    VungleMRAIDViewProperties *_mraidViewProperties;
    id <VungleMRAIDControllerDelegate> _delegate;
    UIViewController *_presenterViewController;
    VungleWebViewFacade *_webViewFacade;
    VungleMRAIDAd *_ad;
    VunglePlacement *_placement;
    VungleMRAIDBridge *_MRAIDbridge;
    VungleDismissibleWebViewContainerView *_adContainerView;
    id <VungleMRAIDReportBuilderProtocol> _reportBuilder;
    VungleCacheManager *_cacheManager;
}

@property(nonatomic) __weak VungleCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
@property(nonatomic) _Bool isSuccessfulAdView; // @synthesize isSuccessfulAdView=_isSuccessfulAdView;
@property(retain, nonatomic) id <VungleMRAIDReportBuilderProtocol> reportBuilder; // @synthesize reportBuilder=_reportBuilder;
@property(nonatomic) _Bool didFinishDisplayingAd; // @synthesize didFinishDisplayingAd=_didFinishDisplayingAd;
@property(retain, nonatomic) VungleDismissibleWebViewContainerView *adContainerView; // @synthesize adContainerView=_adContainerView;
@property(retain, nonatomic) VungleMRAIDBridge *MRAIDbridge; // @synthesize MRAIDbridge=_MRAIDbridge;
@property(retain, nonatomic) VunglePlacement *placement; // @synthesize placement=_placement;
@property(retain, nonatomic) VungleMRAIDAd *ad; // @synthesize ad=_ad;
@property(nonatomic) _Bool isAdLoading; // @synthesize isAdLoading=_isAdLoading;
@property(retain, nonatomic) VungleWebViewFacade *webViewFacade; // @synthesize webViewFacade=_webViewFacade;
@property(nonatomic) __weak UIViewController *presenterViewController; // @synthesize presenterViewController=_presenterViewController;
@property(nonatomic) __weak id <VungleMRAIDControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) VungleMRAIDViewProperties *mraidViewProperties; // @synthesize mraidViewProperties=_mraidViewProperties;
- (void).cxx_destruct;
- (void)handleNativePresentStoreView;
- (void)handleNativePrepareStoreView:(id)arg1;
- (void)bridge:(id)arg1 handleNativeCommandIsSuccessfulView:(_Bool)arg2;
- (void)bridge:(id)arg1 handleNativeCommandTPATKey:(id)arg2;
- (void)handleNativeCommandCriticalErrorWithBridge:(id)arg1;
- (void)bridge:(id)arg1 handleNativeCommandSetOrientationPropertiesWithForceOrientationMask:(unsigned long long)arg2;
- (void)bridge:(id)arg1 handleNativeCommandUseCustomClose:(long long)arg2;
- (void)bridge:(id)arg1 handleDisplayForDestinationURL:(id)arg2;
- (void)handleNativeCommandCloseWithBridge:(id)arg1;
- (void)MRAIDBridgeDidLoadAd:(id)arg1;
- (void)MRAIDBridge:(id)arg1 didFailToLoad:(id)arg2;
- (void)dismissibleContainerViewTappedCloseButton:(id)arg1;
- (void)dealloc;
- (void)unsubscribeFromEnteringBackgroundEvents;
- (void)reactToApplicationEnteringBackground:(id)arg1;
- (void)finalizeAdExperience;
- (void)injectCloseEvent:(_Bool)arg1;
- (void)calculateAdDurationForNativeClose;
- (void)storeViewLoadSuccessful;
- (void)viewablePropertyChange:(_Bool)arg1;
- (void)orientationPropertyChangeWithNewSize:(struct CGSize)arg1;
- (void)loadAdWithPlayOptions:(id)arg1;
- (id)initWithMRAIDPlacement:(id)arg1 cacheManager:(id)arg2 adFrame:(struct CGRect)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

