//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, VungleNetworkManager, VungleOperationQueue;

@interface VungleReportAdController : NSObject
{
    _Bool _isSendingReports;
    VungleNetworkManager *_networkManager;
    VungleOperationQueue *_reportAdQueue;
    NSURL *_URL;
}

@property(nonatomic) _Bool isSendingReports; // @synthesize isSendingReports=_isSendingReports;
@property(copy, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) VungleOperationQueue *reportAdQueue; // @synthesize reportAdQueue=_reportAdQueue;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
- (void).cxx_destruct;
- (id)sortSavedAdReportsByCreationDate:(id)arg1;
- (id)savedAdReportsDirectoryContentsWithError:(id *)arg1;
- (id)sortedSavedReportURLs;
- (void)dispatchSendReportsOperation:(CDUnknownBlockType)arg1;
- (_Bool)saveReport:(id)arg1 error:(id *)arg2;
- (void)sendSavedReports:(CDUnknownBlockType)arg1;
- (id)initWithURL:(id)arg1 networkManager:(id)arg2;

@end

