//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VungleNetworkManager, VunglePublisherInformation;

@interface VungleRequestStreamingAdController : NSObject
{
    _Bool _internalShouldStream;
    VunglePublisherInformation *_publisherInformation;
    VungleNetworkManager *_networkManager;
    id <VungleRequestStreamingAdControllerDelegate> _delegate;
}

@property(nonatomic) _Bool internalShouldStream; // @synthesize internalShouldStream=_internalShouldStream;
@property(nonatomic) __weak id <VungleRequestStreamingAdControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak VungleNetworkManager *networkManager; // @synthesize networkManager=_networkManager;
@property(copy, nonatomic) VunglePublisherInformation *publisherInformation; // @synthesize publisherInformation=_publisherInformation;
- (void).cxx_destruct;
- (id)noResponseError;
- (id)invalidResponseError;
- (void)sendErrorForPlacement:(id)arg1 error:(id)arg2;
- (id)createStreamingAdWithJSONResponse:(id)arg1 networkResponse:(id)arg2;
- (void)handleRequestStreamingAd:(id)arg1 placement:(id)arg2;
- (void)setShouldStream:(_Bool)arg1;
- (void)sendStreamingAdRequestWithPlacement:(id)arg1 playOptions:(id)arg2;
- (id)initWithNetworkManager:(id)arg1 publisherInformation:(id)arg2 delegate:(id)arg3;

@end

