//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL;

@protocol VungleJSCommandDelegate <NSObject>
- (void)commandClose;
- (void)commandOpenURL:(NSURL *)arg1;
- (void)commandSetOrientationPropertiesWithForceOrientation:(unsigned long long)arg1;
- (void)commandShouldUseCustomClose:(long long)arg1;
@end

