//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue, NSString;

@interface XCDYouTubeClient : NSObject
{
    NSString *_languageIdentifier;
    NSOperationQueue *_queue;
}

+ (id)defaultClient;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) NSString *languageIdentifier; // @synthesize languageIdentifier=_languageIdentifier;
- (void).cxx_destruct;
- (id)queryVideo:(id)arg1 streamURLsToQuery:(id)arg2 options:(id)arg3 cookies:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (id)queryVideo:(id)arg1 cookies:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getVideoWithIdentifier:(id)arg1 cookies:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)getVideoWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)getVideoWithIdentifier:(id)arg1 cookies:(id)arg2 customPatterns:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)initWithLanguageIdentifier:(id)arg1;
- (id)init;

@end

