//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XCDYouTubeDashManifestXML : NSObject
{
    NSString *_XMLString;
}

@property(readonly, nonatomic) NSString *XMLString; // @synthesize XMLString=_XMLString;
- (void).cxx_destruct;
- (id)streamURLs;
- (id)initWithXMLString:(id)arg1;

@end

