//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSArray, NSDictionary, NSError, NSObject, NSOperationQueue, XCDYouTubeVideo;
@protocol OS_dispatch_semaphore;

@interface XCDYouTubeVideoQueryOperation : NSOperation
{
    _Bool _isExecuting;
    _Bool _isFinished;
    XCDYouTubeVideo *_video;
    NSDictionary *_streamURLsToQuery;
    NSArray *_cookies;
    NSDictionary *_streamURLs;
    NSError *_error;
    NSDictionary *_streamErrors;
    NSOperationQueue *_queryQueue;
    NSObject<OS_dispatch_semaphore> *_operationStartSemaphore;
}

+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;
@property(readonly) NSObject<OS_dispatch_semaphore> *operationStartSemaphore; // @synthesize operationStartSemaphore=_operationStartSemaphore;
@property(retain) NSOperationQueue *queryQueue; // @synthesize queryQueue=_queryQueue;
@property _Bool isFinished; // @synthesize isFinished=_isFinished;
@property _Bool isExecuting; // @synthesize isExecuting=_isExecuting;
@property(retain) NSDictionary *streamErrors; // @synthesize streamErrors=_streamErrors;
@property(retain) NSError *error; // @synthesize error=_error;
@property(retain) NSDictionary *streamURLs; // @synthesize streamURLs=_streamURLs;
@property(readonly, copy) NSArray *cookies; // @synthesize cookies=_cookies;
@property(retain) NSDictionary *streamURLsToQuery; // @synthesize streamURLsToQuery=_streamURLsToQuery;
@property(readonly) XCDYouTubeVideo *video; // @synthesize video=_video;
- (void).cxx_destruct;
- (id)description;
- (void)finish;
- (void)finishWithError:(id)arg1;
- (void)finishWithStreamURLs:(id)arg1 streamErrors:(id)arg2;
- (void)startGETOperations:(id)arg1 streamErrors:(id)arg2;
- (void)startQuery;
- (void)cancel;
- (void)start;
- (_Bool)isAsynchronous;
- (id)initWithVideo:(id)arg1 cookies:(id)arg2;
- (id)initWithVideo:(id)arg1 streamURLsToQuery:(id)arg2 options:(id)arg3 cookies:(id)arg4;
- (id)init;

@end

