//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class _YYTextSentinel;

@interface XYYTextAsyncLayer : CALayer
{
    _YYTextSentinel *_sentinel;
    _Bool _displaysAsynchronously;
}

+ (id)defaultValueForKey:(id)arg1;
@property _Bool displaysAsynchronously; // @synthesize displaysAsynchronously=_displaysAsynchronously;
- (void).cxx_destruct;
- (void)_cancelAsyncDisplay;
- (void)_displayAsync:(_Bool)arg1;
- (void)display;
- (void)setNeedsDisplay;
- (void)dealloc;
- (id)init;

@end

