//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "XYYTextLinePositionModifier-Protocol.h"

@class NSString;

@interface XYYTextLinePositionSimpleModifier : NSObject <XYYTextLinePositionModifier>
{
    double _fixedLineHeight;
}

@property double fixedLineHeight; // @synthesize fixedLineHeight=_fixedLineHeight;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)modifyLines:(id)arg1 fromText:(id)arg2 inContainer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

